version: hd
files:
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/main.exe
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/dra.bin
    asset_path: assets/dra
    src_path: src/dra
    splat_config_path: config/splat.hd.dra.yaml
    segments:
      - start: 0
        vram: 0x800A0000
        assets:
          - [0x0, skip]
          - [0x518, palette, g_saveIconPal, 256]
          - [0x718, rawgfx, g_saveIcon0, 16, 48, 4, 0x518]
          - [0x898, rawgfx, g_saveIcon1, 16, 48, 4, 0x538]
          - [0xA18, rawgfx, g_saveIcon2, 16, 48, 4, 0x558]
          - [0xB98, rawgfx, g_saveIcon3, 16, 48, 4, 0x578]
          - [0xD18, rawgfx, g_saveIcon4, 16, 48, 4, 0x598]
          - [0xE98, rawgfx, g_saveIcon5, 16, 48, 4, 0x5B8]
          - [0x1018, rawgfx, g_saveIcon6, 16, 48, 4, 0x5D8]
          - [0x1198, rawgfx, g_saveIcon7, 16, 48, 4, 0x5F8]
          - [0x1318, rawgfx, g_saveIcon8, 16, 48, 4, 0x618]
          - [0x1498, rawgfx, g_saveIcon9, 16, 48, 4, 0x638]
          - [0x1618, rawgfx, g_saveIcon10, 16, 48, 4, 0x658]
          - [0x1798, rawgfx, g_saveIcon11, 16, 48, 4, 0x678]
          - [0x1918, rawgfx, g_saveIcon12, 16, 48, 4, 0x698]
          - [0x1A98, rawgfx, g_saveIcon13, 16, 48, 4, 0x6A8]
          - [0x1C18, rawgfx, g_saveIcon14, 16, 48, 4, 0x6C8]
          - [0x1D98, rawgfx, g_saveIcon15, 16, 48, 4, 0x6E8]
          - [0x22E4, skip]
          - [0xD298, blueprintsdef, hd/blueprints, AluBlueprints, AluEntities]
          - [0xD57C, skip]
          - [0x11140, binary, hd/vh_0, vh]
          - [0x14140, binary, hd/vh_1, vh]
          - [0x16140, binary, hd/vh_2, vh]
          - [0x18140, binary, hd/vh_3, vh]
          - [0x1A140, binary, sd_eve1, seq, --skip-build]
          - [0x1C441, binary, sd_eve3, seq, --skip-build]
          - [0x1CB87, binary, sd_eve2, seq, --skip-build]
          - [0x1D140, skip]
          - [0x1D2E8, xamusicconfig, hd/xa_music_config]
          - [0x1F5F8, sfxconfig, hd/sfx_config]
          - [0x20A20, skip]
          - [0x22220, cmpgfx, hd/text_item_up, 128, 128, 4]
          - [0x22854, cmpgfx, hd/load_room_obj, 128, 128, 4]
          - [0x23604, cmpgfx, hd/save_room_obj, 128, 128, 4]
          - [0x24908, cmpgfx, hd/load_room_tile, 80, 16, 4]
          - [0x24B34, cmpgfx, hd/save_room_tile, 80, 16, 4]
          - [0x24D90, headergfx, D_800C4CEC]
          - [0x24E14, headergfx, D_800C4D70]
          - [0x24E98, headergfx, D_800C4DF4]
          - [0x24F1C, headergfx, D_800C4E78]
          - [0x24FA0, headergfx, D_800C4EFC]
          - [0x25024, headergfx, D_800C4F80]
          - [0x250A8, headergfx, D_800C5004]
          - [0x2512C, headergfx, D_800C5088]
          - [0x251B0, headergfx, D_800C510C]
          - [0x25234, headergfx, D_800C5190]
          - [0x252B8, headergfx, D_800C5214]
          - [0x2539C, skip]
          - [0x253C8, rawgfx, g_GfxEquipIcon, 16, 5120, 4]
          - [0x2F3C8, skip]
          - [0x2FFB4, spriteset, hd/D_800CFF10]
          - [0x3100C, spriteset, hd/D_800D0F68]
          - [0x32C98, spriteset, hd/D_800D2BF4]
          - [0x32D9C, spriteset, hd/D_800D2CF8]
          - [0x330A0, spriteset, hd/D_800D2FFC]
          - [0x33320, spriteset, hd/D_800D327C]
          - [0x334CC, spriteset, hd/D_800D3428]
          - [0x3355C, spriteset, hd/D_800D34B8]
          - [0x337D0, spriteset, hd/D_800D372C]
          - [0x33C2C, spriteset, hd/D_800D3B88]
          - [0x356CC, spriteset, hd/D_800D5628]
          - [0x35750, spriteset, hd/D_800D56AC]
          - [0x3590C, spriteset, hd/D_800D5868]
          - [0x368F0, spriteset, hd/D_800D684C]
          - [0x36978, palette, D_800D68D4, 16]
          - [0x36998, palette, D_800D68F4, 16]
          - [0x369B8, palette, D_800D6914, 16]
          - [0x369D8, palette, D_800D6934, 16]
          - [0x369F8, palette, D_800D6954, 16]
          - [0x36A18, palette, D_800D6974, 16]
          - [0x36A38, palette, D_800D6994, 16]
          - [0x36A58, palette, D_800D69B4, 16]
          - [0x36A78, palette, D_800D69D4, 16]
          - [0x36A98, palette, D_800D69F4, 16]
          - [0x36AB8, palette, D_800D6A14, 16]
          - [0x36AD8, palette, D_800D6A34, 16]
          - [0x36B78, palette, D_800D6AD4, 16]
          - [0x36D78, palette, D_800D6CD4, 16]
          - [0x36F78, palette, D_800D6ED4, 16]
          - [0x37178, palette, D_800D70D4, 16]
          - [0x37378, palette, D_800D72D4, 16]
          - [0x38978, skip]
          - [0x3B178, palette, D_800DB0D4, 16]
          - [0x3B198, palette, D_800DB0F4, 16]
          - [0x3B1B8, palette, D_800DB114, 16]
          - [0x3B298, palette, D_800DB1F4, 16]
          - [0x3B458, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/fname.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/sd.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/ric.bin
    asset_path: assets/ric
    src_path: src/ric
    splat_config_path: config/splat.hd.ric.yaml
    segments:
      - start: 0
        vram: 0x8013C000
        assets:
          - [0x0, skip]
          - [0x20, spritesheet, richter, disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/f_game2.bin, 0x40400]
          - [0x170AC, skip]
          - [0x18688, subweaponsdef, subweapons, RicSubweapons, RicBlueprints]
          - [0x188F4, skip]
          - [0x18A6C, blueprintsdef, hd/blueprints, RicBlueprints, RicEntities]
          - [0x18C42, skip]
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/are.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/cat.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/cen.bin
    asset_path: assets/st/cen
    src_path: src/st/cen
    splat_config_path: config/splat.hd.stcen.yaml
    segments:
      - start: 0
        vram: 0x80180000
        assets:
          - [0x40, sprite_banks, sprite_banks]
          - [0xA0, paldef, palette_def]
          - [0xDC, layers, layers]
          - [0x134, gfx_banks, graphics_banks]
          - [0x1EC, layout, entity_layouts]
          - [0x394, skip]
          - [0x1308, rooms, rooms]
          - [0x1334, skip]
          - [0x1678, cmpgfx, stage_title_cen_jp, 128, 128, 4]
          - [0x19BC, cmpgfx, stage_placeholder_cen, 128, 128, 4]
          - [0x1F60, binary, D_80181F60]
          - [0x3A60, cmpgfx, e_maria_cen_g0, 128, 128, 4, 0x69AC]
          - [0x4B90, cmpgfx, e_maria_cen_g1, 128, 128, 4, 0x69AC]
          - [0x5850, cmpgfx, e_elevator_cen_g, 128, 128, 4, 0x69CC]
          - [0x65AC, palette, D_8018658C, 16]
          - [0x66AC, palette, D_8018668C, 16] # unused
          - [0x67AC, palette, D_8018678C, 16]
          - [0x68AC, palette, D_8018688C, 16] # unused
          - [0x69AC, palette, e_maria_cen_p, 16]
          - [0x69CC, palette, e_elevator_cen_p, 16]
          - [0x6A0C, skip] # tile data
          - [0x820C, tiledef, unused]
          - [0x861C, skip] # the other used tile definition
          - [0xC62C, skip] # sprites
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/chi.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/dai.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/dre.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/lib.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/mad.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/no0.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/no1.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/no2.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/no3.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/no4.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/np3.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/nz0.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/nz1.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/sel.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/st0.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/te1.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/te2.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/te3.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/te4.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/te5.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/tek.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/top.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/wrp.bin
    asset_path: assets/st/wrp
    src_path: src/st/wrp
    splat_config_path: config/splat.hd.stwrp.yaml
    segments:
      - start: 0
        vram: 0x80180000
        assets:
          - [0x40, sprite_banks, sprite_banks]
          - [0xA0, paldef, palette_def]
          - [0xB8, layers, layers]
          - [0x1B8, gfx_banks, graphics_banks]
          - [0x23C, layout, entity_layouts]
          - [0x3E4, skip]
          - [0x11B0, rooms, rooms]
          - [0x122C, skip]
          - [0x1424, cmpgfx, stage_title_wrp_jp, 128, 128, 4]
          - [0x1768, cmpgfx, stage_placeholder_wrp, 128, 128, 4]
          - [0x1D0C, palette, D_80181D08, 16]
          - [0x1D2C, palette, D_80181D28, 16] # unused
          - [0x1D6C, skip] # tile data
          - [0x296C, skip] # tile definitions
          - [0x6D8C, skip] # sprites
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rare.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rcat.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rcen.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rchi.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rdai.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rlib.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rno0.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rno1.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rno2.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rno3.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rno4.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rnz0.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rnz1.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rtop.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rwrp.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/mar.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/bo0.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/bo1.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/bo2.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/bo3.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/bo4.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/bo5.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/bo6.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/bo7.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rbo0.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rbo1.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rbo2.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rbo3.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rbo4.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rbo5.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rbo6.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rbo7.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/rbo8.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/tt_000.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/tt_001.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/tt_002.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/tt_003.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/tt_004.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/tt_005.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/tt_006.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_000.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_001.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_002.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_003.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_004.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_005.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_006.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_007.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_008.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_009.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_010.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_011.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_012.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_013.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_014.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_015.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_016.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_017.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_018.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_019.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_020.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_021.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_022.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_023.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_024.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_025.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_026.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_027.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_028.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_029.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_030.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_031.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_032.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_033.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_034.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_035.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_036.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_037.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_038.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_039.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_040.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_041.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_042.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_043.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_044.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_045.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_046.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_047.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_048.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_049.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_050.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_051.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_052.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_053.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_054.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_055.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_056.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_057.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w0_058.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_000.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_001.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_002.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_003.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_004.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_005.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_006.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_007.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_008.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_009.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_010.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_011.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_012.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_013.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_014.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_015.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_016.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_017.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_018.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_019.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_020.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_021.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_022.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_023.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_024.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_025.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_026.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_027.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_028.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_029.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_030.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_031.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_032.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_033.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_034.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_035.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_036.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_037.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_038.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_039.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_040.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_041.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_042.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_043.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_044.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_045.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_046.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_047.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_048.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_049.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_050.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_051.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_052.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_053.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_054.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_055.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_056.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_057.bin
  - target: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/w1_058.bin
