options:
  platform: psx
  basename: ric
  base_path: ..
  build_path: build/hd
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/ric.bin
  asm_path: asm/hd/ric
  asset_path: assets/ric
  src_path: src/ric
  ld_script_path: build/hd/ric.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.hd.txt
    - config/symbols.hd.ric.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.hd.ric.txt
  undefined_syms_auto_path: config/undefined_syms_auto.hd.ric.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  extensions_path: tools/splat_ext
  symbol_name_format: hd_$VRAM
  disassemble_all: true
  section_order:
    - .data
    - .rodata
    - .text
    - .bss
    - .sbss
  ld_bss_is_noload: false
  disasm_unknown: true
sha1: 1dcd6b881e2c0906854c3d53839dfb4ae0d359d6
segments:
  - name: ric
    type: code
    start: 0
    vram:  0x8013C000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .data, pl_header]
      - [0x20, spritesheet, richter, disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/f_game2.bin, 32]
      - [0x170AC, .data, spriteparts]
      - [0x18568, .data, d_18568]
      - [0x18688, assets, subweapondefs, D_80154688]
      - [0x188F4, .data, 238F8]
      - [0x1895C, .data, 238F8] # entity table
      - [0x18A6C, .data, 238F8] # blueprints
      - [0x18C40, .data, 24788]
      - [0x18F7C, .data, 26C84]
      - [0x1938C, .data, pl_anims]
      - [0x199AC, .data, 2A060]
      - [0x19D94, .data, 2C4C4]
      - [0x19EE0, .data, 319C4]
      - [0x19EFC, .data, e_giant_spinning_cross]
      - [0x1A444, .rodata, pl_main]
      - [0x1A5F8, .rodata, pl_debug]
      - [0x1A608, .rodata, pl_handlers]
      - [0x1A7C0, .rodata, pl_handlers]
      - [0x1A7D8, .rodata, pl_setstep]
      - [0x1A8D0, .rodata, pl_collision]
      - [0x1A8D4, .rodata, 238F8]
      - [0x1A8E4, .rodata, 24788]
      - [0x1A9B4, .rodata, 26C84]
      - [0x1A9F4, .rodata, 2A060]
      - [0x1AA88, .rodata, 2C4C4]
      - [0x1AB04, .rodata, 319C4]
      - [0x1AC1C, .rodata, e_giant_spinning_cross]
      - [0x1AC2C, c, pl_main]
      - [0x1C7E4, c, pl_debug]
      - [0x1CB28, c, pl_handlers]
      - [0x202B0, c, pl_utils]
      - [0x20BE4, c, pl_setstep]
      - [0x21B00, c, pl_collision]
      - [0x23834, c, 238F8]
      - [0x246C4, c, 24788]
      - [0x26DD8, c, 26C84]
      - [0x29F9C, c, 2A060]
      - [0x2C42C, c, 2C4C4]
      - [0x31918, c, 319C4]
      - [0x371E0, c, e_giant_spinning_cross]
      - [0x37AB8, .bss, pl_handlers]
      - [0x38ED0, .bss, pl_collision]
      - [0x38ED4, .bss, 238F8]
      - [0x38F54, .bss, 2A060]
      - [0x38FDC, .bss, 2C4C4]
      - [0x397E8, .bss, 319C4]
      - [0x39834, bss]
  - [0x399AC]
