options:
  platform: psp
  basename: stnp3
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/np3.bin
  asm_path: asm/pspeu/st/np3_psp
  asset_path: assets/st/np3
  src_path: src/st
  ld_script_path: build/pspeu/stnp3.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.stnp3.txt
  undefined_funcs_auto_path: build/pspeu/config/undefined_funcs_auto.pspeu.stnp3.txt
  undefined_syms_auto_path: build/pspeu/config/undefined_syms_auto.pspeu.stnp3.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  disassemble_all: true
  global_vram_start: 0x8000000
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: 78660301541f3b90d2b6d39d9b7dde4343481b65
segments:
  - [0x0, bin, mwo_header]
  - name: stnp3
    type: code
    start: 0x80
    vram:  0x09237700
    bss_size: 0x380
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, np3_psp/st_init_np3]
      - [0x488, c, np3/e_jewel_sword_puzzle]
      - [0x1138, c, np3/e_stairway]
      - [0x19D8, c, np3/e_background_bushes_trees]
      - [0x22E0, c, np3/slogra]
      - [0x3748, c, np3/e_breakable]
      - [0x38C8, c, np3/e_background_lightning]
      - [0x3CE0, c, np3/e_castle_door]
      - [0x4108, c, np3/e_trapdoor]
      - [0x42B8, c, np3/gaibon]
      - [0x65C0, c, np3/e_tilemap_shuffler]
      - [0x66F8, c, np3/e_shutting_window]
      - [0x6A98, c, np3/e_unkId16]
      - [0x6B70, c, np3/e_room_bg]
      - [0x6C68, c, np3/e_lock_camera]
      - [0x6EC8, c, np3/e_cavern_door]
      - [0x78A8, c, np3/entrance_weights]
      - [0x8210, c, np3/e_heartroom]
      - [0x8810, c, np3/e_explosion_puff_opaque]
      - [0x8E60, c, np3/e_sky_entities]
      - [0x9038, c, np3/e_transparent_water]
      - [0x9428, c, np3/create_entity]
      - [0xA3D0, c, np3/e_bloody_zombie]
      - [0xB850, c, np3/e_bat]
      - [0xBB88, c, np3/e_stage_name]
      - [0xCA08, c, np3/e_red_door]
      - [0xDD10, c, np3/st_update]
      - [0xE248, c, np3/e_merman2]
      - [0x10A48, c, np3/e_merman]
      - [0x11F70, c, np3/e_particles]
      - [0x13500, c, np3/e_collect]
      - [0x17750, c, np3/e_misc]
      - [0x18260, c, np3/collision]
      - [0x1A438, c, np3/e_bone_scimitar]
      - [0x1B070, c, np3/water_effects]
      - [0x1E0E0, c, np3/popup]
      - [0x1E6D8, c, np3/e_room_fg]
      - [0x1E7F0, c, np3/e_owl_knight]
      - [0x223D8, c, np3/st_common]
      - [0x23E08, c, np3/giantbro_helpers]
      - [0x24870, c, np3/blade]
      - [0x266B0, c, np3/gurkha]
      - [0x280F0, c, np3_psp/working_on]
      - [0x2A0B8, c, np3/e_zombie]
      - [0x2A588, c, np3/prim_helpers]
      - [0x2B100, data]
      - [0x571D0, .data, np3/e_jewel_sword_puzzle]
      - [0x572E0, .data, np3/e_background_bushes_trees]
      - [0x57390, .data, np3/slogra]
      - [0x575A0, .data, np3/e_breakable]
      - [0x575F0, .data, np3/e_background_lightning]
      - [0x57628, .data, np3/e_castle_door]
      - [0x57718, .data, np3/e_trapdoor]
      - [0x57728, .data, np3/gaibon]
      - [0x578C8, data] # heart drop data, weirdly out of order
      - [0x578E0, .data, np3/e_shutting_window]
      - [0x57930, data]
      - [0x57B40, .data, np3/e_lock_camera]
      - [0x57BB8, .data, np3/e_cavern_door]
      - [0x57BC8, .data, np3/e_explosion_puff_opaque]
      - [0x57C38, .data, np3/e_sky_entities]
      - [0x57C58, .data, np3/e_transparent_water]
      - [0x57C98, .data, np3/e_bloody_zombie]
      - [0x57D98, .data, np3/e_bat]
      - [0x57DD8, .data, np3/e_red_door]
      - [0x57DF0, .data, np3/st_update]
      - [0x57E20, .data, np3/e_merman2]
      - [0x57F48, .data, np3/e_merman]
      - [0x58088, .data, np3/e_particles]
      - [0x58108, .data, np3/e_collect]
      - [0x58650, .data, np3/e_misc]
      - [0x586A0, .data, np3/collision]
      - [0x58A78, .data, np3/e_bone_scimitar]
      - [0x58B80, .data, np3/water_effects]
      - [0x58C30, .data, np3/e_room_fg]
      - [0x58CD0, .data, np3/e_owl_knight]
      - [0x58FC0, .data, np3/st_common]
      - [0x591C0, .data, np3/giantbro_helpers]
      - [0x59200, .data, np3/blade]
      - [0x598C8, .data, np3/gurkha]
      - [0x59D90, data]
      - [0x5A2F0, .data, np3/e_zombie]
      - [0x5A380, .rodata, np3/e_stage_name]
      - [0x5A3A8, .rodata, np3/e_red_door]
      - [0x5A3C0, .rodata, np3/e_particles]
      - [0x5A410, .rodata, np3/e_collect]
      - [0x5A448, .rodata, np3/e_misc]
      - [0x5A470, .rodata, np3/water_effects]
      - [0x5A490, .rodata, np3/giantbro_helpers]
      - [0x5A4F0, .rodata, np3/blade]
      - [0x5A508, .rodata, np3/gurkha]
      - [0x5A580, bss, 5A580]
      - [0x5A7F0, .bss, np3/e_background_bushes_trees]
      - [0x5A800, .bss, np3/slogra]
      - [0x5A808, .bss, np3/e_breakable]
      - [0x5A810, .bss, np3/e_trapdoor]
      - [0x5A818, .bss, np3/e_shutting_window]
      - [0x5A828, .bss, np3/e_lock_camera]
      - [0x5A830, .bss, np3/create_entity]
      - [0x5A850, .bss, np3/e_collect]
      - [0x5A8B0, bss, 5A8B0]
  - [0x5A900]
