options:
  platform:     psx
  basename:     main
  base_path:    .
  target_path:  iso/SLUS_000.67
  asm_path:     asm/main
  asset_path:   assets/main
  src_path:     src/main
  compiler:     GCC
  symbol_addrs_path:    config/symbols.txt
  undefined_syms_path:  config/undefined_syms.main.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.main.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.main.txt
  find_file_boundaries: yes
  enable_ld_alignment_hack: yes
  use_legacy_include_asm: no
segments:
  - [0x800, header]
  - name: main
    type: code
    start: 0x00000800
    vram:  0x80010000
    subalign: 4
    subsegments:
      - [0x800, data]
      - [0x15F4, asm]
      - [0x5938, hasm, psxsdk/libapi1]
      - [0x5A38, c]
      - [0x5E60, c, psxsdk/libetc]
      - [0x5E78, c]
      - [0x6864, hasm, psxsdk/libc]
      - [0x6934, c, psxsdk/fprintf]
      - [0x7190, c]
      - [0x720C, hasm, psxsdk/libcard]
      - [0x72A4, c]
      - [0x9C14, hasm, psxsdk/libapi2]
      - [0x9C24, c, psxsdk/libapi]
      - [0x9C54, asm]
      - [0x1BCE0, data]
  - [0x89800]
