options:
  platform:     psx
  basename:     main
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/SLUS_000.67
  asm_path:     asm/us/main
  asset_path:   assets/main
  src_path:     src/main
  compiler:     GCC
  symbol_addrs_path:    config/symbols.us.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.main.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.main.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  asm_jtbl_label_macro: jlabel
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
segments:
  - [0x800, header]
  - name: main
    type: code
    start: 0x00000800
    vram:  0x80010000
    subalign: 4
    subsegments:
      - [0x800, rodata]
      - [0x874, rodata]
      - [0xC94, rodata]
      - [0xEB4, rodata]
      - [0x15F4, asm]
      - [0x5938, hasm, psxsdk/libapi1]
      - [0x5A38, c]
      - [0x5E60, c, psxsdk/libetc]
      - [0x5E78, c]
      - [0x6864, hasm, psxsdk/libc]
      - [0x6934, c, psxsdk/sprintf]
      - [0x7190, c]
      - [0x720C, hasm, psxsdk/libcard]
      - [0x72A4, c]
      - [0x9C14, hasm, psxsdk/libapi2]
      - [0x9C24, c, psxsdk/libapi]
      - [0x9C54, asm]

      - [0xCF30, c, psxsdk/libcd/c_011]
      - [0xDA90, c, psxsdk/libsnd/scsmvol]
      - [0xDAE0, c, psxsdk/libsnd/scssattr]
      - [0xDB74, c, psxsdk/libsnd/scssvol]
      - [0xDC70, c, psxsdk/libsnd/seqinit]
      - [0xE064, c, psxsdk/libsnd/seqread]
      - [0xFD04, c, psxsdk/libsnd/miditime]
      - [0xFDBC, c, psxsdk/libsnd/ccadsr]
      - [0xFEA4, c, psxsdk/libsnd/next]
      - [0xFFAC, c, psxsdk/libsnd/ssvkoff]
      - [0xFFE8, c, psxsdk/libsnd/ssvkon]
      - [0x10034, c, psxsdk/libsnd/sscall]
      - [0x102A8, c, psxsdk/libsnd/cres]
      - [0x10830, c, psxsdk/libsnd/pause]
      - [0x108D0, c, psxsdk/libsnd/play]
      - [0x108FC, c, psxsdk/libsnd/replay]
      - [0x10964, c, psxsdk/libsnd/ssclose]
      - [0x10B28, c, psxsdk/libsnd/ssinit]
      - [0x10C10, c, psxsdk/libsnd/ssinit_h]
      - [0x10C40, c, psxsdk/libsnd/ssquit]
      - [0x10C60, c, psxsdk/libsnd/ssstart]
      - [0x10F98, c, psxsdk/libsnd/sstick]
      - [0x11104, c, psxsdk/libsnd/ssend]
      - [0x111B4, c, psxsdk/libsnd/sstable]
      - [0x11394, c, psxsdk/libsnd/ssplay]
      - [0x11504, c, psxsdk/libsnd/ssvol]
      - [0x115D8, c, psxsdk/libsnd/stop]
      - [0x11798, c, psxsdk/libsnd/tempo]
      - [0x11974, c, psxsdk/libsnd/vs_mono]
      - [0x11998, c, psxsdk/libsnd/vs_srv]
      - [0x119D0, c, psxsdk/libsnd/vs_vab]
      - [0x11AAC, c, psxsdk/libsnd/vs_vfb]
      - [0x11B1C, c, psxsdk/libsnd/vs_vh]
      - [0x11FC0, c, psxsdk/libsnd/vs_vtb]
      - [0x12080, c, psxsdk/libsnd/vs_vtbp]
      - [0x121E0, c, psxsdk/libsnd/vs_vtc]
      - [0x1220C, c, psxsdk/libsnd/vm_doff]
      - [0x1221C, c, psxsdk/libsnd/vm_don]
      - [0x12230, c, psxsdk/libsnd/ut_gpa]
      - [0x12338, c, psxsdk/libsnd/vm_vsu]
      - [0x123FC, c, psxsdk/libsnd/ut_gva]
      - [0x12638, c, psxsdk/libsnd/ut_rev]
      - [0x126EC, c, psxsdk/libsnd/ut_ron]
      - [0x1270C, c, psxsdk/libsnd/ut_roff]
      - [0x1272C, c, psxsdk/libsnd/ut_rfb]
      - [0x1276C, c, psxsdk/libsnd/ut_rdep]
      - [0x12804, c, psxsdk/libsnd/ut_rdel]
      - [0x12844, c, psxsdk/libsnd/ut_sva]
      - [0x12A0C, c, psxsdk/libsnd/vmanager]
      - [0x1785C, c, psxsdk/libspu/s_i]
      - [0x1787C, c, psxsdk/libspu/s_ini]

      - [0x179C8, asm, psxsdk_stuff]
      - [0x1BCE0, data]
  - [0x89800]
