options:
  platform: psp
  basename: stchi
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/chi.bin
  asm_path: asm/pspeu/st/chi_psp
  asset_path: assets/st/chi
  src_path: src/st
  ld_script_path: build/pspeu/stchi.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.stchi.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.pspeu.stchi.txt
  undefined_syms_auto_path: config/undefined_syms_auto.pspeu.stchi.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: psp_$VRAM
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  disassemble_all: true
  global_vram_start: 0x8000000
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
  ld_generate_symbol_per_data_segment: true
sha1: 6d2113b98203cfd239b58a7822910f9febb4c1ef
segments:
  - [0x0, bin, mwo_header]
  - name: stchi
    type: code
    start: 0x80
    vram:  0x09237700
    bss_size: 0x180
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, chi/ut_create_entity]
      - [0x1028, c, chi/en_salem_witch]
      - [0x3170, c, chi/en_venus_weed]
      - [0x5C28, c, chi/en_red_door]
      - [0x6F30, c, chi/st_update]
      - [0x7468, c, chi/en_particles]
      - [0x89F8, c, chi/en_collect]
      - [0xC300, c, chi/en_misc]
      - [0xD350, c, chi/st_collision]
      - [0xF528, c, chi/en_popup]
      - [0xFB20, c, chi/en_room_foreground]
      - [0xFC38, c, chi/ut_common]
      - [0x10DC0, c, chi/ut_prim_helpers]
      - [0x11550, c, chi/en_gremlin]
      - [0x120D0, c, chi/en_thornweed_corpseweed]
      - [0x13DD8, c, chi/en_debug_cerberus_gate]
      - [0x144C0, c, chi_psp/st_init_chi]
      - [0x146A0, c, chi/en_breakable]
      - [0x14F50, c, chi/en_stage_name]
      - [0x15E08, c, chi/e_room_bg]
      - [0x15F18, c, chi/e_lock_camera]
      - [0x16178, c, chi/en_falling_stairs]
      - [0x17440, c, chi/en_demon_switch_wall]
      - [0x17C80, c, chi_psp/en_breakable_wall]
      - [0x18900, .data, chi/en_salem_witch]
      - [0x18AC8, .data, chi/en_venus_weed]
      - [0x18C38, .data, chi/en_red_door]
      - [0x18C50, .data, chi/st_update]
      - [0x18C80, .data, chi/en_particles]
      - [0x18D00, .data, chi/en_collect]
      - [0x19248, .data, chi/en_misc]
      - [0x19298, .data, chi/st_collision]
      - [0x19670, .data, chi/en_room_foreground]
      - [0x19710, .data, chi/en_gremlin]
      - [0x19770, .data, chi/en_thornweed_corpseweed]
      - [0x19840, data]
      - [0x1D3F8, .data, chi/e_red_door_tiles]
      - [0x1D428, .data, chi_psp/dt_entity]
      - [0x1D630, data]
      - [0x1D6D0, .data, chi/en_breakable]
      - [0x1D758, .data, chi/en_stage_name]
      - [0x1EA58, data]
      - [0x34080, .data, chi/background_block_init]
      - [0x340C0, .data, chi/e_lock_camera]
      - [0x34138, .data, chi/en_falling_stairs]
      - [0x341B8, .data, chi/en_demon_switch_wall]
      - [0x341E8, data]
      - [0x34300, .rodata, chi/en_venus_weed]
      - [0x34368, .rodata, chi/en_red_door]
      - [0x34380, .rodata, chi/en_collect]
      - [0x343E0, .rodata, chi/en_thornweed_corpseweed]
      - [0x34420, .rodata, chi/en_debug_cerberus_gate]
      - [0x34438, .rodata, chi/en_stage_name]
      - [0x34450, .rodata, chi_psp/en_breakable_wall]
      - {start: 0x34480, type: .bss, vram: 0x0926BB00, name: chi/ut_create_entity}
      - {start: 0x34480, type: .bss, vram: 0x0926BB20, name: chi/en_collect} # g_ItemIconSlots
      - {start: 0x34480, type: bss, vram: 0x0926BB80, name: bss1}
      - {start: 0x34480, type: .bss, vram: 0x0926BB90, name: chi_psp/st_init_chi}
      - {start: 0x34480, type: .bss, vram: 0x0926BC78, name: chi/e_lock_camera}
  - [0x34480]
