options:
  platform:     psx
  basename:     stwrp
  base_path:    ..
  target_path:  iso/ST/WRP/WRP.BIN
  asm_path:     asm/st/wrp
  asset_path:   assets/st/wrp
  src_path:     src/st/wrp
  compiler:     GCC
  symbol_addrs_path:    config/generated.symbols.us.stwrp.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.stwrp.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.stwrp.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  section_order:
    - ".data"
    - ".rodata"
    - ".text"
    - ".bss"
segments:
  - name: stwrp
    type: code
    start: 0x00000000
    vram:  0x80180000
    subalign: 4
    subsegments:
      - [0x0, .data, 6FD0]
      - [0x2968, .data, tiledef1]
      - [0x2D78, .data, tiledef2]
      - [0x6D88, .data, spriteparts]
      - [0x6E30, .rodata, 6FD0]
      - [0x6E70, rodata] # EntityWarpRoom
      - [0x6E90, rodata] # EntityWarpSmallRocks
      - [0x6EA8, rodata] # EntityRedDoor
      - [0x6EC0, rodata] # CollectGold
      - [0x6F10, rodata] # EntityPriceDrop
      - [0x6F30, rodata] # EntityInventoryDrop
      - [0x6F48, rodata] # EntityRelicOrb
      - [0x6F80, rodata] # EntityUnkId0E
      - [0x6F94, rodata] # EntityStageNamePopup
      - [0x6FD0, c]
      - [0x13AA0, sbss] # bss?
  - [0x14768]
