options:
  platform: psx
  basename: stno1
  base_path: ..
  build_path: build/us
  target_path: disks/us/ST/NO1/NO1.BIN
  asm_path: asm/us/st/no1
  asset_path: assets/st/no1
  src_path: src/st/no1
  ld_script_path: build/us/stno1.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.stno1.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.stno1.txt
  undefined_syms_auto_path: config/undefined_syms_auto.us.stno1.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: us_$VRAM
  disassemble_all: true
  section_order:
    - .data
    - .rodata
    - .text
    - .bss
    - .sbss
  ld_bss_is_noload: false
  disasm_unknown: true
sha1: 41ccd886308d5527684ae2c41164ecf6c554721f
segments:
  - name: stno1
    type: code
    start: 0
    vram: 0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .data, header]
      - [0x2C, data]
      - [0x618, .data, e_laydef]
      - [0x7C0, .data, e_init]
      - [0xB60, .data, e_environment]
      - [0xC84, .data, e_red_door]
      - [0xC9C, data]
      - [0xCFC, .data, st_debug]
      - [0xD7C, data]
      - [0xF48, .data, e_mouse]
      - [0xF8C, data]
      - [0x1508, .data, unk_3B5E0]
      - [0x1540, data, unk_3CB34]
      - [0x1570, .data, unk_3D8AC]
      - [0x15F4, data]
      - [0x1A2C, .data, d_prize_drops]
      - [0x1A5C, .data, st_update]
      - [0x1A88, .data, collision]
      - [0x1E48, .data, st_common]
      - [0x2048, .data, e_collect]
      - [0x2338, .data, e_misc]
      - [0x2450, .data, e_blue_axe_knight]
      - [0x2610, .data, e_particles]
      - [0x2690, .data, e_room_fg]
      - [0x271C, data]
      - [0x272C, .data, e_skeleton]
      - [0x281C, data]
      - [0x2998, .data, e_bone_musket]
      - [0x2A80, .data, e_sword_lord]
      - [0x2BD8, .data, e_bone_archer]
      - [0x2D4C, .data, e_armor_lord]
      - [0x2E2C, data]
      - [0x31E0, .data, unk_54400]
      - [0x3230, .data, e_skeleton_ape]
      - [0x33D0, .data, e_medusa_head]
      - [0x3448, .data, e_mist_door]
      - [0x3488, .data, rooms]
      - [0x3544, .data, e_layout]
      - [0x44FC, data]
      - [0x34668, .rodata, e_environment]
      - [0x34670, .rodata, e_red_door]
      - [0x34688, .rodata, unk_35E20]
      - [0x346BC, .rodata, e_chair]
      - [0x346D0, .rodata, unk_381E8]
      - [0x3479C, .rodata, unk_3B5E0]
      - [0x347BC, .rodata, unk_3CB34]
      - [0x347D8, .rodata, unk_3D8AC]
      - [0x34810, .rodata, e_wall_chicken_secret]
      - [0x3486C, .rodata, unk_3FA34]
      - [0x348A8, .rodata, e_collect]
      - [0x34930, .rodata, e_misc]
      - [0x3497C, .rodata, e_blue_axe_knight]
      - [0x34A00, .rodata, e_stage_name]
      - [0x34A34, .rodata, e_skeleton]
      - [0x34A50, .rodata, e_wereskeleton]
      - [0x34AD4, .rodata, e_bone_musket]
      - [0x34AFC, .rodata, e_sword_lord]
      - [0x34B60, .rodata, e_bone_archer]
      - [0x34B6C, .rodata, e_armor_lord]
      - [0x34C28, .rodata, e_spear_guard]
      - [0x34C5C, .rodata, unk_54400]
      - [0x34C70, .rodata, e_skeleton_ape]
      - [0x34CB4, .rodata, e_medusa_head]
      - [0x34CBC, .rodata, prim_helpers]
      - [0x34CC4, c, e_environment]
      - [0x34E6C, c, e_red_door]
      - [0x35C64, c, st_debug]
      - [0x35E20, c, unk_35E20]
      - [0x37D24, c, unused]
      - [0x37D34, c, e_mouse]
      - [0x38008, c, e_chair]
      - [0x381E8, c, unk_381E8]
      - [0x3B5E0, c, unk_3B5E0]
      - [0x3C598, c, unk_3CB34]
      - [0x3D8AC, c, unk_3D8AC]
      - [0x3E880, c, e_wall_chicken_secret]
      - [0x3FA34, c, unk_3FA34]
      - [0x419F0, c, st_update]
      - [0x41E24, c, collision]
      - [0x435E0, c, create_entity]
      - [0x44158, c, st_common]
      - [0x45608, c, e_collect]
      - [0x46B74, c, blit_char]
      - [0x46E24, c, e_misc]
      - [0x4A314, c, e_blue_axe_knight]
      - [0x4BB24, c, e_stage_name]
      - [0x4C978, c, e_particles]
      - [0x4D1BC, c, e_room_fg]
      - [0x4D2A8, c, popup]
      - [0x4D5D8, c, e_skeleton]
      - [0x4DDD8, c, e_wereskeleton]
      - [0x4EB28, c, e_bone_musket]
      - [0x4F57C, c, e_sword_lord]
      - [0x50598, c, e_bone_archer]
      - [0x51184, c, e_armor_lord]
      - [0x537A4, c, e_spear_guard]
      - [0x54400, c, unk_54400]
      - [0x549E4, c, e_skeleton_ape]
      - [0x5563C, c, e_medusa_head]
      - [0x55A10, c, e_mist_door]
      - [0x55AF8, c, prim_helpers]
      - [0x56328, bss]
      - [0x56384, .bss, create_entity]
      - [0x56394, bss]
      - [0x57024, .bss, e_collect]
  - [0x57064]
