options:
  platform: psp
  basename: main
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PS.ELF
  asm_path: asm/pspeu/main_psp
  asset_path: assets/main_psp
  src_path: src
  ld_script_path: build/pspeu/main.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.main.txt
  create_undefined_funcs_auto: true
  undefined_funcs_auto_path: build/pspeu/undefined_funcs_auto.pspeu.main.txt
  undefined_syms_auto_path: build/pspeu/undefined_syms_auto.pspeu.main.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  rodata_string_guesser_level: 0
  add_set_gp_64: false
  asm_jtbl_label_macro: jlabel
  symbol_name_format: psp_$VRAM
  disassemble_all: true
  section_order:
    - .text
    - .rodata
    - .data
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  global_vram_start: 0x08000000
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
  ld_generate_symbol_per_data_segment: true
sha1: a3bc73aaa3dc4b873c84a3c0b90e46366f5bbaa9
segments:
  - [0, bin, elf_header]
  - name: main
    type: code
    start: 0x16F4
    vram: 0x08900000
    bss_size: 0x72F150
    align: 4
    subalign: 4
    subsegments:
      - [0x16F4, asm, _open] # kernel_bridge.c
      - [0x178C, asm, _lseek] # kernel_bridge.c
      - [0x18BC, asm, _exit] # kernel_bridge.c
      - [0x1984, asm, _sbrk] # kernel_bridge.c
      - [0x1A74, asm, _read] # kernel_bridge.c
      - [0x1B18, asm, _write] # kernel_bridge.c
      - [0x1BBC, asm, _close] # kernel_bridge.c
      - [0x1C40, asm, _fstat] # kernel_bridge.c
      - [0x1C50, asm, isatty] # kernel_bridge.c
      - [0x1C58, asm, _rename] # kernel_bridge.c
      - [0x1C74, c, main_psp/1C74] # kernel_bridge.c
      - [0x1CBC, asm, __free_heap] # kernel_bridge.c
      - [0x1CF8, asm, clock] # kernel_bridge.c
      - [0x1D14, asm, time] # kernel_bridge.c
      - [0x1D30, asm, _gettimeofday] # kernel_bridge.c
      - [0x1D4C, asm, _times] # kernel_bridge.c
      - [0x1D54, asm, sigfillset] # kernel_bridge.c
      - [0x1D64, asm, sigprocmask] # kernel_bridge.c
      - [0x1D6C, asm, sceGuInit] # libgu.c
      - [0x1EA8, asm, sceGuStart] # libgu.c
      - [0x2110, asm, sceGuFinishId] # libgu.c
      - [0x22B4, asm, sceGuSignalSync] # libgu.c
      - [0x2368, asm, sceGuCallList] # libgu.c
      - [0x241C, asm, sceGuSendList] # libgu.c
      - [0x24C0, asm, sceGuDispBuffer2] # libgu.c
      - [0x259C, asm, sceGuSwapBuffers] # libgu.c
      - [0x2664, asm, sceGuDrawBuffer] # libgu.c
      - [0x277C, asm, sceGuSetAllStatus] # libgu.c
      - [0x2828, asm, sceGuSetDither] # libgu.c
      - [0x2954, asm, sceGuEndObject] # libgu.c
      - [0x29F0, asm, sceGuPatchDivide] # libgu.c
      - [0x2A1C, asm, sceGuColorMaterial] # libgu.c
      - [0x2A44, asm, sceGuSpecular] # libgu.c
      - [0x2A70, asm, sceGuTexScale] # libgu.c
      - [0x2AB4, asm, _sceGuSetDebugFontCallback] # libgu.c
      - [0x2B20, asm, sceGuTerm] # libgu.c
      - [0x2B98, asm, sceGuFinish] # libgu.c
      - [0x2BB4, asm, sceGuGetMemory] # libgu.c
      - [0x2C04, asm, sceGuGetAlignedMemory] # libgu.c
      - [0x2C5C, asm, sceGuCheckList] # libgu.c
      - [0x2C74, asm, sceGuBeginPacket] # libgu.c
      - [0x2CB0, asm, sceGuEndPacket] # libgu.c
      - [0x2CC0, asm, sceGuSignal] # libgu.c
      - [0x2CF8, asm, sceGuSetCallback2] # libgu.c
      - [0x2D34, asm, sceGuBreak] # libgu.c
      - [0x2D54, asm, sceGuContinue] # libgu.c
      - [0x2D70, asm, sceGuCallMode] # libgu.c
      - [0x2D7C, asm, sceGuJumpList] # libgu.c
      - [0x2DC0, asm, sceGuSync] # libgu.c
      - [0x2E2C, asm, sceGuFlush] # libgu.c
      - [0x2E48, asm, sceGuDisplay] # libgu.c
      - [0x2EB4, asm, sceGuDispBuffer] # libgu.c
      - [0x2F28, asm, sceGuDrawBuffer2] # libgu.c
      - [0x2FE0, asm, sceGuDrawBufferList] # libgu.c
      - [0x3030, asm, sceGuDepthBuffer] # libgu.c
      - [0x3084, asm, sceGuEnable] # libgu.c
      - [0x30DC, asm, sceGuDisable] # libgu.c
      - [0x3138, asm, sceGuSetStatus] # libgu.c
      - [0x31C4, asm, sceGuGetStatus] # libgu.c
      - [0x31E8, c, main_psp/31E8] # libgu.c
      - [0x4484, asm, sceGupSetStatus] # libgu.c
      - [0x4690, asm, sceGupSetMatrix] # libgu.c
      - [0x4994, asm, sceGupDrawSprite] # libgu.c
      - [0x4B30, asm, sceGupClear] # libgu.c
      - [0x4E84, asm, sceGupDepthRange] # libgu.c
      - [0x4F2C, asm, sceGupDepthOffset] # libgu.c
      - [0x4FD8, asm, sceGupPatchPrim] # libgu.c
      - [0x5048, asm, sceGupModelColor] # libgu.c
      - [0x50AC, asm, sceGupMaterial] # libgu.c
      - [0x513C, asm, sceGupFrontFace] # libgu.c
      - [0x5168, asm, sceGupLight] # libgu.c
      - [0x51FC, asm, sceGupLightColor] # libgu.c
      - [0x5300, asm, sceGupTexMode] # libgu.c
      - [0x5344, asm, sceGupScissor] # libgu.c
      - [0x53C4, asm, sceGupShadeModel] # libgu.c
      - [0x53F0, asm, _sceGuCallbackSignal] # libgu.c
      - [0x546C, asm, _sceGuCallbackFinish] # libgu.c
      - [0x549C, asm, _sceGuResetGlobalVariables] # libgu.c
      - [0x55A8, asm, _sceGuUpdateStallAddr] # libgu.c
      - [0x5600, asm, sceGuDebugPrint] # libgu.c
      - [0x57E8, asm, sceGuDebugFlush] # libgu.c
      - [0x5A5C, asm, _sceGuDebugFontInit] # libgu.c
      - [0x5AB8, asm, _sceGuDebugSwapBuffer] # libgu.c
      - [0x5ACC, asm, _sceGuDebugDispBuffer] # libgu.c
      - [0x5AE8, asm, _sceGuDebugDrawBuffer] # libgu.c
      - [0x5AFC, asm, func_psp_08904408]
      - [0x5B64, asm, __ieee754_rem_pio2]
      - [0x622C, asm, __ieee754_atan2f]
      - [0x6478, asm, __kernel_cos]
      - [0x67E0, asm, __kernel_rem_pio2]
      - [0x74B8, asm, __kernel_sin]
      - [0x7784, asm, copysign]
      - [0x77A4, asm, cos]
      - [0x78B0, asm, fabs]
      - [0x78BC, asm, floor]
      - [0x7AB8, asm, isinf]
      - [0x7AEC, asm, isnan]
      - [0x7B10, asm, func_psp_0890641C]
      - [0x7B18, asm, scalbn]
      - [0x7CB8, asm, sin]
      - [0x7DC4, asm, atanf]
      - [0x8060, asm, fabsf]
      - [0x8074, asm, func_psp_08906980]
      - [0x8088, asm, func_psp_08906994]
      - [0x81CC, asm, func_psp_08906AD8]
      - [0x81E4, asm, abs]
      - [0x81F0, asm, atexit]
      - [0x82C4, asm, _calloc_r]
      - [0x8380, asm, _close_r]
      - [0x83DC, asm, quorem]
      - [0x8624, asm, _dtoa_r]
      - [0x9A70, asm, func_psp_0890837C]
      - [0x9AB4, asm, exit]
      - [0x9BB4, asm, _fflush_r]
      - [0x9CB0, asm, std]
      - [0x9D08, asm, __sfmoreglue]
      - [0x9D7C, asm, __sfp]
      - [0x9E60, asm, _cleanup_r]
      - [0x9E80, asm, _cleanup]
      - [0x9EA4, asm, __sinit]
      - [0x9F28, asm, func_psp_08908834]
      - [0x9F5C, asm, _free_r]
      - [0xA1D8, asm, _malloc_trim_r]
      - [0xA314, asm, _fstat_r]
      - [0xA378, asm, __sfvwrite_r]
      - [0xA758, asm, _fwalk]
      - [0xA860, asm, __getreent]
      - [0xA888, asm, labs]
      - [0xA894, asm, _setlocale_r]
      - [0xA928, asm, __locale_charset]
      - [0xA934, asm, _localeconv_r]
      - [0xA940, asm, setlocale]
      - [0xA980, asm, localeconv]
      - [0xA9A4, asm, _lseek_r]
      - [0xAA0C, asm, __smakebuf_r]
      - [0xAB74, asm, memalign]
      - [0xABB4, asm, _memalign_r]
      - [0xAD3C, asm, malloc]
      - [0xAD6C, asm, free]
      - [0xAD9C, asm, malloc_extend_top]
      - [0xAFC4, asm, _malloc_r]
      - [0xB50C, asm, memchr]
      - [0xB5F4, asm, memcmp]
      - [0xB678, asm, memcpy]
      - [0xB7B4, asm, memmove]
      - [0xBAB4, asm, memset]
      - [0xBB6C, asm, __malloc_lock]
      - [0xBBA8, asm, __malloc_unlock]
      - [0xBBF4, asm, _getmodreent]
      - [0xBD04, asm, _setmodreent]
      - [0xBE10, asm, _clrmodreent]
      - [0xBE94, asm, _reent_init_ptr]
      - [0xC074, asm, _Balloc]
      - [0xC12C, asm, _Bfree]
      - [0xC158, asm, __multadd]
      - [0xC268, asm, __s2b]
      - [0xC388, asm, __hi0bits]
      - [0xC410, asm, __lo0bits]
      - [0xC4C8, asm, __i2b]
      - [0xC4FC, asm, __multiply]
      - [0xC714, asm, __pow5mult]
      - [0xC82C, asm, __lshift]
      - [0xC964, asm, __mcmp]
      - [0xC9CC, asm, __mdiff]
      - [0xCB48, asm, __ulp]
      - [0xCBB8, asm, __b2d]
      - [0xCCDC, asm, __d2b]
      - [0xCE40, asm, __ratio]
      - [0xCEE0, asm, func_psp_0890B7EC]
      - [0xCF80, asm, func_psp_0890B88C]
      - [0xCFC0, asm, printf]
      - [0xD010, asm, srand]
      - [0xD048, asm, rand]
      - [0xD0D4, asm, _read_r]
      - [0xD13C, asm, _realloc_r]
      - [0xD694, asm, cleanup_glue]
      - [0xD6E8, asm, func_psp_0890BFF4]
      - [0xD77C, asm, _reclaim_reent]
      - [0xD8F0, asm, func_psp_0890C1FC]
      - [0xD9A0, asm, _sbrk_r]
      - [0xD9FC, asm, _init_signal_r]
      - [0xDA5C, asm, _signal_r]
      - [0xDAE4, asm, _raise_r]
      - [0xDBA8, asm, __sigtramp_r]
      - [0xDC44, asm, raise]
      - [0xDC74, asm, signal]
      - [0xDCB4, asm, _init_signal]
      - [0xDCD8, asm, __sigtramp]
      - [0xDD08, asm, _kill_r]
      - [0xDD6C, asm, _getpid_r]
      - [0xDD88, asm, func_psp_0890C694]
      - [0xDDF0, asm, sprintf]
      - [0xDE70, asm, __sread]
      - [0xDEE8, asm, __swrite]
      - [0xDF74, asm, __sseek]
      - [0xDFEC, asm, __sclose]
      - [0xE01C, asm, strcat]
      - [0xE0C8, asm, strcmp]
      - [0xE13C, asm, strcpy]
      - [0xE1D4, asm, strlen]
      - [0xE1EC, asm, func_psp_0890CAF8]
      - [0xE23C, asm, func_psp_0890CB48]
      - [0xE288, asm, func_psp_0890CB94]
      - [0xE330, asm, func_psp_0890CC3C]
      - [0xE3AC, asm, _svfprintf_r]
      - [0xFDC4, asm, cvt]
      - [0xFF8C, asm, func_psp_0890E898]
      - [0x10064, asm, func_psp_0890E970]
      - [0x100D8, asm, func_psp_0890E9E4]
      - [0x10128, asm, func_psp_0890EA34]
      - [0x10194, asm, func_psp_0890EAA0]
      - [0x101E4, asm, func_psp_0890EAF0]
      - [0x1033C, asm, func_psp_0890EC48]
      - [0x1039C, asm, func_psp_0890ECA8]
      - [0x107BC, asm, _write_r]
      - [0x10824, asm, __swsetup_r]
      - [0x10944, c, main_psp/10944]
      - [0x180DC, asm, func_psp_089169E8]
      - [0x181DC, asm, func_psp_08916AE8]
      - [0x18218, asm, func_psp_08916B24]
      - [0x18254, asm, func_psp_08916B60]
      - [0x182AC, asm, func_psp_08916BB8]
      - [0x182F8, asm, func_psp_08916C04]
      - [0x18334, c, main_psp/18334]
      - [0x18608, asm, func_psp_08916F14]
      - [0x18644, asm, func_psp_08916F50]
      - [0x18680, asm, func_psp_08916F8C]
      - [0x186C8, asm, func_psp_08916FD4]
      - [0x1870C, asm, func_psp_08917018]
      - [0x18754, asm, func_psp_08917060]
      - [0x18798, asm, func_psp_089170A4]
      - [0x1882C, asm, func_psp_08917138]
      - [0x188C0, asm, func_psp_089171CC]
      - [0x18944, asm, func_psp_08917250]
      - [0x189D8, asm, func_psp_089172E4]
      - [0x189F4, asm, func_psp_08917300]
      - [0x18A1C, asm, func_psp_08917328]
      - [0x18B8C, asm, func_psp_08917498]
      - [0x18CE4, asm, func_psp_089175F0]
      - [0x18D84, asm, func_psp_08917690]
      - [0x18E74, asm, func_psp_08917780]
      - [0x18ED0, asm, func_psp_089177DC]
      - [0x18F30, asm, func_psp_0891783C]
      - [0x18F9C, asm, func_psp_089178A8]
      - [0x18FD0, asm, func_psp_089178DC]
      - [0x1913C, asm, func_psp_08917A44]
      - [0x19234, asm, func_psp_08917B40]
      - [0x192C0, c, main_psp/192C0]
      - [0x1982C, asm, func_psp_08918138]
      - [0x19944, asm, func_psp_08918250]
      - [0x19B2C, asm, func_psp_08918438]
      - [0x19C64, asm, func_psp_08918570]
      - [0x19F10, asm, func_psp_0891881C]
      - [0x1A480, asm, func_psp_08918D8C]
      - [0x1A794, c, main_psp/1A794]
      - [0x1B0F0, c, main_psp/1B0F0]
      - [0x30F3C, asm, func_psp_0892F848]
      - [0x3104C, asm, func_psp_0892F958]
      - [0x31178, c, main_psp/31178]
      - [0x359F8, c, main_psp/vector4]
      - [0x36174, c, main_psp/36174]
      - [0x38EF0, asm, func_psp_089377FC]
      - [0x39464, asm, func_psp_08937D70]
      - [0x39A10, asm, func_psp_0893831C]
      - [0x39B40, asm, func_psp_0893844C]
      - [0x39C04, asm, func_psp_08938510]
      - [0x39C34, asm, __extendsfdf2]
      - [0x39C80, asm, func_psp_0893858C]
      - [0x39EE8, asm, func_psp_089387F4]
      - [0x39FFC, asm, func_psp_08938908]
      - [0x3A344, asm, __adddf3]
      - [0x3A3AC, asm, __subdf3]
      - [0x3A420, asm, __muldf3]
      - [0x3A798, asm, __divdf3]
      - [0x3A9BC, asm, func_psp_089392C8]
      - [0x3AB20, asm, __eqdf2]
      - [0x3ABA8, asm, __nedf2]
      - [0x3AC30, asm, __gtdf2]
      - [0x3ACB8, asm, __gedf2]
      - [0x3AD40, asm, func_psp_0893964C]
      - [0x3ADC8, asm, __floatsidf]
      - [0x3AEA4, asm, __fixdfsi]
      - [0x3AF78, asm, __negdf2]
      - [0x3AFBC, asm, func_psp_089398C8]
      - [0x3AFF0, asm, func_psp_089398FC]
      - [0x3B068, asm, _start] # crt0.c
      - [0x3B13C, asm, _main] # crt0.c
      - [0x3B3CC, asm, _stop] # crt0.c
      - [0x3B3FC, asm, sce_stub]
      - [0x3B9F4, textbin, sce_stub]
      - [0x3C524, rodata]
      - [0x3D528, .rodata, main_psp/192C0]
      - [0x3D534, .rodata, main_psp/1B0F0]
      - [0x3D580, rodata]
      - [0x3D6B4, .rodata, main_psp/31178]
      - [0x3D760, rodata]
      - [0x3D788, .rodata, main_psp/36174]
      - [0x3D8B8, rodata]
      - [0x3E680, .data, main_psp/portrait_data]
      - [0x47B00, data]
      - {start: 0xAEF24, type: bss, vram: 0x089AD830, name: main_bss}
  - [0xAEF24, bin, elf_footer]
  - [0xB3E1C]