options:
  platform: psp
  basename: w1_012
  base_path: ..
  build_path: build/pspeu/weapon1
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/w1_012.bin
  asm_path: asm/pspeu/weapon/w1_012_psp
  asset_path: assets/weapon1
  src_path: src/weapon
  ld_script_path: build/pspeu/w1_012.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.w1_012.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.pspeu.w1_012.txt
  undefined_syms_auto_path: config/undefined_syms_auto.pspeu.w1_012.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  disassemble_all: true
  global_vram_start: 0x8000000
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: eab66ff03cd2ff3c5c011e84f06b2b2943ca06d9
segments:
  - [0x0, bin, mwo_header]
  - name: w1_012
    type: code
    start: 0x80
    vram:  0x092F6C80
    bss_size: 0x80
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, w1_012]
      - [0x1900, data]
      # - [0x23D8, .rodata, w1_012]
      - {start: 0x2480, type: bss, vram: 0x92F9080}
  - [0x2480]
