options:
  platform:     psx
  basename:     dra
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/DRA.BIN
  asm_path:     asm/us/dra
  asset_path:   assets/dra
  src_path:     src/dra
  compiler:     GCC
  symbol_addrs_path:    config/generated.symbols.us.dra.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.dra.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.dra.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  asm_jtbl_label_macro: jlabel
  extensions_path: tools/splat_ext
  section_order:
    - ".data"
    - ".rodata"
    - ".text"
    - ".bss"
segments:
  - name: dra
    type: code
    start: 0x00000000
    vram:  0x800A0000
    subalign: 4
    subsegments:
      - [0x0, data]
      - [0x518, data]
      - [0x1F18, data]
      - [0x2BC0, data]
      - [0x3C40, data]
      - [0x4A00, data]
      - [0x4B04, equipment, equipments]
      - [0x7718, accessory, accessory_data]
      - [0x8258, data]
      - [0x8900, data]
      - [0xCEB0, data]
      - [0xD670, data]
      - [0x2217C, data]
      - [0x227B0, data]
      - [0x3B3B0, rodata]
      - [0x3B3B4, .rodata, 42398]
      - [0x3B530, .rodata, play]
      - [0x3B560, .rodata, gameover]
      - [0x3B720, .rodata, 46358]
      - [0x3B7E8, .rodata, 46FD4]
      - [0x3B9B8, rodata]
      - [0x3BD70, rodata] # jpt_800E7C28
      - [0x3BD88, rodata] # jpt_800E7E3C
      - [0x3BDE0, .rodata, 47BB8]
      - [0x3BEE0, rodata]
      - [0x3BEF8, rodata] # jpt_800E98E4
      - [0x3BF10, rodata] # jpt_800E9934
      - [0x3BF28, rodata] # jpt_800E9A48
      - [0x3BF3C, rodata]
      - [0x3C160, rodata]
      - [0x3C1A8, rodata] # jpt_800EA8C0
      - [0x3C1E8, rodata] # jpt_800EB120
      - [0x3C228, rodata]
      - [0x3C238, rodata] # jpt_800EE2FC
      - [0x3C290, .rodata, collider]
      - [0x3C490, .rodata, demo]
      - [0x3C514, rodata] # jpt_800F096C
      - [0x3C534, .rodata, 52860] # jpt_800F288C
      - [0x3C55C, rodata] # jpt_800F3684
      - [0x3C57C, rodata] # jpt_800F3758
      - [0x3C59C, rodata] # jpt_800F3C14
      - [0x3C5B4, rodata] # jpt_800F42A0
      - [0x3C5D4, rodata]
      - [0x3C68C, rodata] # jpt_800F8150
      - [0x3C6AC, rodata] # jpt_800F93A0
      - [0x3C6EC, rodata]
      - [0x3C71C, rodata] # jpt_800FA060
      - [0x3C734, rodata]
      - [0x3C75C, rodata] # jpt_800FBCC4
      - [0x3CB7C, rodata] # jpt_800FC36C
      - [0x3CB94, rodata] # jpt_800FC5B8
      - [0x3CBAC, .rodata, 5D6C4] # jpt_800FD6E0
      - [0x3CBC4, .rodata, 5D6C4]
      - [0x3CBF4, rodata]
      - [0x3CC0C, .rodata, 627C4]
      - [0x3CC2C, rodata] # jpt_80102918
      - [0x3CC54, .rodata, 62D70] # jpt_80102D9C
      - [0x3CC70, rodata]
      - [0x3CC80, rodata]
      - [0x3CD00, rodata]
      - [0x3CD10, rodata]
      - [0x3CDC0, rodata] # jpt_80103F08
      - [0x3CDDC, rodata]
      - [0x40D38, .rodata, cd] # To be merged with 40D38
      - [0x40E28, rodata]
      - [0x40E48, rodata] # EntityAlucard jump table
      - [0x4108C, rodata] # jpt_8010F424
      - [0x412AC, rodata] # jpt_8010F48C
      - [0x412C4, rodata] # jpt_8010F75C
      - [0x412DC, rodata] # jpt_8010F958
      - [0x412F4, rodata] # jpt_8010F9E8
      - [0x41308, rodata] # jpt_801109D0
      - [0x41320, rodata] # jpt_80110C1C
      - [0x41334, rodata]
      - [0x41348, rodata] # jpt_80110E54
      - [0x41360, rodata] # jpt_80111080
      - [0x41380, rodata] # jpt_8011131C
      - [0x413A0, rodata]
      - [0x413C0, .rodata, 71830]
      - [0x41400, rodata]
      - [0x41410, rodata] # jpt_80112264
      - [0x41588, rodata] # jpt_80112C9C
      - [0x41750, rodata] # jpt_80113328
      - [0x418C8, rodata] # jpt_80113938
      - [0x418E0, .rodata, 73AAC]
      - [0x418F4, rodata]
      - [0x41908, rodata] # jpt_801140A8
      - [0x41948, rodata] # jpt_801141F0
      - [0x41990, rodata] # jpt_80114300
      - [0x419B0, rodata] # jpt_80114388
      - [0x419D0, .rodata, 75DA0]
      - [0x419E8, rodata] # jpt_8011643C
      - [0x41A00, rodata] # jpt_801169F4
      - [0x41A20, rodata] # jpt_80116CF8
      - [0x41A38, rodata]
      - [0x41A44, rodata] # jpt_80118D54
      - [0x41A74, rodata]
      - [0x41A84, rodata] # jpt_801195F4
      - [0x41AA4, rodata]
      - [0x41AB4, rodata] # jpt_8011AD40
      - [0x41AD4, rodata] # jpt_8011AD94
      - [0x41AF4, rodata] # jpt_8011C214
      - [0x41B44, rodata] # jpt_8011C490
      - [0x41B74, rodata] # jpt_8011CB08
      - [0x41B94, rodata] # jpt_8011DC74
      - [0x41BF4, rodata] # jpt_8011DD70
      - [0x41C54, rodata] # jpt_8011DDCC
      - [0x41CB4, rodata] # jpt_8011E580
      - [0x41CE4, rodata] # jpt_8011E648
      - [0x41D1C, rodata] # jpt_8011E9D4
      - [0x41D4C, rodata] # jpt_8011EADC
      - [0x41D84, rodata] # jpt_80120C98
      - [0x41DA4, rodata] # jpt_80120FDC
      - [0x41DBC, rodata] # jpt_80122494
      - [0x41DD4, rodata] # jpt_80124410
      - [0x41E34, rodata] # jpt_80126808
      - [0x41E48, rodata]
      - [0x41E5C, rodata] # jpt_80126F54
      - [0x41E7C, rodata] # jpt_80128C94
      - [0x41E90, rodata] # jpt_8012A918
      - [0x41EB0, rodata] # jpt_8012D4D8
      - [0x41EC8, rodata] # jpt_8012EFE4
      - [0x41EF0, rodata] # jpt_8012FA74
      - [0x41F18, rodata] # jpt_8012FAC0
      - [0x41F30, rodata] # jpt_80130384
      - [0x41F58, rodata] # jpt_801303DC
      - [0x41F70, rodata] # jpt_80130728
      - [0x41F98, rodata] # jpt_80130788
      - [0x41FB0, rodata] # jpt_80130B00
      - [0x41FD8, rodata] # jpt_80131014
      - [0x42000, rodata] # jpt_801314B4
      - [0x4202C, rodata]
      - [0x42034, rodata] # jpt_80132F94
      - [0x4205C, rodata] # jpt_801332C4
      - [0x42074, rodata] # jpt_80133990
      - [0x4208C, rodata] # jpt_80133C10
      - [0x420B4, rodata] # jpt_80135058
      - [0x42354, .rodata, 953A0]
      - [0x42398, c, 42398]
      - [0x4493C, c, play]
      - [0x45358, c, gameover]
      - [0x46358, c, 46358]
      - [0x46FD4, c, 46FD4]
      - [0x47BB8, c, 47BB8]
      - [0x4F45C, c, collider]
      - [0x4FBF8, c, demo]
      - [0x5087C, c, 5087C]
      - [0x52860, c, 52860]
      - [0x5298C, c, 5298C]
      - [0x5D6C4, c, 5D6C4]
      - [0x627C4, c, 627C4]
      - [0x62D70, c, 62D70]
      - [0x673C0, c, cd]
      - [0x692E8, c, 692E8]
      - [0x71830, c, 71830]
      - [0x73AAC, c, 73AAC]
      - [0x75DA0, c, 75DA0]
      - [0x75F54, c, 75F54]
      - [0x953A0, c, 953A0]
      - [0x962AC, sbss]
  - name: dra_data
    type: data
    start: 0x9B6A0
    vram:  0x8013B6A0
  - [0x119870]
