options:
  platform:     psx
  basename:     ric
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/BIN/RIC.BIN
  asm_path:     asm/us/ric
  asset_path:   assets/ric
  src_path:     src/ric
  compiler:     GCC
  symbol_addrs_path:    config/generated.symbols.us.ric.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.ric.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.ric.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  asm_jtbl_label_macro: jlabel
  extensions_path: tools/splat_ext
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
segments:
  - name: ric
    type: code
    start: 0x00000000
    vram:  0x8013C000
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x20, spritesheet, richter, disks/us/BIN/F_GAME2.BIN, 0x40400]
      - [0x170AC, rodata]
      - [0x194B0, rodata]
      - [0x19B50, rodata]
      - [0x19BE0, rodata]
      - [0x19C70, rodata]
      - [0x19EE0, rodata]
      - [0x1A454, rodata]
      - [0x1A788, .rodata, 1F348]
      - [0x1A7A8, .rodata, 1FCD0]
      - [0x1A7C0, .rodata, 202A8]
      - [0x1A800, .rodata, 20920]
      - [0x1A80C, rodata]
      - [0x1A904, .rodata, 22380]
      - [0x1A908, rodata]
      - [0x1A9D0, .rodata, 26C84]
      - [0x1A9E8, rodata]
      - [0x1AB04, rodata]
      - [0x1AB68, .rodata, 32324]
      - [0x1AB88, rodata]
      - [0x1AC60, c, 1AC60]
      - [0x1F348, c, 1F348]
      - [0x1FCD0, c, 1FCD0]
      - [0x202A8, c, 202A8]
      - [0x20920, c, 20920]
      - [0x22380, c, 22380]
      - [0x26C84, c, 26C84]
      - [0x32324, c, 32324]
      - [0x37B60, data]
  - [0x39A58]
