options:
  platform:     psx
  basename:     stcen
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/ST/CEN/CEN.BIN
  asm_path:     asm/us/st/cen
  asset_path:   assets/st/cen
  src_path:     src/st/cen
  ld_script_path: build/us/stcen.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.stcen.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.stcen.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.stcen.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  asm_jtbl_label_macro: jlabel
  extensions_path: tools/splat_ext
  disassemble_all: True
  section_order:
    - ".data"
    - ".rodata"
    - ".text"
    - ".bss"
    - ".sbss"
sha1: 42226b6d9ed24448eed61b3c6cd2949e96bebab6
segments:
  - name: stcen
    type: code
    start: 0x00000000
    vram:  0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .data, header]
      - [0xDC, .data, header] # layers
      - [0x134, .data, header] # gfxbanks
      - [0x1EC, .data, e_laydef] # layout entries header
      - [0x394, .data, e_init]
      - [0x4D4, .data, st_debug]
      - [0x554, .data, e_breakable]
      - [0x5D8, .data, holyglassescutscene]
      - [0x68C, .data, F890]
      - [0x7B8, .data, st_update]
      - [0x7E4, .data, collision]
      - [0xBA4, .data, e_red_door]
      - [0xBBC, .data, st_common]
      - [0xDBC, .data, e_collect]
      - [0x10AC, .data, e_misc]
      - [0x1110, .data, e_misc]
      - [0x11C8, .data, e_particles]
      - [0x1248, .data, e_room_fg]
      - [0x12D4, .data, rooms]
      - [0x1300, .data, e_layout] # layout entries data
      - [0x13F0, .data, cutscene_data]
      - [0x1658, cmp, D_80181658]
      - [0x199C, cmp, D_8018199C]
      - [0x3A40, cmp, D_80183A40]
      - [0x4B70, cmp, D_80184B70]
      - [0x5830, cmp, D_80185830]
      - [0x658C, raw, D_8018658C]
      - [0x678C, raw, D_8018678C]
      - [0x698C, raw, D_8018698C]
      - [0x69AC, raw, D_801869AC]
      - [0x69EC, .data, tile_data] # tile data
      - [0x81EC, .data, tile_data] # tile definitions
      - [0xC60C, .data, sprites]
      - [0xD414, .rodata, e_init]
      - [0xD42C, .rodata, holyglassescutscene]
      - [0xD4B0, .rodata, F890]
      - [0xD4D8, .rodata, e_red_door] # EntityRedDoor
      - [0xD540, .rodata, e_collect] # EntityPrizeDrop
      - [0xD560, .rodata, e_collect] # EntityEquipItemDrop
      - [0xD578, .rodata, e_misc]
      - [0xD5B0, .rodata, e_misc]
      - [0xD5C4, .rodata, e_stage_name] # EntityStageNamePopup
      - [0xD5F8, .rodata, prim_helpers]
      - [0xD600, c, st_debug]
      - [0xD89C, c, e_breakable]
      - [0xDB18, c]
      - [0xDF0C, c, holyglassescutscene]
      - [0xF890, c]
      - [0x10E4C, c, st_update]
      - [0x11280, c, collision]
      - [0x12A3C, c, create_entity]
      - [0x135B4, c, e_red_door]
      - [0x14264, c, st_common]
      - [0x15714, c, e_collect]
      - [0x16C90, c, blit_char] 
      - [0x16F30, c, e_misc] 
      - [0x1A5F0, c, e_stage_name]
      - [0x1B274, c, e_particles]
      - [0x1BAB8, c, e_room_fg]
      - [0x1BBA4, c, popup]
      - [0x1BED4, c, prim_helpers]
      - [0x1C704, .bss, header]
      - [0x1C764, .bss, create_entity]
      - [0x1C774, .bss, holyglassescutscene]
      - [0x1C7C0, .bss, e_collect]
  - [0x1D46C]
