options:
  platform: psx
  basename: tt_003
  base_path: ..
  build_path: build/us
  target_path: disks/us/SERVANT/TT_003.BIN
  asm_path: asm/us/servant/tt_003
  asset_path: assets/servant/tt_003
  src_path: src/servant/tt_003
  ld_script_path: build/us/tt_003.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.tt_003.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.tt_003.txt
  undefined_syms_auto_path: config/undefined_syms_auto.us.tt_003.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: us_$VRAM
  disassemble_all: true
  section_order:
    - .data
    - .rodata
    - .text
    - .bss
    - .sbss
  ld_bss_is_noload: false
  disasm_unknown: true
sha1: b54466dec3923d43bd08d71bec688da252153984
segments:
  - name: tt_003
    type: code
    start: 0
    vram:  0x80170000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .data, demon]
      - [0x40, .data, demon_spriteparts]
      - [0x19F0, .data, demon_data]
      - [0x2090, .data, servant_events]
      - [0x29DC, .rodata, demon]
      - [0x2A68, c, demon]
      - [0x83C4, .bss, demon]
  - [0xA000]
