options:
  platform:     psx
  basename:     tt_000
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/SERVANT/TT_000.BIN
  asm_path:     asm/us/servant/tt_000
  asset_path:   assets/servant/tt_000
  src_path:     src/servant/tt_000
  ld_script_path: build/us/tt_000.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.tt_000.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.tt_000.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.tt_000.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  asm_jtbl_label_macro: jlabel
  disassemble_all: True
  section_order:
    - ".data"
    - ".rodata"
    - ".text"
    - ".bss"
  ld_bss_is_noload: False
sha1: 82dd4ae1c4e3dc0fd483a49e5e4ab4fc5e25ada7
segments:
  - name: tt_000
    type: code
    start: 0x00000000
    vram:  0x80170000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .data, 10E8]
      - [0x40, .data, spriteparts]
      - [0x448, .data, 448]
      - [0x4A8, .data, animationdata]
      - [0x608, .data, 608]
      - [0x10AC, .rodata, 10E8] # func_80172120
      - [0x10C4, .rodata, 10E8] # ProcessSfxState
      - [0x10E8, c]
      - [0x45E4, c]
      - [0x48D8, .bss, 10E8]
  - [0xA000]
