options:
  platform: psp
  basename: stno3
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/no3.bin
  asm_path: asm/pspeu/st/no3_psp
  asset_path: assets/st/no3
  src_path: src/st
  ld_script_path: build/pspeu/stno3.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.stno3.txt
  undefined_funcs_auto_path: build/pspeu/config/undefined_funcs_auto.pspeu.stno3.txt
  undefined_syms_auto_path: build/pspeu/config/undefined_syms_auto.pspeu.stno3.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  disassemble_all: true
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  disassemble_all: true
  global_vram_start: 0x8000000
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
  ld_generate_symbol_per_data_segment: true
sha1: 652e99e09bc71b9a56e2d389c952aa8fc6d0e31d
segments:
  - [0x0, bin, mwo_header]
  - name: stno3
    type: code
    start: 0x80
    vram:  0x09237700
    bss_size: 0x980
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, no3_psp/st_init_no3]
      - [0xD90, c, no3/e_castle_door]
      - [0x13C8, c, no3/e_heartroom]
      - [0x19A0, c, no3/entrance_weights]
      - [0x22C0, c, no3/e_cavern_door]
      - [0x2C60, c, no3/e_transparent_water]
      - [0x3050, c, no3/e_background_bushes_trees]
      - [0x3958, c, no3/e_stairway]
      - [0x41F8, c, no3/e_jewel_sword_puzzle]
      - [0x4EA8, c, no3/e_death_sky_swirl]
      - [0x5940, c, no3/e_sky_entities]
      - [0x5B18, c, no3/e_trapdoor]
      - [0x5CC8, c, no3/e_explosion_puff_opaque]
      - [0x6318, c, no3/e_outdoor_ents]
      - [0x9010, c, no3/e_death]
      - [0xAD58, c, no3/e_tilemap_shuffler]
      - [0xAE90, c, no3/e_shutting_window]
      - [0xB230, c, no3/e_breakable]
      - [0xB3B0, c, no3/e_room_bg]
      - [0xB4A8, c, no3/e_unkId16]
      - [0xB580, c, no3_psp/cutscene]
      - [0xE178, c, no3/e_lock_camera]
      - [0xE3D8, c, no3/create_entity]
      - [0xF380, c, no3/e_bat]
      - [0xF6B8, c, no3/e_stage_name]
      - [0x10538, c, no3/e_red_door]
      - [0x11840, c, no3/st_update]
      - [0x11D78, c, no3/e_fire_warg]
      - [0x16340, c, no3/e_merman2]
      - [0x18B40, c, no3/e_merman]
      - [0x1A068, c, no3/e_particles]
      - [0x1B5F8, c, no3/e_warg]
      - [0x1D6F0, c, no3/e_collect]
      - [0x212B0, c, no3/e_misc]
      - [0x21CC8, c, no3/collision]
      - [0x23EA0, c, no3/e_bone_scimitar]
      - [0x24AD8, c, no3/water_effects]
      - [0x27B48, c, no3/popup]
      - [0x28140, c, no3/e_room_fg]
      - [0x28258, c, no3/st_common]
      - [0x29A08, c, no3/prim_helpers]
      - [0x2A198, c, no3/e_zombie]
      - [0x2A680, data] #, no3/gen/sprites]
      - [0x33300, data] #, no3/sprite_banks]
      - [0x33360, data] #, no3/layers]
      - [0x33730, data] #, no3/palette_def]
      - [0x33870, data] #, no3/graphics_banks]
      - [0x33A58, .data, no3/e_init]
      - [0x33D40, .data, no3/e_red_door_tiles]
      - [0x33D60, .data, no3_psp/st_init_no3]
      - [0x33EA8, data] #, no3/gen/rooms]
      - [0x33FB0, .data, no3_psp/cutscene_data]
      - [0x347E0, data] #, no3/stage_data]
      - [0x481D0, data] #, no3/tilemaps]
      - [0x5E400, .data, no3/header]
      - [0x5E430, .data, no3/e_castle_door]
      - [0x5E530, .data, no3/e_cavern_door]
      - [0x5E540, .data, no3/e_transparent_water]
      - [0x5E580, .data, no3/e_background_bushes_trees]
      - [0x5E630, .data, no3/e_jewel_sword_puzzle]
      - [0x5E740, .data, no3/d_water_data]
      - [0x5E778, .data, no3/e_death_sky_swirl]
      - [0x5E7C0, .data, no3/e_sky_entities]
      - [0x5E7E0, .data, no3/e_trapdoor]
      - [0x5E7F0, .data, no3/e_explosion_puff_opaque]
      - [0x5E860, .data, no3/d_prize_drops]
      - [0x5E878, .data, no3/e_outdoor_ents]
      - [0x5EEF8, .data, no3/e_death]
      - [0x5F020, .data, no3/e_shutting_window]
      - [0x5F070, .data, no3/e_breakable]
      - [0x5F0C0, .data, no3/background_block_init]
      - [0x5F2F0, .data, no3_psp/cutscene]
      - [0x5F6B8, .data, no3/e_lock_camera]
      - [0x5F730, .data, no3/e_bat]
      - [0x5F770, .data, no3/e_red_door]
      - [0x5F788, .data, no3/st_update]
      - [0x5F7B8, .data, no3/e_fire_warg]
      - [0x60050, .data, no3/e_merman2]
      - [0x602B8, .data, no3/e_particles]
      - [0x60338, .data, no3/e_warg]
      - [0x60998, .data, no3/e_collect]
      - [0x60EE0, .data, no3/e_misc]
      - [0x60F40, .data, no3/collision]
      - [0x61318, .data, no3/e_bone_scimitar]
      - [0x61420, .data, no3/water_effects]
      - [0x614D0, .data, no3/e_room_fg]
      - [0x61570, .data, no3/e_zombie]
      - [0x61600, .rodata, no3/e_castle_door]
      - [0x61618, .rodata, no3/e_outdoor_ents] # EntityPushAlucard
      - [0x61630, .rodata, no3/e_death]
      - [0x616B8, .rodata, no3_psp/cutscene]
      - [0x61770, .rodata, no3/e_fire_warg]
      - [0x617C0, .rodata, no3/e_merman2]
      - [0x61810, .rodata, no3/e_warg]
      - [0x61848, .rodata, no3/e_collect]
      - [0x618A8, .rodata, no3/popup]
      - [0x61900, bss] #, no3/gen/sprites] # sprites_no3_7_51 is zero, bss on psp
      #- [0x61908, .bss, no3/layers] # layer_empty
      - [0x61918, .bss, no3_psp/st_init_no3]
      - [0x61BB0, .bss, no3/e_background_bushes_trees]
      - [0x61BC0, .bss, no3/e_trapdoor]
      - [0x61BC8, .bss, no3/e_shutting_window]
      - [0x61BD8, .bss, no3/e_breakable]
      - [0x61BE0, .bss, no3_psp/cutscene]
      - [0x621F0, .bss, no3/e_lock_camera]
      - [0x621F8, .bss, no3/create_entity]
      - [0x62218, .bss, no3/e_collect] # BlitChar
      - [0x62278, .bss, no3/e_bone_scimitar] # spawn_special
  - [0x62280]
