options:
  platform:     psx
  basename:     stno3
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/ST/NO3/NO3.BIN
  asm_path:     asm/us/st/no3
  asset_path:   assets/st/no3
  src_path:     src/st/no3
  compiler:     GCC
  symbol_addrs_path:    config/generated.symbols.us.stno3.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.stno3.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.stno3.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  extensions_path: tools/splat_ext
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
segments:
  - name: stno3
    type: code
    start: 0x00000000
    vram:  0x80180000
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x920, rodata]
      - [0xAAC, rodata]
      - [0xDC0, rodata]
      - [0xDD0, rodata]
      - [0xE50, rodata]
      - [0xE70, rodata]
      - [0xE80, rodata]
      - [0xE90, rodata]
      - [0xEA0, rodata]
      - [0x11F0, rodata]
      - [0x1B40, rodata]
      - [0x26D0, rodata]
      - [0x3180, rodata]
      - [0x39A0, rodata]
      - [0x3AC0, rodata]
      - [0x3AF0, rodata]
      - [0x3B30, rodata]
      - [0x3CC4, roomdef, g_Rooms]
      - [0x3DC8, rodata]
      - [0x4CE0, rodata]
      - [0x373E0, rodata]
      - [0x373E8, rodata]
      - [0x37414, .rodata, 3C4EC]
      - [0x3742C, .rodata, 3E134]
      - [0x37440, rodata]
      - [0x37458, rodata]
      - [0x37628, rodata]
      - [0x376E8, rodata]
      - [0x377A4, .rodata, 56264]
      - [0x377B8, rodata]
      - [0x377D4, c]
      - [0x3C4EC, c, 3C4EC]
      - [0x3E134, c, 3E134]
      - [0x56264, c]
      - [0x570B0, data]
  - [0x57E18]
