options:
  platform: psp
  basename: stno2
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/no2.bin
  asm_path: asm/pspeu/st/no2_psp
  asset_path: assets/st/no2
  src_path: src/st
  ld_script_path: build/pspeu/stno2.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.stno2.txt
  undefined_funcs_auto_path: build/pspeu/config/undefined_funcs_auto.pspeu.stno2.txt
  undefined_syms_auto_path: build/pspeu/config/undefined_syms_auto.pspeu.stno2.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  disassemble_all: true
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  global_vram_start: 0x08000000
  ld_generate_symbol_per_data_segment: true
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: d686a707122484c54e8b9c7602b96c1a55a0fbe1
segments:
  - [0x0, bin, mwo_header]
  - name: stno2
    type: code
    start: 0x80
    vram: 0x09237700
    bss_start_address: 0x0928D480
    bss_size: 0x280
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, no2/create_entity]
      - [0x1028, c, no2/e_bloody_zombie]
      - [0x24A8, c, no2/e_skelerang]
      - [0x33C8, c, no2/e_stage_name]
      - [0x42C8, c, no2/e_red_door]
      - [0x55D0, c, no2/st_update]
      - [0x5B08, c, no2/e_valhalla_knight]
      - [0x6A68, c, no2/e_particles]
      - [0x7FF8, c, no2/e_collect]
      - [0xC248, c, no2/e_misc]
      - [0xCF68, c, no2/collision]
      - [0xF140, c, no2/popup]
      - [0xF738, c, no2/e_room_fg]
      - [0xF850, c, no2/e_owl_knight]
      - [0x13438, c, no2/e_spectral_sword]
      - [0x15048, c, no2/st_common]
      - [0x16928, c, no2/prim_helpers]
      - [0x17448, c, no2/giantbro_helpers]
      - [0x17EB0, c, no2/blade]
      - [0x19CF0, c, no2/gurkha]
      - [0x1B730, c, no2/hammer]
      - [0x1D0C8, c, no2/4966C]
      - [0x1D6F8, c, no2/e_secrets]
      - [0x1F3B8, c, no2_psp/st_init_no2]
      - [0x1F688, c, no2/e_breakable]
      - [0x1FF58, c, no2/33D8C]
      - [0x20770, c, no2/e_sealed_door]
      - [0x21C20, c, no2/e_background_house]
      - [0x22BC8, c, no2/34DA4]
      - [0x23228, c, no2/e_room_bg]
      - [0x23308, c, no2/36E34]
      - [0x23998, c, no2/e_lock_camera]
      - [0x23BF8, c, no2/37580]
      - [0x240B0, c, no2/372E8]
      - [0x24450, c, no2/e_spikes]
      - [0x24E00, .data, no2/e_bloody_zombie]
      - [0x24F00, .data, no2/e_skelerang]
      - [0x24FF0, .data, no2/e_stage_name]
      - [0x25B98, .data, no2/e_red_door]
      - [0x25BB0, .data, no2/st_update]
      - [0x25BE0, .data, no2/e_valhalla_knight]
      - [0x25D78, .data, no2/e_particles]
      - [0x25DF8, .data, no2/e_collect]
      - [0x26340, .data, no2/e_misc]
      - [0x26390, .data, no2/collision]
      - [0x26768, .data, no2/e_room_fg]
      - [0x26808, .data, no2/e_owl_knight]
      - [0x26AF8, .data, no2/e_spectral_sword]
      - [0x26B90, .data, no2/st_common]
      - [0x26D90, .data, no2/giantbro_helpers]
      - [0x26DD0, .data, no2/blade]
      - [0x27498, .data, no2/gurkha]
      - [0x27960, .data, no2/hammer]
      - [0x27EC0, .data, no2/e_secrets]
      - [0x27FD8, data]
      - [0x2E9A0, .data, no2/layers]
      - [0x2EC68, data]
      - [0x2EE90, .data, no2/e_init]
      - [0x2F188, .data, no2/e_red_door_tiles]
      - [0x2F1C8, .data, no2/gen/rooms]
      - [0x2F298, .data, no2/e_breakable]
      - [0x2F3E0, data]
      - [0x3DCE8, .data, no2/tilemaps]
      - [0x55718, .data, no2/header]
      - [0x55748, .data, no2/33D8C]
      - [0x55790, .data, no2/e_sealed_door]
      - [0x55800, .data, no2/e_background_house]
      - [0x55990, .data, no2/d_prize_drops]
      - [0x559A8, .data, no2/34DA4]
      - [0x559B0, .data, no2/background_block_init]
      - [0x559D0, .data, no2/36E34]
      - [0x55A48, .data, no2/e_lock_camera]
      - [0x55AC0, .data, no2/37580]
      - [0x55B30, .data, no2/372E8]
      - [0x55BB0, .data, no2/e_spikes]
      - [0x55C00, .rodata, no2/e_bloody_zombie]
      - [0x55C28, .rodata, no2/e_skelerang]
      - [0x55C70, .rodata, no2/e_red_door]
      - [0x55C88, .rodata, no2/e_valhalla_knight]
      - [0x55CA0, .rodata, no2/e_collect]
      - [0x55D00, .rodata, no2/e_owl_knight]
      - [0x55D60, .rodata, no2/blade]
      - [0x55D78, .rodata, no2/gurkha]
      - [0x55DB8, .rodata, no2/e_sealed_door]
      - {start: 0x55E00, type: .bss, vram: 0x0928D480, name: no2/create_entity}
      - {start: 0x55E00, type: .bss, vram: 0x0928D4A0, name: no2/e_collect}
      - {start: 0x55E00, type: bss, vram: 0x0928D500, name: bss1}
      - {start: 0x55E00, type: .bss, vram: 0x0928D508, name: no2/layers}
      - {start: 0x55E00, type: .bss, vram: 0x0928D518, name: no2_psp/st_init_no2}
      - {start: 0x55E00, type: .bss, vram: 0x0928D6A0, name: no2/e_lock_camera}
      - {start: 0x55E00, type: bss, vram: 0x0928D6A8, name: bss2}
  - [0x56080]
