options:
  platform:     psx
  basename:     stchi
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/ST/CHI/CHI.BIN
  asm_path:     asm/us/st/chi
  asset_path:   assets/st/chi
  src_path:     src/st/chi
  ld_script_path: build/us/stchi.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.stchi.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.stchi.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.stchi.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  asm_jtbl_label_macro: jlabel
  extensions_path: tools/splat_ext
  disassemble_all: True
  section_order:
    - ".data"
    - ".rodata"
    - ".text"
    - ".bss"
    - ".sbss"
sha1: 4ea14c8B54B8526ee6840b8b54658cafc0B336a2
segments:
  - name: stchi
    type: code
    start: 0x00000000
    vram:  0x80180000
    align: 4
    subalign: 4
    subsegments:
      # Code data
      - [0x0, .data, dt_header]   # Header
      - [0xE8, .data, dt_header]  # Layers
      - [0x298, .data, dt_header] # Gfx banks
      - [0x3B4, .data, e_laydef]  # layout entities header
      - [0x55C, .data, dt_entity]
      - [0x798, .data, st_debug]
      - [0x818, .data, en_breakable]
      - [0x89C, .data, en_demon_switch_wall]
      - [0x8CC, .data, en_breakable_wall]
      - [0x974, .data, en_falling_stairs]
      - [0x9E4, .data, dt_prize_drops]
      - [0xA20, .data, st_update]
      - [0xA4C, .data, st_collision]
      - [0xE0C, .data, en_red_door]
      - [0xE24, .data, ut_common]
      - [0x1024, .data, en_collect]
      - [0x1314, .data, en_misc]
      - [0x1378, .data, en_misc]          # EntityUnkId14Spawner
      - [0x1388, .data, en_misc]          # EntityUnkId15, EntityUnkId14
      - [0x13D4, .data, en_misc]          # EntityOlroxDrool
      - [0x13DC, .data, en_misc]          # func_801A6054
      - [0x13EC, .data, en_misc]          # UnkRecursivePrimFunc1
      - [0x140C, .data, en_misc]          # UnkRecursivePrimFunc2
      - [0x142C, .data, en_particles]     # EntitySoulStealOrb
      - [0x14AC, .data, en_room_foreground]
      - [0x1538, .data, en_salem_witch]   # EntitySalemWitch
      - [0x162C, .data, en_salem_witch]   # EntitySalemWitchGlow
      - [0x1638, .data, en_salem_witch]   # EntitySalemWitchCurse
      - [0x167C, .data, en_salem_witch]   # EntitySalemWitchTriboltLaunch
      - [0x16C0, .data, en_salem_witch]   # EntitySalemWitchTriboltProjectile
      - [0x16EC, .data, en_gremlin]       # EntityGremlin
      - [0x1704, .data, en_gremlin]       # EntityGremlinEffect
      - [0x1724, .data, en_gremlin]       # EntityGremlinFire
      - [0x173C, .data, en_thornweed_corpseweed]
      - [0x17F4, .data, en_venus_weed]
      # Binary data
      - [0x195C, .data, rooms]
      - [0x19F8, .data, e_layout] # layout entities data
      - [0x20D8, cmpgfx, bn_gfx_stage_name_jp_sm, 128, 128, 4]
      - [0x2508, cmpgfx, bn_gfx_stage_name_jp_lg, 128, 128, 4]
      - [0x2A60, cmpgfx, bn_gfx_gremlin, 128, 128, 4, 0xA300]
      - [0x3480, cmpgfx, bn_gfx_salem_witch_1, 128, 128, 4, 0xA380]
      - [0x41F8, cmpgfx, bn_gfx_salem_witch_2, 128, 128, 4, 0xA380]
      - [0x4DBC, cmpgfx, bn_gfx_salem_witch_3, 128, 128, 4, 0xA380]
      - [0x5BA0, cmpgfx, bn_gfx_salem_witch_4, 128, 128, 4, 0xA380]
      - [0x6B1C, cmpgfx, bn_gfx_salem_witch_5, 128, 128, 4, 0xA380]
      - [0x70F8, cmpgfx, bn_gfx_thornweed_corpseweed, 128, 128, 4, 0xA3C0]
      - [0x7E84, cmpgfx, bn_gfx_venus_weed_1, 128, 128, 4, 0xA440]
      - [0x8A10, cmpgfx, bn_gfx_venus_weed_2, 128, 128, 4, 0xA440]
      - [0x9B38, cmpgfx, bn_gfx_stage_name_en, 128, 128, 4]
      - [0x9FE0, pal, bn_pal_unused_0]  # Unused
      - [0xA040, pal, bn_pal_salem_witch_projectiles]
      - [0xA240, pal, bn_pal_unused_1]  # Unused
      - [0xA300, pal, bn_pal_gremlin]
      - [0xA380, pal, bn_pal_salem_witch]
      - [0xA3C0, pal, bn_pal_thornweed_corpseweed]
      - [0xA440, pal, bn_pal_venus_weed]
      - [0xA960, .data, tile_data] # tile data
      - [0xF760, .data, tile_data] # tile definitions
      - [0x17B90, .data, sprites]
      - [0x1B100, .rodata, en_demon_switch_wall]      # jtbl_8019B100 [EntityDemonSwitchWall]
      - [0x1B144, .rodata, en_breakable_wall]         # jtbl_8018B144 [EntityBreakableWall]
      - [0x1B168, .rodata, en_debug_cerberus_gate]    # jtbl_8019B168 [EntityCerberusGateDebug]
      - [0x1B180, .rodata, en_falling_stairs]         # jtbl_8019B180 [EntityFallingStairs]
      - [0x1B194, .rodata, en_red_door]               # jtbl_8019B194 [EntityRedDoor]
      - [0x1B1AC, .rodata, en_collect]                # CollectGold strings
      - [0x1B1FC, .rodata, en_collect]                # jtbl_8019B1FC [EntityPrizeDrop]
      - [0x1B21C, .rodata, en_collect]                # jtbl_8019B21C [EntityEquipItemDrop]
      - [0x1B234, .rodata, en_misc]                   # EntityRelicOrb string
      - [0x1B244, .rodata, en_misc]                   # jtbl_8019B244 [EntityRelicOrb]
      - [0x1B26C, .rodata, en_misc]                   # jtbl_8019B26C [EntityMessageBox]
      - [0x1B280, .rodata, en_salem_witch]            # EntitySalemWitch debug string
      - [0x1B290, .rodata, en_salem_witch]            # jtbl_8019B290 [EntitySalemWitch]
      - [0x1B2A8, .rodata, en_salem_witch]            # jtbl_8019B2A8 [EntitySalemWitchTribolt]
      - [0x1B2BC, .rodata, en_gremlin]                # EntityGremlin debug string
      - [0x1B2C8, .rodata, en_thornweed_corpseweed]   # jtbl_8019B2C8 [EntityThornweed]
      - [0x1B2E8, .rodata, en_thornweed_corpseweed]   # jtbl_8019B2E8 [EntityCorpseweed]
      - [0x1B304, .rodata, en_venus_weed]             # jtbl_8019B304 [EntityVenusWeed]
      - [0x1B32C, .rodata, en_venus_weed]             # jtbl_8019B32C [EntityVenusWeed]
      - [0x1B344, .rodata, en_venus_weed]             # jtbl_8019B344 [EntityVenusWeedFlower]
      - [0x1B36C, .rodata, en_venus_weed]             # jtbl_8019B36C [EntityVenusWeedFlower]
      - [0x1B384, .rodata, en_venus_weed]             # jtbl_8019B384 [EntityVenusWeedFlower]
      - [0x1B39C, .rodata, en_venus_weed]             # jtbl_8019B39C [EntityVenusWeedTendril]
      - [0x1B3C0, .rodata, en_stage_name]             # EntityStageNamePopup strings
      - [0x1B3E0, .rodata, en_stage_name]             # jtbl_8019B3E0 [EntityStageNamePopup]
      - [0x1B3F4, .rodata, ut_prim_helpers]           # UnkPrimHelper SVECTOR
      - [0x1B3FC, c, st_debug]
      - [0x1B698, c, en_breakable]
      - [0x1BD0C, c, en_demon_switch_wall]
      - [0x1C31C, c, en_breakable_wall]
      - [0x1CBA8, c, en_debug_cerberus_gate]
      - [0x1D0D8, c, en_falling_stairs]
      - [0x1DE74, c, st_update]
      - [0x1E2A8, c, st_collision]
      - [0x1FA64, c, ut_create_entity]
      - [0x205DC, c, en_red_door]
      - [0x2128C, c, ut_common]
      - [0x2273C, c, en_collect]
      - [0x23CA8, c, ut_blit_char]
      - [0x23F58, c, en_misc]
      - [0x27448, c, en_particles]
      - [0x27C8C, c, en_room_foreground]
      - [0x27D78, c, en_bottom_corner_text]
      - [0x2813C, c, en_salem_witch]
      - [0x297C8, c, en_gremlin]
      - [0x2A020, c, en_thornweed_corpseweed]
      - [0x2B548, c, en_venus_weed]
      - [0x2D0EC, c, en_stage_name]
      - [0x2DF40, c, ut_prim_helpers]
      - [0x2E770, .bss, ut_create_entity]
      - [0x2E780, bss]
      - [0x2F3E8, .bss, en_collect]
  - [0x2F428]