options:
  platform: psp
  basename: stlib
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/lib.bin
  asm_path: asm/pspeu/st/lib_psp
  asset_path: assets/st/lib
  src_path: src/st
  ld_script_path: build/pspeu/stlib.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.stlib.txt
  undefined_funcs_auto_path: build/pspeu/config/undefined_funcs_auto.pspeu.stlib.txt
  undefined_syms_auto_path: build/pspeu/config/undefined_syms_auto.pspeu.stlib.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: psp_$VRAM
  disassemble_all: true
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  global_vram_start: 0x08000000
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
  ld_generate_symbol_per_data_segment: true
sha1: f45dd42ccb88a374491c7c38c19cc80c1cd936ad
segments:
  - [0x0, bin, mwo_header]
  - name: stlib
    type: code
    start: 0x00000080
    vram: 0x09237700
    bss_size: 0xE00
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, lib/create_entity]
      - [0x1028, c, lib/e_bloody_zombie]
      - [0x1848, c, lib/e_spellbook_magic_tome]
      - [0x3DC0, c, lib/e_life_up]
      - [0x4A40, c, lib/e_stage_name]
      - [0x5940, c, lib/e_dhuron]
      - [0x6E18, c, lib/e_red_door]
      - [0x8120, c, lib/st_update]
      - [0x8658, c, lib/e_flying_zombie]
      - [0x9A28, c, lib/e_ectoplasm]
      - [0xAC78, c, lib/e_particles]
      - [0xC208, c, lib/e_collect]
      - [0x10458, c, lib/e_misc]
      - [0x11A88, c, lib/collision]
      - [0x13C60, c, lib/e_mist_door]
      - [0x13EE8, c, lib/e_mudman]
      - [0x15190, c, lib/popup]
      - [0x15788, c, lib/e_flea_man]
      - [0x15E00, c, lib/e_room_fg]
      - [0x15F18, c, lib/e_flea_armor]
      - [0x169E8, c, lib/e_skeleton]
      - [0x174C8, c, lib/st_common]
      - [0x18EE0, c, lib/prim_helpers]
      - [0x19AE8, c, lib/en_thornweed_corpseweed]
      - [0x1B7F0, c, lib/e_library_bg]
      - [0x1C6D8, c, lib_psp/st_init_lib]
      - [0x1CC08, c, lib/unk_3B53C]
      - [0x1D050, c, lib/e_breakable]
      - [0x1D650, c, lib/e_chair]
      - [0x1D9E8, c, lib_psp/unk_1D9E8]
      - [0x1E6F8, c, lib/e_lesser_demon]
      - [0x231B0, c, lib_psp/cutscene]
      - [0x25CD0, c, lib/e_room_bg]
      - [0x25DB0, c, lib_psp/e_shop]
      - [0x35798, c, lib/e_lock_camera]
      - [0x35F60, c, lib/unk_3B200]
      - [0x36428, c, lib/e_candle_table]
      - [0x367C0, data]
      - [0x36800, .data, lib/e_bloody_zombie]
      - [0x36840, .data, lib/e_spellbook_magic_tome]
      - [0x36AA0, .data, lib/e_life_up]
      - [0x36AF0, .data, lib/e_stage_name]
      - [0x37788, .data, lib/e_dhuron]
      - [0x37918, .data, lib/e_red_door]
      - [0x37930, .data, lib/st_update]
      - [0x37960, .data, lib/e_flying_zombie]
      - [0x37A40, .data, lib/e_ectoplasm]
      - [0x37AF0, .data, lib/e_particles]
      - [0x37B70, .data, lib/e_collect]
      - [0x380B8, .data, lib/e_misc]
      - [0x38138, .data, lib/collision]
      - [0x38510, .data, lib/e_mist_door]
      - [0x38698, .data, lib/e_mudman]
      - [0x38728, .data, lib/e_flea_man]
      - [0x38790, .data, lib/e_room_fg]
      - [0x38830, data]
      - [0x388A0, .data, lib/e_skeleton]
      - [0x389A8, .data, lib/st_common]
      - [0x38BA8, .data, lib/en_thornweed_corpseweed]
      - [0x38C78, .data, lib/e_library_bg]
      - [0x38D38, data]
      - [0x3E888, .data, lib/e_red_door_tiles]
      - [0x3E898, .data, lib/e_init]
      - [0x3EC28, data] # g_gen_rooms.c
      - [0x3ECB0, .data, lib_psp/cutscene_data]
      - [0x3F608, .data, lib/e_breakable]
      - [0x3F710, data]
      - [0x60AB8, .data, lib/e_chair]
      - [0x60AE8, data]
      - [0x60C70, .data, lib/e_lesser_demon]
      - [0x60E50, .data, lib_psp/cutscene]
      - [0x61218, .data, lib/background_block_init]
      - [0x61308, .data, lib_psp/e_shop]
      - [0x6D6D0, .data, lib/e_lock_camera]
      - [0x6D748, data]
      - [0x6D768, .data, lib/e_candle_table]
      - [0x6D800, .rodata, lib/e_spellbook_magic_tome]
      - [0x6D858, .rodata, lib/e_life_up]
      - [0x6D878, .rodata, lib/e_dhuron]
      - [0x6D8A0, .rodata, lib/e_red_door]
      - [0x6D8B8, .rodata, lib/e_flying_zombie]
      - [0x6D8E0, .rodata, lib/e_collect]
      - [0x6D940, .rodata, lib/e_mist_door]
      - [0x6D940, .rodata, lib/e_mudman]
      - [0x6D988, .rodata, lib/en_thornweed_corpseweed]
      - [0x6D9C8, .rodata, lib/unk_3B53C]
      - [0x6D9E8, .rodata, lib/e_lesser_demon]
      - [0x6DA20, .rodata, lib_psp/cutscene]
      - [0x6DAD8, .rodata, lib_psp/e_shop]
      - [0x6DD20, .rodata, lib/unk_3B200]
      - [0x6DD80, .bss, lib/create_entity]
      - [0x6DDA0, .bss, lib/e_life_up]
      - [0x6DDA8, .bss, lib/e_collect]
      - [0x6DE08, .bss, lib/e_mist_door]
      - [0x6DE20, .bss, lib/e_library_bg]
      - [0x6DE40, bss, 6DE40]
      - [0x6DE50, .bss, lib/e_init]
      - [0x6DE60, .bss, lib_psp/st_init_lib]
      - [0x6E078, bss, 6E078]
      - [0x6E090, .bss, lib/e_breakable]
      - [0x6E0A8, .bss, lib_psp/cutscene]
      - [0x6E6B0, .bss, lib_psp/e_shop]
      - [0x6EB50, .bss, lib/e_lock_camera]
  - [0x6EC00]
