options:
  platform: psp
  basename: stst0
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/st0.bin
  asm_path: asm/pspeu/st/st0_psp
  asset_path: assets/st/st0
  src_path: src/st
  ld_script_path: build/pspeu/stst0.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.stst0.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.pspeu.stst0.txt
  undefined_syms_auto_path: config/undefined_syms_auto.pspeu.stst0.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  nonmatchings_path: psp
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  include_macro_inc: false
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: f40689641eda2ab9de69b6aed15a200717827628
segments:
  - [0x0, bin, mwo_header]
  - name: stst0
    type: code
    start: 0x80
    vram:  0x09237700
    bss_size: 0x3C00
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, st0_psp/80]
      - [0x1E8, c, st0_psp/30030]
      - [0x1578, c, st0_psp/cutscene]
      - [0x3F58, c, st0_psp/2A8DC]
      - [0x4A30, c, st0_psp/2B0C8]
      - [0x58B8, c, st0_psp/2C564]
      - [0x8230, c, st0_psp/2DAC8]
      - [0xB3A0, c, st0_psp/3101C]
      - [0xC3E0, c, st0_psp/3AB08]
      - [0xE658, c, st0_psp/3C5C0]
      - [0xF320, c, st0_psp/st_init_st0]
      - [0xF560, c, st0_psp/2850C]
      - [0xFD18, c, st0_psp/st_debug]
      - [0xFDF8, c, st0_psp/2A218]
      - [0x10678, c, st0_psp/e_lock_camera]
      - [0x10A00, c, st0_psp/create_entity]
      - [0x119A8, c, st0_psp/e_red_door]
      - [0x12CB0, c, st0_psp/st_update]
      - [0x131E8, c, st0_psp/e_particles_maria1]
      - [0x13770, c, st0_psp/e_particles_maria2]
      - [0x13C00, c, st0_psp/e_particles]
      - [0x14160, c, st0_psp/e_collect]
      - [0x15CC8, c, st0_psp/e_misc]
      - [0x16278, c, st0_psp/collision]
      - [0x18000, c, st0_psp/popup]
      - [0x185F8, c, st0_psp/e_room_fg]
      - [0x18710, c, st0_psp/st_common]
      - [0x194C0, c, st0_psp/3D8F0]
      - [0x19D90, c, st0_psp/prim_helpers]
      - [0x1A4D0, c, st0_psp/e_bg_vortex]
      - [0x1B200, data]
      - [0x42400, .rodata, st0_psp/30030]
      - [0x42450, .rodata, st0_psp/cutscene]
      - [0x424F8, .rodata, st0_psp/2B0C8]
      - [0x42530, .rodata, st0_psp/2C564]
      - [0x42580, .rodata, st0_psp/2DAC8]
      - [0x425D8, .rodata, st0_psp/3AB08]
      - [0x42610, .rodata, st0_psp/2A218]
      - [0x42650, .rodata, st0_psp/e_red_door]
      - [0x42668, .rodata, st0_psp/e_collect]
      - [0x426A0, .rodata, st0_psp/3D8F0]
      - {type: bss, vram: 0x9279D80}
  - [0x42700]
