options:
  platform: psx
  basename: bobo4
  base_path: ..
  build_path: build/us
  target_path: disks/us/BOSS/BO4/BO4.BIN
  asm_path: asm/us/boss/bo4
  asset_path: assets/boss/bo4
  src_path: src/boss/bo4
  ld_script_path: build/us/bobo4.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.bobo4.txt
  undefined_funcs_auto_path: build/us/config/undefined_funcs_auto.us.bobo4.txt
  undefined_syms_auto_path: build/us/config/undefined_syms_auto.us.bobo4.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  extensions_path: tools/splat_ext
  symbol_name_format: us_$VRAM
  section_order:
    - .data
    - .rodata
    - .text
    - .bss
    - .sbss
  ld_bss_is_noload: false
  disasm_unknown: true
  disassemble_all: true
  global_vram_start: 0x80010000
  ld_generate_symbol_per_data_segment: true
sha1: b90a2a70ae9651ed107b306d4dcfba2311b523fc
segments:
  - name: bobo4
    type: code
    start: 0
    vram:  0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .data, header]
      #- [0x34, data, header] # sprite_banks
      #- [0x94, data, header] # pallet_def
      #- [0xF0, data, header] # layers
      #  [0x118, data, header] # graphics banks
      - [0x188, .data, gen/e_laydef]
      - [0x330, .data, e_init]
      - [0x464, .data, background_block_init]
      - [0x49C, .data, e_red_door_tiles]
      - [0x4BC, .data, e_lock_camera]
      - [0x53C, .data, e_breakable]
      - [0x5A0, .data, doors]
      - [0x668, .data, unk_365FC]
      - [0x690, .data, d_prize_drops]
      - [0x690, .data, st_update]
      - [0x6DC, .data, collision]
      - [0xA9C, .data, e_red_door]
      - [0xAB4, .data, st_common]
      - [0xCB4, .data, e_collect]
      - [0xFA4, .data, e_misc]
      - [0x10C0, .data, e_particles]
      - [0x1140, .data, e_room_fg]
      - [0x11CC, .data, gen/rooms]
      - [0x11E8, .data, doppleganger]
      - [0x12E4, .data, dop_anim]
      - [0x1318, .data, unk_45354]
      - [0x133C, .data, unk_46E7C]
      - [0x14B0, .data, unk_46E7C] # factory blueprint
      - [0x2028, .data, doppleganger_anim] # animation
      - [0x4098, data, doppleganger_anim]
      - [0x4290, .data, e_life_up]
      - [0x42E4, .data, gen/e_layout]
      - [0x435C, .data, spritesheets] # doppleganger_sprites, bat_form_sprites
      - [0x2BEA0, .data, stage_data]
      - [0x30A78, data] # small animationframe sets, unimportable
      - [0x340E4, .rodata, doors]
      - [0x34188, .rodata, unk_365FC]
      - [0x341A8, .rodata, e_red_door]
      - [0x341C0, .rodata, e_collect]
      - [0x34248, .rodata, e_misc]
      - [0x34294, .rodata, e_stage_name]
      - [0x342C8, .rodata, doppleganger]
      - [0x344AC, .rodata, unk_45354]
      - [0x344D8, .rodata, unk_46E7C]
      - [0x34814, .rodata, prim_helpers]
      - [0x3481C, .rodata, e_life_up]
      - [0x34838, c, e_room_bg]
      - [0x34900, c, e_lock_camera]
      - [0x34ABC, c, e_breakable]
      - [0x34BF0, c, doors]
      - [0x365FC, c, unk_365FC]
      - [0x369BC, c, st_update]
      - [0x36DF0, c, collision]
      - [0x385AC, c, create_entity]
      - [0x39124, c, e_red_door]
      - [0x39DD4, c, st_common]
      - [0x3B284, c, e_collect]
      - [0x3CAA0, c, e_misc]
      - [0x3FF84, c, e_stage_name]
      - [0x40DD8, c, e_particles]
      - [0x4161C, c, e_room_fg]
      - [0x41708, c, popup]
      - [0x41A38, c, doppleganger]
      - [0x44958, c, dop_anim]
      - [0x45354, c, unk_45354]
      - [0x46E7C, c, unk_46E7C]
      - [0x52020, c, prim_helpers]
      - [0x52850, c, e_life_up]
      - [0x53104, .bss, doors]
      - [0x53110, .bss, create_entity]
      - [0x53120, bss] # unused
      - [0x53D24, .bss, doppleganger]
      - [0x53D30, .bss, unk_46E7C]
      - [0x54118, .bss, bss]
      - [0x54DF8, .bss, st_update]
  - [0x54E38]
