options:
  platform:     psx
  basename:     stsel
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/ST/SEL/SEL.BIN
  asm_path:     asm/us/st/sel
  asset_path:   assets/st/sel
  src_path:     src/st/sel
  compiler:     GCC
  symbol_addrs_path:    config/generated.symbols.us.stsel.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.stsel.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.stsel.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  extensions_path: tools/splat_ext
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
segments:
  - name: stsel
    type: code
    start: 0x00000000
    vram:  0x80180000
    subalign: 2
    subsegments:
      - [0x0, .data, 2C048]
      - [0x40, data]
      - [0xD5D4, .data, D5D4]
      - [0xDBD4, data]
      - [0x176C0, rodata]
      - [0x276C0, .rodata, 2D260]
      - [0x276F0, rodata]
      - [0x27AD0, rodata] # Update function
      - [0x27AE4, rodata] # func_801B2E5C, func_801B3164, func_801B3A94
      - [0x27B14, rodata] # func_801B3164, func_801B3A94
      - [0x27B4C, rodata] # func_801B3A94, TestCollision
      - [0x27B98, rodata] # TestCollision
      - [0x27BD8, rodata] # func_801B55C8
      - [0x27BF8, .rodata, 3585C]
      - [0x27CD4, rodata] # func_801B675C
      - [0x27CF4, rodata] # func_801B69F8
      - [0x27D78, rodata] # func_801B8518, func_801B88F4
      - [0x27D90, rodata] # func_801B8A8C
      - [0x27DD4, rodata]
      - [0x2C048, c, 2C048]
      - [0x2D260, c, 2D260]
      - [0x3585C, c, 3585C]
      - [0x360D4, c, func_801B60D4]
      - [0x3642C, c, 3642C]
      - [0x38A8C, c, func_801B8A8C]
      - [0x38D24, c, 38D24]
      - [0x3AEE4, sbss]
  - [0x56B28]
