options:
  platform: psp
  basename: stare
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/are.bin
  asm_path: asm/pspeu/st/are_psp
  asset_path: assets/st/are
  src_path: src/st
  ld_script_path: build/pspeu/stare.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.stare.txt
  undefined_funcs_auto_path: build/pspeu/config/undefined_funcs_auto.pspeu.stare.txt
  undefined_syms_auto_path: build/pspeu/config/undefined_syms_auto.pspeu.stare.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  disassemble_all: true
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  global_vram_start: 0x08000000
  ld_generate_symbol_per_data_segment: true
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: 655183190ea16eb3f0404d68fbbae93e0245aa45
segments:
  - [0x0, bin, mwo_header]
  - name: stare
    type: code
    start: 0x80
    vram: 0x09237700
    bss_start_address: 0x09297F80
    bss_size: 0x300
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, are_psp/st_init]
      - [0x3E0, c, are_psp/unk_3E0]
      - [0x5C8, c, are_psp/e_breakable]
      - [0xF48, c, are_psp/unk_F48]
      - [0x20F8, c, are_psp/e_heartroom]
      - [0x2280, c, are_psp/e_room_bg]
      - [0x2360, c, are_psp/e_lock_camera]
      - [0x25C0, c, are_psp/unk_25C0]
      - [0x3180, c, are_psp/e_cavern_door]
      - [0x3F40, c, are_psp/create_entity]
      - [0x4EE8, c, are_psp/unk_4EE8]
      - [0x8BB0, c, are_psp/e_stage_name]
      - [0x9AB0, c, are/e_red_door]
      - [0xADB8, c, are_psp/st_update]
      - [0xB2F0, c, are_psp/unk_B2F0]
      - [0xF9E0, c, are_psp/e_plate_lord]
      - [0xFAB0, c, are_psp/unk_FAB0]
      - [0x15748, c, are_psp/e_valhalla_knight]
      - [0x166C0, c, are/e_particles]
      - [0x17C50, c, are_psp/unk_17C50]
      - [0x17D28, c, are_psp/e_collect]
      - [0x1BEA0, c, are_psp/e_misc]
      - [0x1CA68, c, are_psp/st_collision]
      - [0x1EC40, c, are_psp/e_mist_door]
      - [0x1EEC8, c, are_psp/e_bone_scimitar]
      - [0x1FB00, c, are/popup]
      - [0x200F8, c, are_psp/e_hunting_girl]
      - [0x21CD0, c, are_psp/e_flea_man]
      - [0x22328, c, are/e_room_fg]
      - [0x22440, c, are_psp/e_owl_knight]
      - [0x26028, c, are_psp/e_flea_armor]
      - [0x26978, c, are_psp/unk_26978]
      - [0x29B30, c, are_psp/st_common]
      - [0x2B630, c, are/prim_helpers]
      - [0x2BF00, data]
      - [0x4FAF8, .data, are/header]
      - [0x4FB28, data]
      - [0x5D3E0, .data, are/e_init]
      - [0x5D7A8, .data, are/e_red_door_tiles]
      - [0x5D7C8, data]
      - [0x5E840, .data, are/e_red_door]
      - [0x5E858, data]
      - [0x5ECD0, .data, are/e_particles]
      - [0x5ED50, data]
      - [0x5FB50, .data, are/e_room_fg]
      - [0x5FBF0, data]
      - [0x60600, .rodata, are_psp/unk_4EE8]
      - [0x60658, .rodata, are/e_red_door]
      - [0x60670, .rodata, are_psp/unk_B2F0]
      - [0x606F8, .rodata, are_psp/unk_FAB0]
      - [0x60758, .rodata, are_psp/e_valhalla_knight]
      - [0x60770, .rodata, are_psp/e_collect]
      - [0x607D0, .rodata, are_psp/e_bone_scimitar]
      - [0x607F0, .rodata, are_psp/e_hunting_girl]
      - [0x60818, .rodata, are_psp/e_owl_knight]
      - [0x60878, .rodata, are_psp/unk_26978]
      - [0x60900, bss]
  - [0x60C00]
