options:
  platform: psx
  basename: stno0
  base_path: ..
  build_path: build/us
  target_path: disks/us/ST/NO0/NO0.BIN
  asm_path: asm/us/st/no0
  asset_path: assets/st/no0
  src_path: src/st/no0
  ld_script_path: build/us/stno0.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.stno0.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.stno0.txt
  undefined_syms_auto_path: config/undefined_syms_auto.us.stno0.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: us_$VRAM
  disassemble_all: true
  section_order:
    - .data
    - .rodata
    - .text
    - .bss
    - .sbss
  ld_bss_is_noload: false
  disasm_unknown: true
sha1: d07f054f9dc8ef639257aca01deb1f24a2811924
segments:
  - name: stno0
    type: code
    start: 0
    vram: 0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, data]
      - [0x778, data, e_laydef]
      - [0x920, .data, e_init]
      - [0xC8C, .data, e_stage_decoration]
      - [0xE94, data, 419EC]
      - [0xF04, .data, e_breakable]
      - [0xFC0, data]
      - [0x1100, .data, d_prize_drops]
      - [0x113C, .data, st_update] # UNK_Invincibility0 data
      - [0x1168, .data, collision]
      - [0x1528, .data, e_red_door]
      - [0x1540, .data, e_room_fg]
      - [0x15CC, .data, e_particles]
      - [0x164C, .data, st_common] # g_SineTable
      - [0x184C, .data, e_collect]
      - [0x1B3C, .data, e_misc]
      - [0x1C14, data]
      - [0x1C34, data, clock_room]
      - [0x1CA0, .data, 4E2E0]
      - [0x1CC4, data]
      - [0x1E94, .data, e_skelerang]
      - [0x1F80, .data, e_plate_lord]
      - [0x1F90, data]
      - [0x1FC8, .data, e_ghost]
      - [0x1FE8, data]
      - [0x2194, .data, e_slinger]
      - [0x2268, data]
      - [0x234C, .data, e_ctulhu]
      - [0x2478, .data, e_axe_knight]
      - [0x25CC, .data, e_ouija_table]
      - [0x2618, .data, e_flea_man]
      - [0x2680, .data, e_skeleton]
      - [0x2770, .data, e_magically_sealed_door]
      - [0x27E0, data]
      - [0x41368, .rodata, e_explosion_puff_opaque]
      - [0x4137C, .rodata, e_red_door]
      - [0x41394, .rodata, e_collect]
      - [0x4141C, .rodata, e_misc]
      - [0x41468, .rodata, clock_room]
      - [0x414A8, .rodata, 4E2E0]
      - [0x414B8, .rodata, e_stage_name]
      - [0x414EC, .rodata, e_diplocephalus]
      - [0x41540, .rodata, e_diplocephalus_2]
      - [0x415B8, .rodata, e_skelerang]
      - [0x41624, .rodata, e_plate_lord]
      - [0x416A0, .rodata, e_plate_lord_2]
      - [0x416F0, .rodata, e_marionette]
      - [0x4171C, .rodata, e_slinger]
      - [0x41738, .rodata, e_stone_rose]
      - [0x41760, .rodata, e_ctulhu]
      - [0x4178C, .rodata, e_axe_knight]
      - [0x417B0, .rodata, e_ouija_table]
      - [0x41804, .rodata, e_flea_man]
      - [0x41818, .rodata, e_skeleton]
      - [0x41834, .rodata, e_magically_sealed_door]
      - [0x4184C, .rodata, prim_helpers]
      - [0x41854, c, e_stage_decoration]
      - [0x419EC, c, 419EC]
      - [0x41E48, c, e_breakable]
      - [0x41F98, c, e_elevator]
      - [0x42A34, c, 42A34]
      - [0x43334, c, e_explosion_puff_opaque]
      - [0x43788, c, st_update]
      - [0x43BBC, c, collision]
      - [0x45378, c, create_entity]
      - [0x45EF0, c, e_red_door]
      - [0x46BA0, c, e_room_fg]
      - [0x46C8C, c, popup]
      - [0x46FBC, c, e_particles]
      - [0x47800, c, st_common]
      - [0x48CB0, c, e_collect]
      - [0x4A21C, c, blit_char]
      - [0x4A4CC, c, e_misc]
      - [0x4C750, c]
      - [0x4CAAC, c, clock_room]
      - [0x4E2E0, c, 4E2E0]
      - [0x4E654, c, e_stage_name]
      - [0x4F4A8, c, e_diplocephalus]
      - [0x50990, c, e_diplocephalus_2]
      - [0x5191C, c, e_skelerang]
      - [0x52374, c, e_plate_lord]
      - [0x5542C, c, e_plate_lord_2]
      - [0x55E4C, c, e_ghost]
      - [0x56254, c, e_marionette]
      - [0x575E4, c, e_slinger]
      - [0x57C20, c, e_stone_rose]
      - [0x59264, c, e_ctulhu]
      - [0x5AEBC, c, e_axe_knight]
      - [0x5BDCC, c, e_ouija_table]
      - [0x5C64C, c, e_flea_man]
      - [0x5CAB0, c, e_skeleton]
      - [0x5D2B0, c, e_magically_sealed_door]
      - [0x5E09C, c, prim_helpers]
      - [0x5E8CC, .bss, create_entity]
      - [0x5E8DC, bss]
      - [0x5F54C, .bss, e_collect]
  - [0x5F58C]
