options:
  platform:     psx
  basename:     stcen
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/ST/CEN/CEN.BIN
  asm_path:     asm/us/st/cen
  asset_path:   assets/st/cen
  src_path:     src/st/cen
  compiler:     GCC
  symbol_addrs_path:    config/generated.symbols.us.stcen.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.stcen.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.stcen.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  asm_jtbl_label_macro: jlabel
  extensions_path: tools/splat_ext
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
segments:
  - name: stcen
    type: code
    start: 0x00000000
    vram:  0x80180000
    subalign: 2
    subsegments:
      - [0x0, data]
      - [0x10AC, .data, entity_relic_orb]
      - [0x1110, data]
      - [0x12D4, roomdef, g_Rooms]
      - [0x1300, data]
      - [0xD42C, rodata]
      - [0xD4B0, .rodata, D600]
      - [0xD4D8, rodata]
      - [0xD578, .rodata, entity_relic_orb]
      - [0xD5B0, .rodata, entity_unk0e]
      - [0xD5C4, rodata]
      - [0xD600, c]
      - [0x10E4C, c]
      - [0x11280, c]
      - [0x16F30, c, entity_relic_orb]
      - [0x17A00, c, entity_heart_drop]
      - [0x17B28, c, entity_unk0e]
      - [0x18084, c]
      - [0x1B274, c]
      - [0x1C704, rodata]
      - [0x1C764, rodata]
      - [0x1D374, rodata]
      - [0x1D424, rodata]
  - [0x1D46C]
