options:
  platform:     psx
  basename:     tt_000
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/SERVANT/TT_000.BIN
  asm_path:     asm/us/servant/tt_000
  asset_path:   assets/servant/tt_000
  src_path:     src/servant/tt_000
  compiler:     GCC
  symbol_addrs_path:    config/generated.symbols.us.tt_000.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.tt_000.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.tt_000.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  asm_jtbl_label_macro: jlabel
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
segments:
  - name: tt_000
    type: code
    start: 0x00000000
    vram:  0x80170000
    subalign: 2
    subsegments:
      - [0x0, .data, 10E8]
      - [0x40, .data, spriteparts]
      - [0x448, .data, 448]
      - [0x4A8, .data, 4A8]
      - [0x608, .data, 608]
      - [0x10AC, rodata] # func_80172120 jtbl
      - [0x10C4, .rodata, 10E8]
      - [0x10E8, c]
      - [0x48D8, sbss]
  - [0xA000]
