options:
  platform: psp
  basename: stno4
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/no4.bin
  asm_path: asm/pspeu/st/no4_psp
  asset_path: assets/st/no4
  src_path: src/st
  ld_script_path: build/pspeu/stno4.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.stno4.txt
  undefined_funcs_auto_path: build/pspeu/config/undefined_funcs_auto.pspeu.stno4.txt
  undefined_syms_auto_path: build/pspeu/config/undefined_syms_auto.pspeu.stno4.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  disassemble_all: true
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  global_vram_start: 0x08000000
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
  ld_generate_symbol_per_data_segment: true
sha1: 769a78f5c964dd8ff29754c346bbf5857ae67558
segments:
  - [0x0, bin, mwo_header]
  - name: stno4
    type: code
    start: 0x00000080
    vram:  0x09237700
    bss_size: 0x980
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, no4/e_bat]
      - [0x568, c, no4_psp/st_init_no4]
      - [0xA98, c, no4/e_breakable]
      - [0xEA0, c, no4/e_room_bg]
      - [0xF80, c, no4/e_lock_camera]
      - [0x11E0, c, no4/e_killer_fish]
      - [0x1798, c, no4/e_secrets]
      - [0x2108, c, no4/e_ferryman]
      - [0x5DA8, c, no4_psp/unk_5EE8] # first_c_file PSX
      - [0xC388, c, no4/create_entity]
      - [0xD330, c, no4/e_bone_archer]
      - [0xE4E8, c, no4/e_stage_name]
      - [0xF3F0, c, no4/e_red_door]
      - [0x106F8, c, no4/st_update]
      - [0x10C30, c, no4/e_fishhead]
      - [0x120E0, c, no4/e_toad]
      - [0x12920, c, no4/e_frog]
      - [0x131F0, c, no4/e_particles]
      - [0x14780, c, no4/e_collect]
      - [0x189D0, c, no4/e_misc]
      - [0x190D8, c, no4/collision]
      - [0x1B2B0, c, no4/water_effects]
      - [0x1E320, c, no4/popup]
      - [0x1E918, c, no4/e_frozen_shade]
      - [0x220E0, c, no4/e_room_fg]
      - [0x221F8, c, no4/e_skeleton_ape]
      - [0x233A0, c, no4/st_common]
      - [0x24C20, c, no4/prim_helpers]
      - [0x25360, c, no4/e_spear_guard]
      - [0x26740, c, no4/cutscene]
      - [0x28700, .data, no4/e_bat]
      - [0x28740, data]
      - [0x30260, .data, no4/e_red_door_tiles]
      - [0x30290, .data, no4_psp/e_init]
      - [0x305D0, data]
      - [0x30728, .data, no4/cutscene_data]
      - [0x30A68, .data, no4/e_breakable]
      - [0x30B88, data]
      - [0x65910, .data, no4/background_block_init]
      - [0x65950, .data, no4/e_lock_camera]
      - [0x659C8, .data, no4/e_killer_fish]
      - [0x65A38, .data, no4/e_secrets]
      - [0x65AA8, .data, no4/e_ferryman]
      - [0x65C40, data]
      - [0x662C8, .data, no4/e_bone_archer]
      - [0x66460, .data, no4/e_stage_name]
      - [0x67200, .data, no4/e_red_door]
      - [0x67218, .data, no4/st_update]
      - [0x67248, .data, no4/e_fishhead]
      - [0x67348, .data, no4/e_toad]
      - [0x67418, .data, no4/e_frog]
      - [0x67498, .data, no4/e_particles]
      - [0x67518, data]
      - [0x67A60, .data, no4/e_misc]
      - [0x67AB0, .data, no4/collision]
      - [0x67E88, .data, no4/water_effects]
      - [0x67F38, .data, no4/e_frozen_shade]
      - [0x681D0, .data, no4/e_room_fg]
      - [0x68270, .data, no4/e_skeleton_ape]
      - [0x68430, .data, no4/e_spear_guard]
      - [0x68710, .data, no4/cutscene]
      - [0x68A18, data]
      - [0x68A80, .rodata, no4/e_ferryman]
      - [0x68AE0, .rodata, no4_psp/unk_5EE8]
      - [0x68AF8, .rodata, no4/e_red_door]
      - [0x68B10, .rodata, no4/e_fishhead]
      - [0x68B28, .rodata, no4/e_toad]
      - [0x68B48, .rodata, no4/e_collect]
      - [0x68BA8, .rodata, no4/e_frozen_shade]
      - [0x68BE0, .rodata, no4/e_skeleton_ape]
      - [0x68C00, .rodata, no4/e_spear_guard]
      - [0x68C38, .rodata, no4/cutscene]
      - [0x68D00, bss, 68D00]
      - [0x68D10, .bss, no4_psp/st_init_no4]
      - [0x68FB0, bss, 68FB0]
      - [0x68FB8, .bss, no4/e_lock_camera]
      - [0x68FC0, bss, 68FC0]
      - [0x68FD0, .bss, no4/create_entity]
      - [0x68FF0, .bss, no4/e_collect] #BlitChar
      - [0x69050, bss, 69050]
  - [0x69600]
