options:
  platform:     psx
  basename:     dra
  base_path:    ..
  build_path:   build/hd
  target_path:  disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/dra.bin
  asm_path:     asm/hd/dra
  asset_path:   assets/dra
  src_path:     src/dra
  ld_script_path: build/hd/dra.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/symbols.hd.txt
    - config/symbols.hd.dra.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.hd.dra.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.hd.dra.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  asm_jtbl_label_macro: jlabel
  extensions_path: tools/splat_ext
  section_order:
    - ".data"
    - ".rodata"
    - ".text"
    - ".bss"
    - ".sbss"
sha1: ea268a06a7eb7cd99928ba40e774577c4a1c504d
segments:
  - name: dra
    type: code
    start: 0x00000000
    vram:  0x800A0000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .data, dra_header]
      - [0x144, .data, 42398]
      - [0x160, .data, play]
      - [0x240, .data, loading]
      - [0x248, .data, 47BB8]
      - [0x510, .data, save_mgr_pre]
      - [0x518, palette, memcard_0]
      - [0x538, palette, memcard_1]
      - [0x558, palette, memcard_2]
      - [0x578, palette, memcard_3]
      - [0x598, palette, memcard_4]
      - [0x5B8, palette, memcard_5]
      - [0x5D8, palette, memcard_6]
      - [0x5F8, palette, memcard_7]
      - [0x618, palette, memcard_8]
      - [0x638, palette, memcard_9]
      - [0x658, palette, memcard_10]
      - [0x678, palette, memcard_11]
      - [0x698, palette, memcard_12]
      - [0x6B8, palette, memcard_13]
      - [0x6D8, palette, memcard_14]
      - [0x6F8, palette, memcard_15]
      - [0x718, ci4, memcard_0, 16, 48]
      - [0x898, ci4, memcard_1, 16, 48]
      - [0xA18, ci4, memcard_2, 16, 48]
      - [0xB98, ci4, memcard_3, 16, 48]
      - [0xD18, ci4, memcard_4, 16, 48]
      - [0xE98, ci4, memcard_5, 16, 48]
      - [0x1018, ci4, memcard_6, 16, 48]
      - [0x1198, ci4, memcard_7, 16, 48]
      - [0x1318, ci4, memcard_8, 16, 48]
      - [0x1498, ci4, memcard_9, 16, 48]
      - [0x1618, ci4, memcard_10, 16, 48]
      - [0x1798, ci4, memcard_11, 16, 48]
      - [0x1918, ci4, memcard_12, 16, 48]
      - [0x1A98, ci4, memcard_13, 16, 48]
      - [0x1C18, ci4, memcard_14, 16, 48]
      - [0x1D98, ci4, memcard_15, 16, 48]
      - [0x1F18, .data, save_mgr]
      - [0x2178, .data, 4A538] # D_800A21B8
      - [0x23F8, .data, 4A538] # D_800A2438
      - [0x23FC, .data, demo] # D_800A243C
      - [0x241C, .data, 5087C] # D_800A245C
      - [0x293C, .data, 5087C] # D_800A297C
      - [0x2B6C, .data, 5087C] # D_800A2BC0
      - [0x2BB8, .data, 5087C] # D_800A2C0C, D_800A2D44
      - [0x2CF4, .data, menu] # array of strings
      - [0x2D1C, .data, menu] # HD exclusive array of strings
      - [0x2D88, .data, menu]
      - [0x2ED0, .data, 5D5BC] # g_LevelHPIncrease
      - [0x2EF8, .data, 5D5BC] # hud sprites def
      - [0x2FCC, .data, 5D5BC] # g_CapePaletteDefs
      - [0x301C, .data, 5D5BC] # g_CheatCodes
      - [0x3024, .data, 5D5BC] # D_800A3014
      - [0x3144, .data, 627C4] # D_800A3194
      - [0x31C0, .data, 63ED4] # D_800A3210
      - [0x3340, .data, 63ED4] # D_800A33A0-D_800A35D0
      - [0x37E8, .data, 63ED4] # Palette, GFX desc until D_800A3BB8
      - [0x3C50, .data, lba_stage]
      - [0x4A10, .data, config_jp]
      - [0xC8BC, .data, d_C910]
      - [0xCA20, .data, cd]
      - [0xCE48, .data, d_CD80]
      - [0xCEB8, .data, 692E8]
      - [0xCFDC, .data, 6D59C]
      - [0xD038, .data, d_CF74]
      - [0xD188, .data, 7A4D0] # D_800AD0C4
      - [0xD298, assets, factory_blueprint, g_FactoryBlueprints]
      - [0xD57C, .data, 7E4BC]
      - [0xDC98, .data, d_DBD4]
      - [0xE358, .data, d_E294]
      - [0x1085C, .data, d_10798]
      - [0x109E8, .data, 8D3E8] # D_800B0924 to D_800B09F8
      - [0x10B00, .data, 8D3E8] # D_800B0A3C to D_800B0AEC
      - [0x10BF8, .data, 8D3E8] # D_800B0CB4 and D_800B0F94
      - [0x11140, raw, vh_0] # aPbav
      - [0x14140, raw, vh_1] # aPbav_0
      - [0x16140, raw, vh_2] # aPbav_2
      - [0x18140, raw, vh_3] # aPbav_1
      - [0x1A140, data] # aPqes_1
      - [0x1D140, .data, 91EBC] # g_CdVolumeTable
      - [0x1D260, .data, 91EBC] # g_VolumeTable
      - [0x1D284, .data, 91EBC] # g_DebugEnabled
      - [0x1D288, .data, 91EBC] # D_800BD1C4
      - [0x1D28C, .data, 91EBC] # g_VabAddrs
      - [0x1D2A4, .data, 91EBC] # g_SeqInfo
      - [0x1D2E8, data, assets, music_xa, g_XaMusicConfigs] # g_XaMusicConfigs
      - [0x1F5F8, assets, sfx, g_SfxData] # g_SfxData
      - [0x20A20, .data, 953A0]
      - [0x22220, cmp, D_800C217C]
      - [0x22854, cmp, D_800C27B0]
      - [0x23604, cmp, D_800C3560]
      - [0x24908, cmp, D_800C4864]
      - [0x24B34, cmp, D_800C4A90]
      - [0x24D90, .data, d_24CEC]
      - [0x253C8, raw, g_GfxEquipIcon]
      - [0x2F3C8, .data, d_2F324]
      - [0x38978, raw, g_PalEquipIcon]
      - [0x3B178, .data, d_3B0D4]
      - [0x3B458, .rodata, 42398]
      - [0x3B618, .rodata, play]
      - [0x3B808, .rodata, loading]
      - [0x3B938, .rodata, 47BB8]
      - [0x3BE60, .rodata, save_mgr]
      - [0x3C11C, .rodata, 4A538]
      - [0x3C204, .rodata, collider]
      - [0x3C404, .rodata, demo]
      - [0x3C488, .rodata, 5087C]
      - [0x3C548, .rodata, menu]
      - [0x3CC18, .rodata, 5D5BC]
      - [0x3CC78, .rodata, 627C4]
      - [0x3CED4, .rodata, 63ED4]
      - [0x3CEF0, .rodata, lba_stage]
      - [0x3D29C, .rodata, config_jp]
      - [0x40C74, .rodata, cd]
      - [0x40D64, .rodata, 692E8]
      - [0x40FA8, .rodata, 6D59C]
      - [0x41224, .rodata, 704D0]
      - [0x4132C, .rodata, 71830]
      - [0x414A4, .rodata, 72BB0]
      - [0x41904, .rodata, 75F54]
      - [0x41960, .rodata, 78D0C]
      - [0x419C0, .rodata, 7A4D0]
      - [0x41BD0, .rodata, 7E4BC]
      - [0x41CF0, .rodata, 843B0]
      - [0x41DAC, .rodata, 8A0A4]
      - [0x41DCC, .rodata, 8D3E8]
      - [0x41E4C, .rodata, 8D3E8]
      - [0x41F50, .rodata, 92F60]
      - [0x41F78, .rodata, 93290]
      - [0x41FA8, .rodata, 93BDC]
      - [0x41FD0, .rodata, 94F50]
      - [0x42270, .rodata, 953A0]
      - [0x422B4, c, 42398]
      - [0x44EC8, c, play]
      - [0x463E4, c, loading]
      - [0x48250, c, 47BB8]
      - [0x493BC, c, pads]
      - [0x4957C, c, save_mgr]
      - [0x4ABF0, c, 4A538]
      - [0x4FAE0, c, collider]
      - [0x5027C, c, demo]
      - [0x50F00, c, 5087C]
      - [0x54E50, c, menu]
      - [0x5D570, c, 5D5BC]
      - [0x62654, c, 627C4]
      - [0x63D1C, c, 63ED4]
      - [0x67200, c, cd]
      - [0x69100, c, 692E8]
      - [0x6D2E0, c, 6D59C]
      - [0x7021C, c, 704D0]
      - [0x71574, c, 71830]
      - [0x7291C, c, 72BB0]
      - [0x75C44, c, 75F54]
      - [0x78A04, c, 78D0C]
      - [0x7A1C8, c, 7A4D0]
      - [0x7E168, c, 7E4BC]
      - [0x8403C, c, 843B0]
      - [0x8A528, c, 8A0A4]
      - [0x8D050, c, 8D3E8]
      - [0x91A98, c, 91EBC]
      - [0x92B3C, c, 92F60]
      - [0x92E6C, c, 93290]
      - [0x937B8, c, 93BDC]
      - [0x94B2C, c, 94F50]
      - [0x94F7C, c, 953A0]
      - [0x95E88, .bss, bss]
  - name: dra_data
    type: data
    start: 0x9B270
    vram:  0x8013B370
    subsegments:
      - [0x9B270, raw, vb_0] # D_8013B6A0, TODO verify data length
      - [0xDCF1C, raw, vb_1] # D_8017D01C, TODO verify data length
      - [0xEAFEC, raw, vb_2] # D_8018B4E0, TODO verify data length
      - [0x10978C, raw, vb_3] # D_801A9C80, TODO verify data length
  - [0x115EDC]
