options:
  platform: psp
  basename: tt_001
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/tt_001.bin
  asm_path: asm/pspeu/servant/tt_001
  asset_path: assets/servant/tt_001
  src_path: src/servant/tt_001
  ld_script_path: build/pspeu/tt_001.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
  undefined_funcs_auto_path: build/pspeu/config/undefined_funcs_auto.pspeu.tt_001.txt
  undefined_syms_auto_path: build/pspeu/config/undefined_syms_auto.pspeu.tt_001.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: yes
  asm_jtbl_label_macro: jlabel
  disassemble_all: true
  section_order:
    - ".text"
    - ".data"
    - ".rodata"
    - ".bss"
  ld_bss_is_noload: True
  disasm_unknown: True
  global_vram_start: 0x08000000
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
  ld_generate_symbol_per_data_segment: true
sha1: 0e75ffe97e2cc57448b171052ac66b3cc2671f72
segments:
  - [0x0, bin, mwo_header]
  - name: tt_001
    type: code
    start: 0x00000080
    vram: 0x092E7680
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, ghost]
      - [0x3020, c, init]
      - [0x3080, .data, servant_spriteparts]
      - [0x3508, .data, servant_clutdata]
      - [0x3568, .data, ghost]
      - [0x3FB0, .data, init]
      - [0x4000, .rodata, ghost]
      - [0x4080, .bss, ghost]
  - [0x4364]
