options:
  platform:     psx
  basename:     stmad
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/ST/MAD/MAD.BIN
  asm_path:     asm/us/st/mad
  asset_path:   assets/st/mad
  src_path:     src/st/mad
  compiler:     GCC
  symbol_addrs_path:    config/generated.symbols.stmad.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.stmad.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.stmad.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  extensions_path: tools/splat_ext
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
segments:
  - name: stmad
    type: code
    start: 0x00000000
    vram:  0x80180000
    subalign: 2
    subsegments:
      - [0x0, rodata]
      - [0xE40, rodata]
      - [0x1130, roomdef, g_Rooms]
      - [0x11D4, rodata] # assets/st/mad/0.objlayout
      # - [0x11E8, rodata] # assets/st/mad/1.objlayout
      # - [0x1206, rodata] # assets/st/mad/2.objlayout
      # - [0x12B0, rodata] # assets/st/mad/3.objlayout
      # - [0x135A, rodata] # assets/st/mad/4.objlayout
      # - [0x1404, rodata] # assets/st/mad/5.objlayout
      # - [0x14AE, rodata] # assets/st/mad/6.objlayout
      # - [0x1558, rodata] # assets/st/mad/7.objlayout
      # - [0x1602, rodata] # assets/st/mad/8.objlayout
      # - [0x16AC, rodata] # assets/st/mad/9.objlayout
      # - [0x1756, rodata] # assets/st/mad/10.objlayout
      # - [0x1774, rodata] # assets/st/mad/11.objlayout
      # - [0x1788, rodata] # assets/st/mad/12.objlayout
      # - [0x17A6, rodata] # assets/st/mad/13.objlayout
      # - [0x1850, rodata] # assets/st/mad/14.objlayout
      # - [0x18FA, rodata] # assets/st/mad/15.objlayout
      # - [0x19A4, rodata] # assets/st/mad/16.objlayout
      # - [0x1A4E, rodata] # assets/st/mad/17.objlayout
      # - [0x1AF8, rodata] # assets/st/mad/18.objlayout
      # - [0x1BA2, rodata] # assets/st/mad/19.objlayout
      # - [0x1C4C, rodata] # assets/st/mad/20.objlayout
      # - [0x1CF6, rodata] # assets/st/mad/21.objlayout
      - [0x1404, rodata]
      - [0x1774, rodata]
      - [0x19A4, rodata]
      - [0x1D14, rodata]
      - [0xD794, rodata]
      - [0xD884, rodata]
      - [0xD8C8, c]
      - [0x197D8, data]
  - [0x19E94]
