options:
  platform:     psx
  basename:     dra
  base_path:    ..
  target_path:  iso/DRA.BIN
  asm_path:     asm/dra
  asset_path:   assets/dra
  src_path:     src/dra
  compiler:     GCC
  symbol_addrs_path:    config/generated.symbols.dra.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.dra.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.dra.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
segments:
  - name: dra
    type: code
    start: 0x00000000
    vram:  0x800A0000
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x518, rodata]
      - [0x1F18, rodata]
      - [0x2BC0, rodata]
      - [0x4B04, rodata, equipment_data]
      - [0x7718, rodata, accessory_data]
      - [0x8000, rodata]
      - [0x8900, rodata]
      - [0xCEB0, rodata]
      - [0xD670, rodata]
      - [0x3B3F0, rodata]
      - [0x3B44C, .rodata, 42398]
      - [0x3B524, rodata]
      - [0x3B560, rodata]
      - [0x3B790, rodata]
      - [0x3B7A0, rodata]
      - [0x3B7E8, .rodata, 46FD4]
      - [0x3B828, rodata]
      - [0x3BF10, rodata]
      - [0x3C160, rodata]
      - [0x3CBC4, .rodata, 5D7C0]
      - [0x3CBDC, rodata]
      - [0x3CC80, rodata]
      - [0x3CD00, rodata]
      - [0x3CD10, rodata]
      - [0x40FC0, rodata]
      - [0x41360, rodata]
      - [0x41750, rodata]
      - [0x418E0, .rodata, 73AAC]
      - [0x418F4, rodata]
      - [0x41990, rodata]
      - [0x419B0, rodata]
      - [0x419D0, .rodata, 75DA0]
      - [0x419E8, rodata]
      - [0x41A00, rodata]
      - [0x41F30, rodata]
      - [0x41F70, rodata]
      - [0x41FB0, rodata]
      - [0x42000, rodata]
      - [0x42398, c, 42398]
      - [0x46FD4, c, 46FD4]
      - [0x4768C, c, 4768C]
      - [0x5D7C0, c, 5D7C0]
      - [0x5D874, c, 5D874]
      - [0x73AAC, c, 73AAC]
      - [0x73D7C, c, 73D7C]
      - [0x75DA0, c, 75DA0]
      - [0x75F54, c, 75F54]
      - [0x962AC, data]
  - [0x119870]
