options:
  platform: psp
  basename: tt_003
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/tt_003.bin
  asm_path: asm/pspeu/servant/tt_003
  asset_path: assets/servant/tt_003
  src_path: src/servant/tt_003
  ld_script_path: build/pspeu/tt_003.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
  undefined_funcs_auto_path: build/pspeu/config/undefined_funcs_auto.pspeu.tt_003.txt
  undefined_syms_auto_path: build/pspeu/config/undefined_syms_auto.pspeu.tt_003.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: yes
  asm_jtbl_label_macro: jlabel
  disassemble_all: true
  section_order:
    - ".text"
    - ".data"
    - ".rodata"
    - ".bss"
  ld_bss_is_noload: True
  disasm_unknown: True
  global_vram_start: 0x08000000
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
  ld_generate_symbol_per_data_segment: true
sha1: ca15c105a7c6941fcfd1c709b739f5bba5f98358
segments:
  - [0x0, bin, mwo_header]
  - name: tt_003
    type: code
    start: 0x00000080
    vram: 0x092E7680
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, demon]
      - [0x8308, c, init]
      - [0x8380, .data, demon_spriteparts]
      - [0x9D60, .data, demon]
      - [0xAD88, .data, init]
      - [0xAE00, .rodata, demon]
      - [0xAE80, .bss, demon]
  - [0xB2A0]
