options:
  platform:     psx
  basename:     ric
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/BIN/RIC.BIN
  asm_path:     asm/us/ric
  asset_path:   assets/ric
  src_path:     src/ric
  ld_script_path: build/us/ric.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.ric.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.ric.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.ric.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  asm_jtbl_label_macro: jlabel
  extensions_path: tools/splat_ext
  section_order:
    - ".data"
    - ".rodata"
    - ".text"
    - ".bss"
    - ".sbss"
segments:
  - name: ric
    type: code
    start: 0x00000000
    vram:  0x8013C000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .data, pl_header]
      - [0x20, spritesheet, richter, disks/us/BIN/F_GAME2.BIN, 32]
      - [0x170AC, .data, spriteparts]
      - [0x18568, .data, d_18568]
      - [0x18688, assets, subweapondefs, D_80154688]
      - [0x188F4, .data, 21250]
      - [0x1895C, .data, 21250] # entity table
      - [0x18A6C, .data, 21250] # blueprints
      - [0x18C40, .data, 24788]
      - [0x18ED4, .data, 24788] # func_80162C84
      - [0x18F7C, .data, 26C84]
      - [0x1938C, .data, pl_anims]    
      - [0x199AC, .data, 2A060]
      - [0x19D94, .data, 2C4C4]
      - [0x19EE0, .data, 319C4]
      - [0x19EFC, .data, e_giant_spinning_cross]
      - [0x1A444, .rodata, 1AC60] # UpdateEntityRichter
      - [0x1A5E0, .rodata, 1AC60]
      - [0x1A5F0, .rodata, 1CB04]
      - [0x1A7A8, .rodata, 1FCD0]
      - [0x1A7C0, .rodata, 202A8]
      - [0x1A800, .rodata, 20920]
      - [0x1A80C, .rodata, 21250]
      - [0x1A918, .rodata, 24788]
      - [0x1A9D0, .rodata, 24788] # func_80162C84
      - [0x1A9E8, .rodata, 26C84] # EntityPlayerBlinkWhite
      - [0x1AA28, .rodata, 2A060]
      - [0x1AAA0, .rodata, 2A060]
      - [0x1AABC, .rodata, 2C4C4]
      - [0x1AAD4, .rodata, 2C4C4] # RicEntitySubwpnCrashCross
      - [0x1AAEC, .rodata, 2C4C4] # RicEntityRevivalColumn
      - [0x1AB04, .rodata, 2C4C4] # RicEntitySubwpnCross
      - [0x1AB24, .rodata, 2C4C4] # RicEntitySubwpnAgunea
      - [0x1AB38, .rodata, 319C4]
      - [0x1AB68, .rodata, e_giant_spinning_cross]
      - [0x1AC50, .rodata, e_giant_spinning_cross]
      - [0x1AC60, c, 1AC60]
      - [0x1CB04, c, 1CB04]
      - [0x1FCD0, c, 1FCD0]
      - [0x202A8, c, 202A8]
      - [0x20920, c, 20920]
      - [0x21250, c, 21250]
      - [0x24788, c, 24788]
      - [0x26C84, c, 26C84]
      - [0x2A060, c, 2A060]
      - [0x2C4C4, c, 2C4C4]
      - [0x319C4, c, 319C4]
      - [0x359A4, c, 319C4]
      - [0x3728C, c, e_giant_spinning_cross]
      - [0x37B64, .bss, 1CB04]
      - [0x37F80, .bss, 21250]
      - [0x38000, .bss, 2A060]
      - [0x38088, .bss, 2C4C4]
      - [0x39894, .bss, 319C4]
      - [0x398E0, .bss, bss]
  - [0x39A58]
