options:
  platform: psx
  basename: stlib
  base_path: ..
  build_path: build/us
  target_path: disks/us/ST/LIB/LIB.BIN
  asm_path: asm/us/st/lib
  asset_path: assets/st/lib
  src_path: src/st/lib
  ld_script_path: build/us/stlib.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.stlib.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.stlib.txt
  undefined_syms_auto_path: config/undefined_syms_auto.us.stlib.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: us_$VRAM
  disassemble_all: true
  section_order:
    - .data
    - .rodata
    - .text
    - .bss
    - .sbss
  ld_bss_is_noload: false
  disasm_unknown: true
sha1: ddd108c3a9ec564d34063e5008685a9a41f8eabd
segments:
  - name: stlib
    type: code
    start: 0
    vram:  0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, data]
      - [0x134C, .data, e_shop]
      - [0x1528, data]
      - [0x1C7C, .data, st_update]
      - [0x1CA8, .data, collision]
      - [0x2068, .data, e_red_door]
      - [0x2080, .data, e_room_fg]
      - [0x210C, .data, st_common]
      - [0x230C, .data, e_misc]
      - [0x23C0, .data, e_collect]
      - [0x26B0, .data, e_misc_2]
      - [0x2714, .data, e_bloody_zombie]
      - [0x280C, data]
      - [0x2B80, .data, en_thornweed_corpseweed]
      - [0x2C38, data] # unused data?
      - [0x2C48, data]
      - [0x2B938, .rodata, first_c_file]
      - [0x2CE78, .rodata, e_shop]
      - [0x2CF14, .rodata, unk_33EC8]
      - [0x2D848, .rodata, unk_3BEB0]
      - [0x2D868, .rodata, unk_3C57C]
      - [0x2D980, .rodata, e_chair]
      - [0x2D9C4, .rodata, e_red_door]
      - [0x2D9DC, .rodata, e_collect]
      - [0x2DA64, .rodata, e_misc_2]
      - [0x2DAB0, .rodata, e_bloody_zombie]
      - [0x2DAD8, .rodata, unk_49870]
      - [0x2DB54, .rodata, e_stage_name]
      - [0x2DB88, .rodata, unk_4C054]
      - [0x2DC48, .rodata, en_thornweed_corpseweed]
      - [0x2DC84, .rodata, e_skeleton]
      - [0x2DD08, .rodata, unk_4F918]
      - [0x2DDA4, .rodata, prim_helpers]
      - [0x2DDAC, .rodata, unk_51BCC]
      - [0x2DED0, c, first_c_file]
      - [0x3245C, c, e_shop]
      - [0x33EC8, c, unk_33EC8]
      - [0x3BEB0, c, unk_3BEB0]
      - [0x3C57C, c, unk_3C57C]
      - [0x3EDD8, c, e_chair]
      - [0x3EFEC, c, unk_3EFEC]
      - [0x3F130, c, st_update]
      - [0x3F564, c, collision]
      - [0x40D20, c, create_entity]
      - [0x41898, c, e_red_door]
      - [0x42548, c, e_room_fg]
      - [0x42634, c, st_common]
      - [0x43AE4, c, e_misc]
      - [0x45E80, c, e_collect]
      - [0x473EC, c, blit_char]
      - [0x4769C, c, e_misc_2]
      - [0x487F0, c, e_bloody_zombie]
      - [0x49870, c, unk_49870]
      - [0x4A68C, c, e_stage_name]
      - [0x4B4E0, c, e_particles]
      - [0x4BD24, c, popup]
      - [0x4C054, c, unk_4C054]
      - [0x4DB6C, c, en_thornweed_corpseweed]
      - [0x4F094, c, e_skeleton]
      - [0x4F918, c, unk_4F918]
      - [0x5139C, c, prim_helpers]
      - [0x51BCC, c, unk_51BCC]
      - [0x5415C, bss]
      - [0x545C4, .bss, create_entity]
      - [0x545D4, bss]
      - [0x5528C, .bss, e_collect]
  - [0x552CC]
