options:
  platform:     psx
  basename:     main
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/SLUS_000.67
  asm_path:     asm/us/main
  asset_path:   assets/main
  src_path:     src/main
  ld_script_path: build/us/main.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.main.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.main.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.main.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  asm_jtbl_label_macro: jlabel
  disassemble_all: true
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
    - ".bss"
sha1: 54828d4e44ea9575f2a0917ff63def42a304abff
segments:
  - [0x800, header]
  - name: main
    type: code
    start: 0x00000800
    vram:  0x80010000
    align: 4
    subalign: 4
    subsegments:
      - [0x800, .rodata, main]
      - [0x874, .rodata, psxsdk/libgpu/font]
      - [0x8F8, .rodata, psxsdk/libgpu/prim]
      - [0x9C8, .rodata, psxsdk/libgpu/sys]
      - [0xBC4, .rodata, psxsdk/libetc/vsync] # aVsyncTimeout
      - [0xBD4, .rodata, psxsdk/libetc/intr]
      - [0xC40, .rodata, psxsdk/libetc/intr_dma]
      - [0xC6C, .rodata, psxsdk/libc/sprintf]
      - [0xD48, .rodata, psxsdk/libcd/event]
      - [0xD60, .rodata, psxsdk/libcd/sys]
      - [0xD68, rodata] # referenced indirectly by libcd functions (see 1BCE0.data.s)
      - [0xEB4, .rodata, psxsdk/libcd/bios]
      - [0xFB8, .rodata, psxsdk/libcd/iso9660]
      - [0x11A4, .rodata, psxsdk/libcd/cdread]
      - [0x11E8, .rodata, psxsdk/libcd/c_011]
      - [0x1200, .rodata, psxsdk/libsnd/seqinit]
      - [0x1260, .rodata, psxsdk/libsnd/seqread]
      - [0x14D4, .rodata, psxsdk/libsnd/sstick]
      - [0x14EC, .rodata, psxsdk/libspu/spu]
      - [0x1534, .rodata, psxsdk/libspu/s_si]
      - [0x1574, .rodata, psxsdk/libspu/s_sva]
      - [0x15B4, .rodata, psxsdk/libspu/s_sca]
      - [0x15F4, asm, psxsdk/2mbyte]
      - [0x16B8, c, main]
      - [0x192C, c, psxsdk/libgpu/ext]
      - [0x1B4C, c, psxsdk/libgpu/font]
      - [0x2554, c, psxsdk/libgpu/prim]
      - [0x2C34, c, psxsdk/libgpu/sys]
      - [0x5938, c, psxsdk/libapi/c57]
      - [0x5948, c, psxsdk/libapi/c66]
      - [0x5958, c, psxsdk/libapi/c67]
      - [0x5968, c, psxsdk/libapi/c73]
      - [0x5978, c, psxsdk/libapi/c112]
      - [0x5988, c, psxsdk/libapi/a50]
      - [0x5998, c, psxsdk/libapi/a51]
      - [0x59A8, c, psxsdk/libapi/a52]
      - [0x59B8, c, psxsdk/libapi/a53]
      - [0x59C8, c, psxsdk/libapi/a54]
      - [0x59D8, c, psxsdk/libapi/a65]
      - [0x59E8, c, psxsdk/libapi/a66]
      - [0x59F8, c, psxsdk/libapi/a67]
      - [0x5A08, c, psxsdk/libapi/a69]
      - [0x5A18, c, psxsdk/libapi/a81]
      - [0x5A28, c, psxsdk/libapi/a91]
      - [0x5A38, c, psxsdk/libetc/pad]
      - [0x5AD8, c, psxsdk/libapi/a20]
      - [0x5AE8, c, psxsdk/libapi/a21]
      - [0x5AF8, c, psxsdk/libapi/a22]
      - [0x5B08, c, psxsdk/libetc/vsync]
      - [0x5CEC, c, psxsdk/libapi/l10]
      - [0x5CFC, c, psxsdk/libetc/intr]
      - [0x640C, c, psxsdk/libapi/c114]
      - [0x641C, c, psxsdk/libapi/a23]
      - [0x642C, c, psxsdk/libapi/a24]
      - [0x643C, c, psxsdk/libapi/a25]
      - [0x644C, c, psxsdk/libapi/a36]
      - [0x645C, c, psxsdk/libapi/a37]
      - [0x646C, c, psxsdk/libetc/intr_vb]
      - [0x6594, c, psxsdk/libetc/intr_dma]
      - [0x683C, c, psxsdk/libetc/vmode]
      - [0x6864, c, psxsdk/libc/a56]
      - [0x6874, c, psxsdk/libc/a63]
      - [0x6884, c, psxsdk/libc/c19]
      - [0x6894, c, psxsdk/libc/c21]
      - [0x68A4, c, psxsdk/libc/c25]
      - [0x68B4, c, psxsdk/libc/c27]
      - [0x68C4, c, psxsdk/libc/c42]
      - [0x68D4, c, psxsdk/libc/c43]
      - [0x68E4, c, psxsdk/libc/c47]
      - [0x68F4, c, psxsdk/libc/c48]
      - [0x6904, c, psxsdk/libc/c51]
      - [0x6914, c, psxsdk/libc/c52]
      - [0x6924, c, psxsdk/libc/c63]
      - [0x6934, c, psxsdk/libc/sprintf]
      - [0x7190, c, psxsdk/libc/c46]
      - [0x71A0, c, psxsdk/libc/memmove]
      - [0x720C, c, psxsdk/libcard/c171]
      - [0x721C, c, psxsdk/libcard/c172]
      - [0x722C, c, psxsdk/libcard/a74]
      - [0x723C, c, psxsdk/libcard/a75]
      - [0x724C, c, psxsdk/libcard/card]
      - [0x7284, c, psxsdk/libcard/a78]
      - [0x7294, c, psxsdk/libcard/a80]
      - [0x72A4, c, psxsdk/libgs/gs_007]
      - [0x72DC, c, psxsdk/libapi/counter]
      - [0x7454, c, psxsdk/libgs/gs_008]
      - [0x7478, c, psxsdk/libgs/gs_009]
      - [0x749C, c, psxsdk/libgte/geo_00]
      - [0x7568, c, psxsdk/libgte/geo_01]
      - [0x7608, c, psxsdk/libgte/fog_01]
      - [0x766C, asm, psxsdk/libgte/msc00]
      - [0x76EC, asm, psxsdk/libgte/msc01]
      - [0x777C, asm, psxsdk/libgte/msc02]
      - [0x7A1C, asm, psxsdk/libgte/msc09]
      - [0x7ABC, asm, psxsdk/libgte/mtx_00]
      - [0x84DC, asm, psxsdk/libgte/mtx_07]
      - [0x850C, asm, psxsdk/libgte/mtx_08]
      - [0x863C, asm, psxsdk/libgte/mtx_09]
      - [0x866C, asm, psxsdk/libgte/mtx_10]
      - [0x869C, asm, psxsdk/libgte/mtx_11]
      - [0x86CC, asm, psxsdk/libgte/mtx_12]
      - [0x86EC, asm, psxsdk/libgte/reg03]
      - [0x87FC, asm, psxsdk/libgte/reg10]
      - [0x881C, asm, psxsdk/libgte/reg11]
      - [0x883C, asm, psxsdk/libgte/reg12]
      - [0x885C, asm, psxsdk/libgte/reg13]
      - [0x886C, asm, psxsdk/libgte/smp]
      - [0x8A4C, asm, psxsdk/libgte/smp_02]
      - [0x8A7C, asm, psxsdk/libgte/smp_03]
      - [0x8ADC, asm, psxsdk/libgte/smp_04]
      - [0x8B0C, asm, psxsdk/libgte/smp_05]
      - [0x8B20, asm, psxsdk/libgte/smp_06]
      - [0x8B3C, asm, psxsdk/libgte/cmb_00]
      - [0x8BBC, asm, psxsdk/libgte/cmb_01]
      - [0x8C1C, asm, psxsdk/libgte/cmb_02]
      - [0x8C9C, asm, psxsdk/libgte/cmb_06]
      - [0x8D2C, asm, psxsdk/libgte/cmb_07]
      - [0x8DDC, asm, psxsdk/libgte/cmb_09]
      - [0x8EAC, asm, psxsdk/libgte/fgo_01]
      - [0x913C, asm, psxsdk/libgte/fgo_02]
      - [0x93CC, asm, psxsdk/libgte/fgo_04]
      - [0x956C, asm, psxsdk/libgte/fgo_05]
      - [0x970C, asm, psxsdk/libgte/fgo_06]
      - [0x98AC, c, psxsdk/libgte/ratan]
      - [0x9A2C, asm, psxsdk/libgte/patchgte]
      - [0x9ACC, c, psxsdk/libapi/c68]
      - [0x9ADC, c, psxsdk/libcd/cdrom]
      - [0x9B0C, c, psxsdk/libcd/event]
      - [0x9C14, c, psxsdk/libapi/a07]
      - [0x9C24, c, psxsdk/libcd/sys]
      - [0xA398, c, psxsdk/libcd/bios]
      - [0xBA98, c, psxsdk/libcd/iso9660]
      - [0xC464, c, psxsdk/libc/c23]
      - [0xC474, c, psxsdk/libc/c24]
      - [0xC484, c, psxsdk/libcd/cdread]
      - [0xCA6C, c, psxsdk/libcd/cdread2]
      - [0xCB20, c, psxsdk/libcd/c_002]
      - [0xCB80, c, psxsdk/libcd/c_003]
      - [0xCBD8, c, psxsdk/libcd/c_004]
      - [0xCCC8, c, psxsdk/libcd/c_005]
      - [0xCD50, c, psxsdk/libcd/c_007]
      - [0xCE0C, c, psxsdk/libcd/c_008]
      - [0xCE4C, c, psxsdk/libcd/c_009]
      - [0xCF10, c, psxsdk/libcd/c_010]
      - [0xCF30, c, psxsdk/libcd/c_011]
      - [0xDA90, c, psxsdk/libsnd/scsmvol]
      - [0xDAE0, c, psxsdk/libsnd/scssattr]
      - [0xDB74, c, psxsdk/libsnd/scssvol]
      - [0xDC70, c, psxsdk/libsnd/seqinit]
      - [0xE064, c, psxsdk/libsnd/seqread]
      - [0xFDBC, c, psxsdk/libsnd/adsr]
      - [0xFEA4, c, psxsdk/libsnd/next]
      - [0xFFAC, c, psxsdk/libsnd/seskoff]
      - [0xFFE8, c, psxsdk/libsnd/seskon]
      - [0x10034, c, psxsdk/libsnd/sscall]
      - [0x102A8, c, psxsdk/libsnd/cres]
      - [0x10584, c, psxsdk/libsnd/decre]
      - [0x10830, c, psxsdk/libsnd/pause]
      - [0x108D0, c, psxsdk/libsnd/play]
      - [0x108FC, c, psxsdk/libsnd/replay]
      - [0x10964, c, psxsdk/libsnd/ssclose]
      - [0x10B28, c, psxsdk/libsnd/ssinit]
      - [0x10C10, c, psxsdk/libsnd/ssinit_h]
      - [0x10C40, c, psxsdk/libsnd/ssquit]
      - [0x10C60, c, psxsdk/libsnd/ssstart]
      - [0x10F98, c, psxsdk/libsnd/sstick]
      - [0x11104, c, psxsdk/libsnd/ssend]
      - [0x111B4, c, psxsdk/libsnd/sstable]
      - [0x11394, c, psxsdk/libsnd/ssplay]
      - [0x11504, c, psxsdk/libsnd/ssvol]
      - [0x115D8, c, psxsdk/libsnd/stop]
      - [0x11798, c, psxsdk/libsnd/tempo]
      - [0x11974, c, psxsdk/libsnd/vs_mono]
      - [0x11998, c, psxsdk/libsnd/vs_srv]
      - [0x119D0, c, psxsdk/libsnd/vs_vab]
      - [0x11AAC, c, psxsdk/libsnd/vs_vfb]
      - [0x11B1C, c, psxsdk/libsnd/vs_vh]
      - [0x11FC0, c, psxsdk/libsnd/vs_vtb]
      - [0x12080, c, psxsdk/libsnd/vs_vtbp]
      - [0x121E0, c, psxsdk/libsnd/vs_vtc]
      - [0x1220C, c, psxsdk/libsnd/vm_doff]
      - [0x1221C, c, psxsdk/libsnd/vm_don]
      - [0x12230, c, psxsdk/libsnd/ut_gpa]
      - [0x12338, c, psxsdk/libsnd/vm_vsu]
      - [0x123FC, c, psxsdk/libsnd/ut_gva]
      - [0x12638, c, psxsdk/libsnd/ut_rev]
      - [0x126EC, c, psxsdk/libsnd/ut_ron]
      - [0x1270C, c, psxsdk/libsnd/ut_roff]
      - [0x1272C, c, psxsdk/libsnd/ut_rfb]
      - [0x1276C, c, psxsdk/libsnd/ut_rdep]
      - [0x12804, c, psxsdk/libsnd/ut_rdel]
      - [0x12844, c, psxsdk/libsnd/ut_sva]
      - [0x12A0C, c, psxsdk/libsnd/vmanager]
      - [0x1785C, c, psxsdk/libspu/s_i]
      - [0x1787C, c, psxsdk/libspu/s_ini]
      - [0x179C8, c, psxsdk/libapi/a08]
      - [0x179D8, c, psxsdk/libapi/a12]
      - [0x179E8, c, psxsdk/libspu/spu]
      - [0x18B04, c, psxsdk/libspu/s_dcb]
      - [0x18B28, c, psxsdk/libspu/s_q]
      - [0x18BA4, c, psxsdk/libapi/a09]
      - [0x18BB4, c, psxsdk/libapi/a13]
      - [0x18BC4, c, psxsdk/libspu/s_m_init]
      - [0x18C18, c, psxsdk/libspu/s_m_m]
      - [0x191E0, c, psxsdk/libspu/s_m_wsa]
      - [0x197F4, c, psxsdk/libspu/s_m_f]
      - [0x19870, c, psxsdk/libspu/s_snv]
      - [0x19894, c, psxsdk/libspu/s_sav]
      - [0x19948, c, psxsdk/libspu/s_sr]
      - [0x19A18, c, psxsdk/libspu/s_m_util]
      - [0x19B00, c, psxsdk/libspu/s_srmp]
      - [0x1A4E0, c, psxsdk/libspu/s_crwa]
      - [0x1A67C, c, psxsdk/libapi/a10]
      - [0x1A68C, c, psxsdk/libspu/s_si]
      - [0x1A7BC, c, psxsdk/libspu/s_sic]
      - [0x1A800, c, psxsdk/libspu/s_cb]
      - [0x1A824, c, psxsdk/libspu/s_sk]
      - [0x1A89C, c, psxsdk/libspu/s_sva]
      - [0x1AF20, c, psxsdk/libspu/s_gva]
      - [0x1B2F8, c, psxsdk/libspu/s_r]
      - [0x1B358, c, psxsdk/libspu/s_w]
      - [0x1B3B8, c, psxsdk/libspu/s_stsa]
      - [0x1B3F4, c, psxsdk/libspu/s_stm]
      - [0x1B428, c, psxsdk/libspu/s_wp]
      - [0x1B4B4, c, psxsdk/libspu/s_itc]
      - [0x1B55C, c, psxsdk/libapi/a11]
      - [0x1B56C, c, psxsdk/libspu/s_it]
      - [0x1B5A8, c, psxsdk/libspu/s_sca]
      - [0x1B93C, c, psxsdk/libspu/s_n2p]
      - [0x1BB88, c, psxsdk/libspu/sr_gaks]
      - [0x1BCE0, data]
      - [0x1CAA8, .data, psxsdk/libetc/vsync]
      - [0x1CAB8, .data, psxsdk/libetc/intr]
      - [0x1DB54, .data, psxsdk/libetc/intr_vb]
      - [0x1DB7C, .data, psxsdk/libetc/intr_dma]
      - [0x1DBA4, .data, psxsdk/libetc/vmode]
      - [0x1DBA8, data]
      - [0x235E8, .data, psxsdk/libcd/c_002]
      - [0x235F8, .data, psxsdk/libcd/c_003]
      - [0x23608, .data, psxsdk/libcd/c_004]
      - [0x23618, .data, psxsdk/libcd/c_005]
      - [0x23628, .data, psxsdk/libcd/c_007]
      - [0x23638, .data, psxsdk/libcd/c_008]
      - [0x23648, .data, psxsdk/libcd/c_009]
      - [0x23658, .data, psxsdk/libcd/c_010]
      - [0x23668, .data, psxsdk/libcd/c_011]
      - [0x23678, data]
      - [0x23708, .data, psxsdk/libsnd/vs_vtbp] # needs to be ram address + 0x800
      - [0x23710, data]
      - [0x29A5C, .data, psxsdk/libetc/pad]
      - [0x29A60, data]
      - [0x2BE84, bss]
      - [0x63880, .bss, psxsdk/libetc/pad]
      - [0x63884, bss]
  - [0x89800]

