options:
  platform:     psx
  basename:     stsel
  base_path:    ..
  target_path:  iso/ST/SEL/SEL.BIN
  asm_path:     asm/st/sel
  asset_path:   assets/st/sel
  src_path:     src/st/sel
  compiler:     GCC
  symbol_addrs_path:    config/generated.symbols.stsel.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.stsel.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.stsel.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
segments:
  - name: stsel
    type: code
    start: 0x00000000
    vram:  0x80180000
    subalign: 2
    subsegments:
      - [0x0, .data, 2C048]
      - [0x40, data]
      - [0x176C0, rodata]
      - [0x276C0, .rodata, func_801AD260]
      - [0x276D8, rodata]
      - [0x27AD0, rodata]
      - [0x27B14, rodata]
      - [0x27B4C, rodata]
      - [0x27B98, rodata]
      - [0x27BB8, rodata]
      - [0x27BD8, rodata]
      - [0x27BF8, rodata]
      - [0x27C18, rodata]
      - [0x27C30, rodata]
      - [0x27C48, rodata]
      - [0x27C60, rodata]
      - [0x27C78, rodata]
      - [0x27C98, rodata]
      - [0x27CB0, .rodata, func_801B60D4]
      - [0x27CD4, rodata]
      - [0x27CF4, rodata]
      - [0x27D14, rodata]
      - [0x27D90, rodata] # func_801B8A8C
      - [0x27DA8, rodata] # func_801B8A8C
      - [0x27DC0, rodata] # func_801B8A8C
      - [0x27DD4, rodata]
      - [0x2C048, c, 2C048]
      - [0x2D260, c, func_801AD260]
      - [0x2D490, c, 2D490]
      - [0x360D4, c, func_801B60D4]
      - [0x3642C, c, 3642C]
      - [0x38A8C, c, func_801B8A8C]
      - [0x38D24, c, 38D24]
      - [0x3AEE4, sbss]
  - [0x56B28]
