options:
  platform: psx
  basename: bomar
  base_path: ..
  build_path: build/us
  target_path: disks/us/BOSS/MAR/MAR.BIN
  asm_path: asm/us/boss/mar
  asset_path: assets/boss/mar
  src_path: src/boss/mar
  ld_script_path: build/us/bomar.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.bomar.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.bomar.txt
  undefined_syms_auto_path: config/undefined_syms_auto.us.bomar.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  extensions_path: tools/splat_ext
  symbol_name_format: us_$VRAM
  disassemble_all: true
  section_order:
    - .data
    - .rodata
    - .text
    - .sbss
    - .bss
  ld_bss_is_noload: false
  disasm_unknown: true
sha1: 4cd6c07959db859f5bc19390a283f34df4bf1619
segments:
  - name: bomar
    type: code
    start: 0
    vram: 0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .data, header]
      - [0x8C, .data, header] # palette definitions
      - [0xCC, .data, header] # layers
      - [0xF4, .data, header] # graphics banks
      - [0x168, .data, e_laydef] # layout entries header
      - [0x310, .data, e_init]
      - [0x4E8, .data, st_debug]
      - [0x568, .data, e_breakable]
      - [0x5D4, data]
      - [0x680, .data, cutscene]
      - [0x688, data]
      - [0x744, .data, d_prize_drops]
      - [0x764, .data, st_update]
      - [0x790, .data, collision]
      - [0xB50, .data, e_red_door]
      - [0xB68, .data, st_common]
      - [0xD68, .data, e_collect]
      - [0x1058, .data, e_misc]
      - [0x1174, .data, e_particles]
      - [0x11F4, .data, e_room_fg]
      - [0x1280, data, clock_room]
      - [0x12EC, .data, rooms]
      - [0x1308, .data, e_life_up]
      - [0x135C, .data, e_layout] # layout entries data
      - [0x1424, .data, cutscene_data]
      - [0x15DC, data]
      - [0x15F0, raw, cutscene_alucard]
      - [0x2370, raw, cutscene_maria]
      - [0x30F0, cmp, D_801830F0]
      - [0x4220, cmp, D_80184220]
      - [0x4EE0, pal, D_80184EE0]
      - [0x4FE0, pal, D_80184FE0] # unused
      - [0x50E0, pal, D_801850E0]
      - [0x51E0, pal, D_801851E0] # unused
      - [0x52E0, pal, D_801852E0]
      - [0x5300, .data, tile_data] # tile data
      - [0x5700, .data, tile_data] # tile definitions
      - [0x9710, .data, sprites]
      - [0xA9D4, .rodata, cutscene] # actor names
      - [0xA9EC, .rodata, cutscene]
      - [0xAA70, .rodata, CA94]
      - [0xAAB0, .rodata, e_red_door]
      - [0xAAC8, .rodata, e_collect]
      - [0xAB50, .rodata, e_misc]
      - [0xAB9C, .rodata, e_stage_name]
      - [0xABD0, .rodata, clock_room]
      - [0xABE8, .rodata, prim_helpers]
      - [0xABF0, .rodata, e_life_up]
      - [0xAC0C, c, st_debug]
      - [0xAE90, c, e_breakable]
      - [0xAFC4, c, cutscene]
      - [0xCA94, c]
      - [0xCF70, c, st_update]
      - [0xD3A4, c, collision]
      - [0xEB60, c, create_entity]
      - [0xF6D8, c, e_red_door]
      - [0x10388, c, st_common]
      - [0x11838, c, e_collect]
      - [0x12DA4, c, blit_char]
      - [0x13054, c, e_misc]
      - [0x16538, c, e_stage_name]
      - [0x1738C, c, e_particles]
      - [0x17BD0, c, e_room_fg]
      - [0x17CBC, c, popup]
      - [0x17FEC, c, clock_room]
      - [0x1911C, c, prim_helpers]
      - [0x1994C, c, e_life_up]
      - [0x1A200, .bss, unk]
      - [0x1A260, .bss, create_entity]
      - [0x1A270, .bss, bss]
      - [0x1AF30, .bss, e_collect]
  - [0x1AF70]
