options:
  platform: psp
  basename: dra
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/wrp.bin
  asm_path: asm/pspeu/st/wrp_psp
  asset_path: assets/st/wrp
  src_path: src/st
  ld_script_path: build/pspeu/stwrp.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.stwrp.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.pspeu.stwrp.txt
  undefined_syms_auto_path: config/undefined_syms_auto.pspeu.stwrp.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: yes
  asm_jtbl_label_macro: jlabel
  symbol_name_format: psp_$VRAM
  nonmatchings_path: psp
  disassemble_all: true
  section_order:
    - ".text"
    - ".data"
    - ".rodata"
    - ".bss"
  ld_bss_is_noload: True
  disasm_unknown: True
  global_vram_start: 0x08000000
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: 0584ddb3ba1afce61592d43497212fcb8ebf797b
segments:
  - [0x0, bin, mwo_header]
  - name: stwrp
    type: code
    start: 0x00000080
    vram: 0x09237700
    bss_size: 0x1180
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, wrp/create_entity]
      - [0x1028, c, wrp/e_stage_name]
      - [0x1EA8, c, wrp/e_red_door]
      - [0x31B0, c, wrp/st_update]
      - [0x36E8, c, wrp_psp/e_particles_maria1]
      - [0x3C70, c, wrp_psp/e_particles_maria2]
      - [0x4100, c, wrp/e_particles]
      - [0x4C78, c, wrp_psp/blit_char]
      - [0x5308, c, wrp_psp/e_collect]
      - [0x8580, c, wrp_psp/e_misc]
      - [0x95D0, c, wrp/collision]
      - [0xB7A8, c, wrp/popup]
      - [0xBDA0, c, wrp/e_room_fg]
      - [0xBEB8, c, wrp/st_common]
      - [0xC9A0, c, wrp/prim_helpers]
      - [0xD0E0, c, wrp_psp/st_init_wrp]
      - [0xD1B8, c, wrp/e_breakable]
      - [0xD338, c, wrp/st_debug]
      - [0xD6A8, c, wrp/warp]
      - [0xEA00, .data, wrp/e_red_door]
      - [0xEA18, .data, wrp/st_update]
      - [0xEA48, .data, wrp/e_particles]
      - [0xEAC8, .data, wrp_psp/e_collect]
      - [0xF010, .data, wrp_psp/e_misc]
      - [0xF060, .data, wrp/collision]
      - [0xF438, .data, wrp/e_room_fg]
      - [0xF4D8, data] # WRP_spriteBanks
      - [0xF5F8, data] # WRP_rooms_layers
      - [0xF700, data] # WRP_cluts
      - [0xF708, .data, wrp_psp/graphics_banks]
      - [0xF790, .data, wrp_psp/e_init]
      - [0xF8A0, data] # WRP_rooms
      - [0xF920, .data, wrp/e_breakable]
      - [0xF970, data] # [0xF970, cmpgfx, stage_title_jp, 128, 128, 4]
      - [0xFCB8, data] # [0xFCB8, cmpgfx, stage_placeholder, 128, 128, 4]
      - [0x10260, data] # D_psp_092478E0
      - [0x102C0, data] # D_psp_09247940
      - [0x104C0, data] # D_psp_09247B40
      - [0x106C0, data] # D_psp_09247D40
      - [0x108C0, data] # D_psp_09247F40
      - [0x10AC0, data] # tile data
      - [0x10EC0, data] # tile definitions
      - [0x142E0, .data, wrp_psp/header]
      - [0x14320, .data, wrp_psp/st_debug_data]
      - [0x14360, .data, wrp/st_debug]
      - [0x14430, .data, wrp/warp]
      - [0x14480, .rodata, wrp/e_red_door]
      - [0x14498, .rodata, wrp_psp/e_collect]
      - [0x144F8, .rodata, wrp/warp]
      - [0x14500, .bss, wrp/create_entity]
      - [0x14520, .bss, wrp_psp/e_collect]
      - [0x14560, .bss, wrp_psp/bss]
  - [0x14580]
