options:
  platform:     psx
  basename:     stnp3
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/ST/NP3/NP3.BIN
  asm_path:     asm/us/st/np3
  asset_path:   assets/st/np3
  src_path:     src/st/np3
  compiler:     GCC
  symbol_addrs_path:    config/generated.symbols.us.stnp3.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.stnp3.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.stnp3.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  extensions_path: tools/splat_ext
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
segments:
  - name: stnp3
    type: code
    start: 0x00000000
    vram:  0x80180000
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0xE50, rodata]
      - [0x10C0, rodata]
      - [0x1300, rodata]
      - [0x1520, rodata]
      - [0x22B0, rodata]
      - [0x23D0, rodata]
      - [0x2400, rodata]
      - [0x2440, rodata]
      - [0x2720, rodata]
      - [0x2740, rodata]
      - [0x2A20, rodata]
      - [0x2B00, rodata]
      - [0x3010, rodata]
      - [0x33A0, rodata]
      - [0x3530, rodata]
      - [0x3570, rodata]
      - [0x3580, rodata]
      - [0x3720, rodata]
      - [0x3760, rodata]
      - [0x3A7C, roomdef, g_Rooms]
      - [0x3B68, rodata]
      - [0x31EA0, rodata]
      - [0x31FB0, rodata]
      - [0x3208C, .rodata, 4997C]
      - [0x320A0, rodata]
      - [0x32360, rodata]
      - [0x3246C, c]
      - [0x4997C, c, 4997C]
      - [0x52768, data]
  - [0x53434]
