options:
  platform:     psx
  basename:     strwrp
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/ST/RWRP/RWRP.BIN
  asm_path:     asm/us/st/rwrp
  asset_path:   assets/st/rwrp
  src_path:     src/st/rwrp
  compiler:     GCC
  symbol_addrs_path:    config/generated.symbols.us.strwrp.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.strwrp.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.strwrp.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  extensions_path: tools/splat_ext
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
segments:
  - name: strwrp
    type: code
    start: 0x00000000
    vram:  0x80180000
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x4E0, rodata]
      - [0x5E0, rodata]
      - [0x10A0, rodata]
      - [0x11AC, roomdef, g_Rooms]
      - [0x1228, rodata]
      - [0x8C88, rodata]
      - [0x8D78, rodata]
      - [0x8DF0, c]
      - [0x15A20, data]
  - [0x166E8]
