options:
  platform: psx
  basename: stno4
  base_path: ..
  build_path: build/us
  target_path: disks/us/ST/NO4/NO4.BIN
  asm_path: asm/us/st/no4
  asset_path: assets/st/no4
  src_path: src/st/no4
  ld_script_path: build/us/stno4.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.stno4.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.stno4.txt
  undefined_syms_auto_path: config/undefined_syms_auto.us.stno4.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: us_$VRAM
  section_order:
    - .data
    - .rodata
    - .text
    - .bss
    - .sbss
  ld_bss_is_noload: false
  disasm_unknown: true
  disassemble_all: true
  global_vram_start: 0x80010000
  ld_generate_symbol_per_data_segment: true
sha1: bd0c8f0dd19fb736c483abc23254aefdeba7904f
segments:
  - name: stno4
    type: code
    start: 0
    vram:  0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, data]
      - [0xA0C, .data, e_init]
      - [0xCF4, .data, background_block_init]
      - [0xD2C, .data, e_red_door_tiles]
      - [0xD5C, .data, e_lock_camera]
      - [0xDDC, .data, e_breakable]
      - [0xECC, data] # additional water_effects data
      - [0x1108, data]
      - [0x1678, .data, e_ferryman]
      - [0x1804, data]
      - [0x1880, .data, e_secrets]
      - [0x18F0, .data, e_bat]
      - [0x1928, data] # NO4_PrizeDrops
      - [0x1974, .data, e_killer_fish]
      - [0x19D0, .data, cutscene]
      - [0x19D4, .data, st_update]
      - [0x1A20, .data, collision]
      - [0x1DE0, .data, e_red_door]
      - [0x1DF8, .data, st_common]
      - [0x1FF8, .data, e_collect]
      - [0x234C, .data, e_misc]
      - [0x2404, .data, e_particles]
      - [0x2484, .data, e_room_fg]
      - [0x2510, .data, water_effects]
      - [0x25CC, .data, e_toad]
      - [0x2688, .data, e_frog]
      - [0x2700, .data, e_fishhead]
      - [0x27F0, .data, e_frozen_shade]
      - [0x2B10, .data, e_spear_guard]
      - [0x2DE0, .data, e_bone_archer]
      - [0x2F54, .data, e_skeleton_ape]
      - [0x30F0, data]
      - [0x5354, .data, cutscene_data]
      - [0x5400, data]
      - [0x40980, .rodata, e_breakable]
      - [0x409A0, .rodata, first_c_file]
      - [0x409B8, .rodata, e_ferryman]
      - [0x40A30, .rodata, C82B8]
      - [0x40A48, .rodata, e_bat]
      - [0x40A5C, .rodata, e_killer_fish]
      - [0x40A70, .rodata, cutscene]
      - [0x40B04, .rodata, e_red_door]
      - [0x40B1C, .rodata, e_collect]
      - [0x40BF0, .rodata, e_stage_name]
      - [0x40C24, .rodata, e_toad]
      - [0x40C40, .rodata, e_frog]
      - [0x40C6C, .rodata, e_fishhead]
      - [0x40C84, .rodata, e_frozen_shade]
      - [0x40CB8, .rodata, e_spear_guard]
      - [0x40CEC, .rodata, e_bone_archer]
      - [0x40CF8, .rodata, e_skeleton_ape]
      - [0x40D3C, .rodata, prim_helpers]
      - [0x40D44, c, e_room_bg]
      - [0x40E0C, c, e_lock_camera]
      - [0x40FC8, c, e_breakable]
      - [0x412B0, c, first_c_file]
      - [0x459E0, c, e_ferryman]
      - [0x48248, c, C82B8]
      - [0x486F4, c, e_secrets]
      - [0x48E4C, c, e_bat]
      - [0x49130, c, e_killer_fish]
      - [0x49538, c, cutscene]
      - [0x4A5F0, c, st_update]
      - [0x4AA24, c, collision]
      - [0x4C1E0, c, create_entity]
      - [0x4CD58, c, e_red_door]
      - [0x4DA08, c, st_common]
      - [0x4EEB8, c, e_collect]
      - [0x51828, c, e_misc]
      - [0x53BC4, c, e_stage_name]
      - [0x54A18, c, e_particles]
      - [0x5525C, c, e_room_fg]
      - [0x55348, c, popup]
      - [0x55678, c, water_effects]
      - [0x5798C, c, e_toad]
      - [0x57FAC, c, e_frog]
      - [0x585A4, c, e_fishhead]
      - [0x59560, c, e_frozen_shade]
      - [0x5BCDC, c, e_spear_guard]
      - [0x5CA9C, c, e_bone_archer]
      - [0x5D688, c, e_skeleton_ape]
      - [0x5E2E0, c, prim_helpers]
      - [0x5EB10, bss]
      - [0x5EB70, .bss, create_entity]
      - [0x5EB80, bss]
      - [0x5F780, .bss, cutscene]
      - [0x5F81C, .bss, e_collect]
  - [0x5F85C]
