options:
  platform: psp
  basename: stcat
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/cat.bin
  asm_path: asm/pspeu/st/cat_psp
  asset_path: assets/st/cat
  src_path: src/st
  ld_script_path: build/pspeu/stcat.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.stcat.txt
  undefined_funcs_auto_path: build/pspeu/config/undefined_funcs_auto.pspeu.stcat.txt
  undefined_syms_auto_path: build/pspeu/config/undefined_syms_auto.pspeu.stcat.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  nonmatchings_path: nonmatchings
  disassemble_all: true
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  global_vram_start: 0x08000000
  ld_generate_symbol_per_data_segment: true
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: cf9e412d9f72698fefa72e53a19c54f0a1fb4815
segments:
  - [0x0, bin, mwo_header]
  - name: stcat
    type: code
    start: 0x80
    vram: 0x09237700
    bss_start_address: 0x09297000
    bss_size: 0x1000
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, cat/create_entity]
      - [0x1028, c, cat/e_stage_name]
      - [0x1F28, c, cat/e_discus_lord]
      - [0x4820, c, cat/e_red_door]
      - [0x5B28, c, cat/st_update]
      - [0x6060, c, cat/e_grave_keeper]
      - [0x7540, c, cat/e_tombstone]
      - [0x7870, c, cat/e_particles]
      - [0x8E00, c, cat/e_bone_ark]
      - [0xD0D0, c, cat/e_collect]
      - [0x11320, c, cat/e_misc]
      - [0x12AC8, c, cat/st_collision]
      - [0x14CA0, c, cat/popup]
      - [0x15298, c, cat/e_room_fg]
      - [0x153B0, c, cat/e_blood_skeleton]
      - [0x158F8, c, cat/e_slime]
      - [0x18618, c, cat/e_lossoth]
      - [0x1A9C0, c, cat/st_common]
      - [0x1C308, c, cat/e_lava_glow]
      - [0x1C4B0, c, cat/prim_helpers]
      - [0x1CD50, c, cat/en_gremlin]
      - [0x1D8D0, c, cat/e_hellfire_beast]
      - [0x20A38, c, cat/en_thornweed_corpseweed]
      - [0x22740, c, cat/e_wereskeleton]
      - [0x23A98, c, cat_psp/unk_23A98]
      - [0x26C48, c, cat_psp/st_init_psp]
      - [0x26FF8, c, cat/e_breakable]
      - [0x273C0, c, cat_psp/unk_273C0]
      - [0x288D0, c, cat/e_room_bg]
      - [0x289B0, c, cat/e_lock_camera]
      - [0x28C10, c, cat_psp/unk_28C10]
      - [0x296D8, c, cat/e_spike_room_light_switch]
      - [0x2A0C8, c, cat_psp/unk_2A0C8]
      - [0x2A398, c, cat/e_spike_room]
      - [0x2A9F0, c, cat/e_spikes]
      - [0x2B4D8, c, cat/e_elevator]
      - [0x2B980, .data, cat/e_stage_name]
      - [0x2C238, .data, cat/e_discus_lord]
      - [0x2C370, .data, cat/e_red_door]
      - [0x2C388, .data, cat/st_update]
      - [0x2C3B8, .data, cat/e_grave_keeper]
      - [0x2C488, .data, cat/e_tombstone]
      - [0x2C498, .data, cat/e_particles]
      - [0x2C518, .data, cat/e_bone_ark]
      - [0x2C608, .data, cat/e_collect]
      - [0x2CB50, .data, cat/e_misc]
      - [0x2CBA0, .data, cat/st_collision]
      - [0x2CF78, .data, cat/e_room_fg]
      - [0x2D018, .data, cat/e_blood_skeleton]
      - [0x2D0D0, .data, cat/e_slime]
      - [0x2D110, .data, cat/e_lossoth]
      - [0x2D230, .data, cat/st_common]
      - [0x2D430, .data, cat/en_gremlin]
      - [0x2D490, .data, cat/e_hellfire_beast]
      - [0x2D590, .data, cat/en_thornweed_corpseweed]
      - [0x2D660, .data, cat/e_wereskeleton]
      - [0x2D7C0, data]
      - [0x32438, .data, cat/e_init]
      - [0x32818, data]
      - [0x36308, .data, cat/e_breakable]
      - [0x36448, data]
      - [0x5F4B0, .data, cat/header]
      - [0x5F4E0, data]
      - [0x5F560, .data, cat_psp/unk_273C0]
      - [0x5F570, data]
      - [0x5F628, .data, cat/e_lock_camera]
      - [0x5F6A0, data]
      - [0x5F708, .data, cat_psp/unk_28C10]
      - [0x5F718, .data, cat/e_spike_room]
      - [0x5F728, .data, cat/e_spikes]
      - [0x5F748, .data, cat/e_elevator]
      - [0x5F780, .rodata, cat/e_red_door]
      - [0x5F798, .rodata, cat/e_grave_keeper]
      - [0x5F7D0, .rodata, cat/e_bone_ark]
      - [0x5F810, .rodata, cat/e_collect]
      - [0x5F870, .rodata, cat/e_slime]
      - [0x5F8C8, .rodata, cat/e_lossoth]
      - [0x5F8F0, .rodata, cat/en_thornweed_corpseweed]
      - [0x5F930, .rodata, cat_psp/unk_28C10]
      - [0x5F950, .rodata, cat/e_spike_room_light_switch]
      - [0x5F980, .bss, cat/create_entity]
      - [0x5F9A0, .bss, cat/e_collect]
      - [0x5FA00, .bss, cat/e_lossoth]
      - [0x5FA08, bss, 5FA08]
      - [0x5FAB8, .bss, cat_psp/st_init_psp]
      - [0x5FCD8, .bss, cat/e_breakable]
      - [0x5FCF0, bss, 5FCF0]
      - [0x608F0, .bss, cat/e_lock_camera]
      - [0x608F8, bss, 608F8]
      - [0x60900, .bss, cat/e_spike_room]
  - [0x60980]
