options:
  platform: psp
  basename: w0_000
  base_path: ..
  build_path: build/pspeu/weapon0
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/w0_000.bin
  asm_path: asm/pspeu/weapon/w0_000
  asset_path: assets/weapon
  src_path: src/weapon
  ld_script_path: build/pspeu/w0_000.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.weapon.txt
    - config/symbols.pspeu.w0_000.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.pspeu.w0_000.txt
  undefined_syms_auto_path: config/undefined_syms_auto.pspeu.w0_000.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: pspeu_$VRAM
  section_order:
    - .text
    - .data
    - .rodata
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  disassemble_all: true
  global_vram_start: 0x8000000
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
sha1: bc20b2683492352905317f0634b4db6b84f9985d
segments:
  - [0x0, bin, mwo_header]
  - name: w0_000
    type: code
    start: 0x80
    vram:  0x092F2E80
    bss_size: 0x80
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, w_000]
      - [0x700, .data, w_000]
      - {start: 0x1980, type: bss, vram: 0x92F4780}
  - [0x1980]
