options:
  platform:     psp
  basename:     dra
  base_path:    ..
  build_path:   build/pspeu
  target_path:  disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/wrp.bin
  asm_path:     asm/pspeu/st/wrp_psp
  asset_path:   assets/st/wrp
  src_path:     src/st
  ld_script_path: build/pspeu/stwrp.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.stwrp.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.pspeu.stwrp.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.pspeu.stwrp.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  asm_jtbl_label_macro: jlabel
  symbol_name_format : psp_$VRAM
  nonmatchings_path: psp
  section_order:
    - ".text"
    - ".data"
    - ".rodata"
    - ".bss"
  ld_bss_is_noload: True
  disasm_unknown: True
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
    .include "macro.inc"
segments:
  - [0x0, bin, mwo_header]
  - name: stwrp
    type: code
    start: 0x00000080
    vram:  0x09237700
    bss_size: 0x1180
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, wrp_psp/80]
      - [0x4D0, c, wrp_psp/4D0]
      - [0x31F0, c, wrp_psp/31F0]
      - [0x3C70, c, wrp_psp/3C70]
      - [0x4100, c, wrp_psp/4100]
      - [0x5600, c, wrp_psp/5600]
      - [0x5AB0, c, wrp_psp/5AB0]
      - [0x6BF0, c, wrp_psp/6BF0]
      - [0x8580, c, wrp_psp/8580]
      - [0x95D0, c, wrp_psp/95D0]
      - [0xBDA0, c, wrp_psp/BDA0]
      - [0xBF50, c, wrp_psp/BF50]
      - [0xC3F0, c, wrp_psp/C3F0]
      - [0xD010, c, wrp_psp/D010]
      - [0xD0E0, c, wrp_psp/st_init_wrp]
      - [0xD1B8, c, wrp_psp/e_breakable]
      - [0xD338, c, wrp_psp/D338]
      - [0xE980, data]
      - [0x14480, data] # rodata?
      - {type: bss, vram: 0x924BC00}
  - [0x14580]
