options:
  platform:     psx
  basename:     stnp3
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/ST/NP3/NP3.BIN
  asm_path:     asm/us/st/np3
  asset_path:   assets/st/np3
  src_path:     src/st/np3
  ld_script_path: build/us/stnp3.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.stnp3.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.stnp3.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.stnp3.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  asm_jtbl_label_macro: jlabel
  extensions_path: tools/splat_ext
  disassemble_all: True
  section_order:
    - ".data"
    - ".rodata"
    - ".text"
    - ".bss"
    - ".sbss"
segments:
  - name: stnp3
    type: code
    start: 0x00000000
    vram:  0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, .data, header]
      - [0x1D0, .data, header] # layers
      - [0x558, data]
      - [0x728, .data, e_laydef] # layout entries header
      - [0x8D0, .data, e_init]
      - [0xD98, .data, st_debug]
      - [0xE18, .data, e_breakable]
      - [0xE78, .data, 32830]
      - [0xF0C, data]
      - [0x10C0, data]
      - [0x1300, data]
      - [0x14B4, .data, gaibon]
      - [0x1618, data, d_prize_drops]
      - [0x164C, .data, st_update]
      - [0x1678, .data, collision]
      - [0x1A38, .data, e_red_door]
      - [0x1A50, .data, st_common]
      - [0x1C50, .data, e_collect]
      - [0x1F40, .data, e_misc] # EntityRelicOrb
      - [0x205C, data]
      - [0x22B0, data]
      - [0x23D0, data]
      - [0x2400, data]
      - [0x2440, data]
      - [0x2460, .data, e_bone_scimitar]
      - [0x2554, data]
      - [0x25D4, .data, e_bloody_zombie]
      - [0x26CC, data]
      - [0x2720, data]
      - [0x2740, data]
      - [0x2A20, data]
      - [0x2B00, data]
      - [0x3010, data]
      - [0x33A0, data]
      - [0x3530, data]
      - [0x3570, data]
      - [0x3580, data]
      - [0x3720, data]
      - [0x3760, data]
      - [0x3A7C, .data, rooms]
      - [0x3B68, .data, e_layout] # layout entries data
      - [0x49E0, data]
      - [0x168F4, .data, tile_data] # tile data
      - [0x21CF4, .data, tile_data] # tile definitions
      - [0x2A124, .data, sprites]
      - [0x31EA0, data]
      - [0x31EA8, .rodata, 32830] # EntityStairwayPiece
      - [0x31EBC, .rodata, 363FC] # func_801B63FC
      - [0x31ED0, .rodata, slogra] # EntitySlogra .rodata, 36990
      - [0x31EDC, .rodata, gaibon] # EntityGaibon .rodata, 36990
      - [0x31F00, .rodata, e_red_door] # EntityRedDoor
      - [0x31F68, .rodata, e_collect]
      - [0x31FA0, .rodata, e_misc] # EntityRelicOrb
      - [0x31FD8, .rodata, e_misc] # EntityMessageBox
      - [0x31FEC, .rodata, e_stage_name] # EntityStageNamePopup
      - [0x32020, .rodata, e_merman2] # EntityMerman2
      - [0x32044, .rodata, 48238] # EntityMerman
      - [0x3206C, .rodata, e_bone_scimitar] # EntityBoneScimitar data
      - [0x3208C, .rodata, 4997C] # EntityBat
      - [0x320A0, .rodata, 49BC8] # EntityZombie
      - [0x320B4, .rodata, e_bloody_zombie] # EntityBloodyZombie data
      - [0x320DC, .rodata, 4B018] # Shared charal string for owl and owl knight
      - [0x320EC, .rodata, 4B018] # EntityOwl
      - [0x3214C, .rodata, 4B018] # EntityOwlKnight
      - [0x321EC, .rodata, 4D540] # Strings
      - [0x3224C, .rodata, 4E69C] # EntityHammer
      - [0x322CC, .rodata, 4E69C] # EntityGurkhaBodyParts
      - [0x322F8, .rodata, 4F5B8] # EntityGurkha
      - [0x32380, .rodata, 4F5B8] # EntityGurkhaSword
      - [0x323E4, .rodata, blade] # EntityBlade
      - [0x32464, .rodata, prim_helpers]
      - [0x3246C, c, st_debug]
      - [0x326FC, c, e_breakable]
      - [0x32830, c]
      - [0x363FC, c]
      - [0x36990, c, slogra]
      - [0x378BC, c, gaibon]
      - [0x390BC, c, st_update]
      - [0x394F0, c, collision]
      - [0x3ACAC, c, create_entity]
      - [0x3B824, c, e_red_door]
      - [0x3C4D4, c, st_common]
      - [0x3D984, c, e_collect]
      - [0x3EEF0, c, blit_char]
      - [0x3F1A0, c, e_misc]
      - [0x42860, c, e_stage_name]
      - [0x434E4, c, e_particles]
      - [0x43D28, c, e_room_fg]
      - [0x43E14, c, popup]
      - [0x44144, c, player_water_effect]
      - [0x44DCC, c, e_merman2] # Merman Entities
      - [0x48238, c] # Merman Entities (2)
      - [0x490E8, c, e_bone_scimitar] # EntityBoneScimitar
      - [0x4997C, c]
      - [0x49BC8, c]
      - [0x49F98, c, e_bloody_zombie] # EntityBloodyZombie
      - [0x4B018, c]
      - [0x4D540, c]
      - [0x4E69C, c]
      - [0x4F5B8, c]
      - [0x50A00, c, blade]
      - [0x51F38, c, prim_helpers]
      - [0x52768, .bss, create_entity]
      - [0x5277D, .bss, bss]
      - [0x53378, .bss, 4D540]
      - [0x533F4, .bss, e_collect]
  - [0x53434]
