options:
  platform:     psp
  basename:     dra
  base_path:    ..
  build_path:   build/pspeu
  target_path:  disks/pspeu/PSP_GAME/USRDIR/res/ps/PSPBIN/wrp.bin
  asm_path:     asm/pspeu/st/wrp_psp
  asset_path:   assets/st/wrp
  src_path:     src/st
  ld_script_path: build/pspeu/stwrp.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.stwrp.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.pspeu.stwrp.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.pspeu.stwrp.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  asm_jtbl_label_macro: jlabel
  symbol_name_format : psp_$VRAM
  nonmatchings_path: psp
  section_order:
    - ".text"
    - ".data"
    - ".rodata"
    - ".bss"
  ld_bss_is_noload: True
  disasm_unknown: True
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
    .include "macro.inc"
sha1: 0584ddb3ba1afce61592d43497212fcb8ebf797b

segments:
  - [0x0, bin, mwo_header]
  - name: stwrp
    type: code
    start: 0x00000080
    vram:  0x09237700
    bss_size: 0x1180
    align: 128
    subalign: 8
    subsegments:
      - [0x80, c, wrp_psp/create_entity]
      - [0x1028, c, wrp_psp/e_stage_name]
      - [0x1EA8, c, wrp_psp/e_red_door]
      - [0x31B0, c, wrp/st_update]
      - [0x36E8, c, wrp_psp/e_particles_maria1]
      - [0x3C70, c, wrp_psp/e_particles_maria2]
      - [0x4100, c, wrp/e_particles]
      - [0x4C78, c, wrp_psp/blit_char]
      - [0x5308, c, wrp_psp/e_collect]
      - [0x7448, c, wrp_psp/e_misc]
      - [0x95D0, c, wrp_psp/collision]
      - [0xB7A8, c, wrp/popup]
      - [0xBDA0, c, wrp/e_room_fg]
      - [0xBEB8, c, wrp/st_common]
      - [0xC9A0, c, wrp_psp/stage_name_new]
      - [0xCEA0, c, wrp_psp/prim_helpers]
      - [0xD0E0, c, wrp_psp/st_init_wrp]
      - [0xD1B8, c, wrp/e_breakable]
      - [0xD338, c, wrp/st_debug]
      - [0xD6A8, c, wrp_psp/warp]
      - [0xE980, data] # D_psp_09246000
      - [0xEA00, data] # g_eRedDoorUV
      - [0xEAD0, data] # D_psp_09246150
      - [0xEB00, data] # D_psp_09246180
      - [0xEB10, data] # D_psp_09246190
      - [0xEB20, data] # D_psp_092461A0
      - [0xEB30, data] # D_psp_092461B0
      - [0xEB40, data] # D_psp_092461C0
      - [0xEB50, data] # D_psp_092461D0
      - [0xEB80, data] # D_psp_09246200
      - [0xEBB0, data] # D_psp_09246230
      - [0xEBE0, data] # D_psp_09246260
      - [0xEC10, data] # D_psp_09246290
      - [0xEC40, data] # D_psp_092462C0
      - [0xEC60, data] # D_psp_092462E0
      - [0xEC90, data] # D_psp_09246310
      - [0xECF0, data] # D_psp_09246370
      - [0xED30, data] # D_psp_092463B0
      - [0xED60, data] # D_psp_092463E0
      - [0xEDE0, data] # D_psp_09246460
      - [0xEDF0, data] # D_psp_09246470
      - [0xEE00, data] # D_psp_09246480
      - [0xEE10, data] # D_psp_09246490
      - [0xEE20, data] # D_psp_092464A0
      - [0xEE50, data] # c_GoldPrizes
      - [0xEE80, data] # c_HeartPrizes
      - [0xEEA0, data] # D_psp_09246520
      - [0xEF40, data] # D_psp_092465C0
      - [0xEF60, data] # D_psp_092465E0
      - [0xEF70, data] # D_psp_092465F0
      - [0xEF80, data] # D_psp_09246600
      - [0xEF90, data] # D_psp_09246610
      - [0xEFA0, data] # D_psp_09246620
      - [0xEFB0, data] # D_psp_09246630
      - [0xEFC0, data] # D_psp_09246640
      - [0xEFD0, data] # D_psp_09246650
      - [0xEFE0, data] # D_psp_09246660
      - [0xF010, data] # D_80180FF8
      - [0xF020, data] # D_80181008
      - [0xF050, data] # D_80181038
      - [0xF060, data] # D_psp_092466E0
      - [0xF390, data] # D_psp_09246A10
      - [0xF3A0, data] # D_psp_09246A20
      - [0xF440, data] # D_psp_09246AC0
      - [0xF450, data] # D_psp_09246AD0
      - [0xF460, data] # D_80181134
      - [0xF700, data] # D_psp_09246D80
      - [0xF720, data] # D_psp_09246DA0
      - [0xF740, data] # D_psp_09246DC0
      - [0xF790, data] # g_eRedDoorTiles
      - [0xF7B0, data] # D_psp_09246E30
      - [0xF810, data] # g_eBreakableInit
      - [0xF820, data] # g_InitializeData0
      - [0xF830, data] # g_InitializeEntityData0
      - [0xF840, data] # D_psp_09246EC0
      - [0xF850, data] # D_psp_09246ED0
      - [0xF860, data] # D_80180488
      - [0xF870, data] # g_eInitGeneric2
      - [0xF880, data] # D_psp_09246F00
      - [0xF890, data] # D_801804C4
      - [0xF8A0, data] # D_psp_09246F20
      - [0xF920, .data, wrp_psp/create_entity] # D_psp_09246FA0
      - [0xF930, .data, wrp_psp/create_entity] # g_eBreakableAnimations
      - [0xF950, .data, wrp_psp/create_entity] # g_eBreakableHitboxes
      - [0xF970, data] # D_psp_09246FF0
      - [0x10260, data] # D_psp_092478E0
      - [0x102C0, data] # D_psp_09247940
      - [0x104C0, data] # D_psp_09247B40
      - [0x106C0, data] # D_psp_09247D40
      - [0x108C0, data] # D_psp_09247F40
      - [0x10AC0, data] # D_psp_09248140
      - [0x10CC0, data] # D_psp_09248340
      - [0x10EC0, data] # D_psp_09248540
      - [0x10FC0, data] # D_psp_09248640
      - [0x110C0, data] # D_psp_09248740
      - [0x111C0, data] # D_psp_09248840
      - [0x112C0, data] # D_psp_09248940
      - [0x112D0, data] # D_psp_09248950
      - [0x122D0, data] # D_psp_09249950
      - [0x132D0, data] # D_psp_0924A950
      - [0x142D0, data] # D_psp_0924B950
      - [0x142E0, data] # D_psp_0924B960
      - [0x14320, data] # D_psp_0924B9A0
      - [0x14360, data] # D_80180528
      - [0x14430, data] # D_psp_0924BAB0
      - [0x14440, data] # D_psp_0924BAC0
      - [0x14450, data] # D_psp_0924BAD0
      - [0x14460, data] # D_psp_0924BAE0
      - [0x14480, data] # rodata?
      - {type: bss, vram: 0x924BC00}
  - [0x14580]
