options:
  platform: psp
  basename: main
  base_path: ..
  build_path: build/pspeu
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/PS.ELF
  asm_path: asm/pspeu/main_psp
  asset_path: assets/main_psp
  src_path: src
  ld_script_path: build/pspeu/main.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.pspeu.txt
    - config/symbols.pspeu.main.txt
  create_undefined_funcs_auto: true
  undefined_funcs_auto_path: build/pspeu/undefined_funcs_auto.pspeu.main.txt
  undefined_syms_auto_path: build/pspeu/undefined_syms_auto.pspeu.main.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  rodata_string_guesser_level: 0
  add_set_gp_64: false
  asm_jtbl_label_macro: jlabel
  symbol_name_format: psp_$VRAM
  disassemble_all: true
  section_order:
    - .text
    - .rodata
    - .data
    - .bss
  ld_bss_is_noload: true
  disasm_unknown: true
  global_vram_start: 0x08000000
  asm_inc_header: |
    .set noat      /* allow manual use of $at */
    .set noreorder /* don't insert nops after branches */
  ld_generate_symbol_per_data_segment: true
sha1: a3bc73aaa3dc4b873c84a3c0b90e46366f5bbaa9
segments:
  - [0, bin, elf_header]
  - name: main
    type: code
    start: 0x16F4
    vram: 0x08900000
    bss_size: 0x72F150
    align: 4
    subalign: 4
    subsegments:
      - [0x16F4, asm, kernel_bridge/_open]
      - [0x178C, asm, kernel_bridge/_lseek]
      - [0x18BC, asm, kernel_bridge/_exit]
      - [0x1984, asm, kernel_bridge/_sbrk]
      - [0x1A74, asm, kernel_bridge/_read]
      - [0x1B18, asm, kernel_bridge/_write]
      - [0x1BBC, asm, kernel_bridge/_close]
      - [0x1C40, asm, kernel_bridge/_fstat]
      - [0x1C50, asm, kernel_bridge/isatty]
      - [0x1C58, asm, kernel_bridge/_rename]
      - [0x1C74, asm, kernel_bridge/func_psp_08900580]
      - [0x1C7C, asm, kernel_bridge/func_psp_08900588]
      - [0x1C84, asm, kernel_bridge/func_psp_08900590]
      - [0x1C8C, asm, kernel_bridge/func_psp_08900598]
      - [0x1C94, asm, kernel_bridge/_kill]
      - [0x1C9C, asm, kernel_bridge/_getpid]
      - [0x1CA4, asm, kernel_bridge/func_psp_089005B0]
      - [0x1CAC, asm, kernel_bridge/func_psp_089005B8]
      - [0x1CB4, asm, kernel_bridge/func_psp_089005C0]
      - [0x1CBC, asm, kernel_bridge/__free_heap]
      - [0x1CF8, asm, kernel_bridge/clock]
      - [0x1D14, asm, kernel_bridge/time]
      - [0x1D30, asm, kernel_bridge/_gettimeofday]
      - [0x1D4C, asm, kernel_bridge/_times]
      - [0x1D54, asm, kernel_bridge/sigfillset]
      - [0x1D64, asm, kernel_bridge/sigprocmask]
      - [0x1D6C, asm, libgu/sceGuInit]
      - [0x1EA8, asm, libgu/sceGuStart]
      - [0x2110, asm, libgu/sceGuFinishId]
      - [0x22B4, asm, libgu/sceGuSignalSync]
      - [0x2368, asm, libgu/sceGuCallList]
      - [0x241C, asm, libgu/sceGuSendList]
      - [0x24C0, asm, libgu/sceGuDispBuffer2]
      - [0x259C, asm, libgu/sceGuSwapBuffers]
      - [0x2664, asm, libgu/sceGuDrawBuffer]
      - [0x277C, asm, libgu/sceGuSetAllStatus]
      - [0x2828, asm, libgu/sceGuSetDither]
      - [0x2954, asm, libgu/sceGuEndObject]
      - [0x29F0, asm, libgu/sceGuPatchDivide]
      - [0x2A1C, asm, libgu/sceGuColorMaterial]
      - [0x2A44, asm, libgu/sceGuSpecular]
      - [0x2A70, asm, libgu/sceGuTexScale]
      - [0x2AB4, asm, libgu/_sceGuSetDebugFontCallback]
      - [0x2B20, asm, libgu/sceGuTerm]
      - [0x2B98, asm, libgu/sceGuFinish]
      - [0x2BB4, asm, libgu/sceGuGetMemory]
      - [0x2C04, asm, libgu/sceGuGetAlignedMemory]
      - [0x2C5C, asm, libgu/sceGuCheckList]
      - [0x2C74, asm, libgu/sceGuBeginPacket]
      - [0x2CB0, asm, libgu/sceGuEndPacket]
      - [0x2CC0, asm, libgu/sceGuSignal]
      - [0x2CF8, asm, libgu/sceGuSetCallback2]
      - [0x2D34, asm, libgu/sceGuBreak]
      - [0x2D54, asm, libgu/sceGuContinue]
      - [0x2D70, asm, libgu/sceGuCallMode]
      - [0x2D7C, asm, libgu/sceGuJumpList]
      - [0x2DC0, asm, libgu/sceGuSync]
      - [0x2E2C, asm, libgu/sceGuFlush]
      - [0x2E48, asm, libgu/sceGuDisplay]
      - [0x2EB4, asm, libgu/sceGuDispBuffer]
      - [0x2F28, asm, libgu/sceGuDrawBuffer2]
      - [0x2FE0, asm, libgu/sceGuDrawBufferList]
      - [0x3030, asm, libgu/sceGuDepthBuffer]
      - [0x3084, asm, libgu/sceGuEnable]
      - [0x30DC, asm, libgu/sceGuDisable]
      - [0x3138, asm, libgu/sceGuSetStatus]
      - [0x31C4, asm, libgu/sceGuGetStatus]
      - [0x31E8, c, main_psp/libgu]
      - [0x4484, asm, libgu/sceGupSetStatus]
      - [0x4690, asm, libgu/sceGupSetMatrix]
      - [0x4994, asm, libgu/sceGupDrawSprite]
      - [0x4B30, asm, libgu/sceGupClear]
      - [0x4E84, asm, libgu/sceGupDepthRange]
      - [0x4F2C, asm, libgu/sceGupDepthOffset]
      - [0x4FD8, asm, libgu/sceGupPatchPrim]
      - [0x5048, asm, libgu/sceGupModelColor]
      - [0x50AC, asm, libgu/sceGupMaterial]
      - [0x513C, asm, libgu/sceGupFrontFace]
      - [0x5168, asm, libgu/sceGupLight]
      - [0x51FC, asm, libgu/sceGupLightColor]
      - [0x5300, asm, libgu/sceGupTexMode]
      - [0x5344, asm, libgu/sceGupScissor]
      - [0x53C4, asm, libgu/sceGupShadeModel]
      - [0x53F0, asm, libgu/_sceGuCallbackSignal]
      - [0x546C, asm, libgu/_sceGuCallbackFinish]
      - [0x549C, asm, libgu/_sceGuResetGlobalVariables]
      - [0x55A8, asm, libgu/_sceGuUpdateStallAddr]
      - [0x5600, asm, libgu/sceGuDebugPrint]
      - [0x57E8, asm, libgu/sceGuDebugFlush]
      - [0x5A5C, asm, libgu/_sceGuDebugFontInit]
      - [0x5AB8, asm, libgu/_sceGuDebugSwapBuffer]
      - [0x5ACC, asm, libgu/_sceGuDebugDispBuffer]
      - [0x5AE8, asm, libgu/_sceGuDebugDrawBuffer]
      - [0x5AFC, asm, sceDisplaySetVblankCallback]
      - [0x5B64, asm, newlib/libm/math/e_rem_pio2/__ieee754_rem_pio2]
      - [0x622C, asm, newlib/libm/math/ef_atan2/__ieee754_atan2f]
      - [0x6478, asm, newlib/libm/math/k_cos/__kernel_cos]
      - [0x67E0, asm, newlib/libm/math/kf_rem_pio2/__kernel_rem_pio2]
      - [0x74B8, asm, newlib/libm/math/k_sin/__kernel_sin]
      - [0x7784, asm, newlib/libm/common/s_copysign/copysign]
      - [0x77A4, asm, newlib/libm/math/s_cos/cos]
      - [0x78B0, asm, newlib/libm/math/s_fabs/fabs]
      - [0x78BC, asm, newlib/libm/math/s_floor/floor]
      - [0x7AB8, asm, newlib/libm/common/s_isinf/isinf]
      - [0x7AEC, asm, newlib/libm/common/s_isnan/isnan]
      - [0x7B10, asm, newlib/libm/common/s_matherr/matherr]
      - [0x7B18, asm, newlib/libm/common/s_scalbn/scalbn]
      - [0x7CB8, asm, newlib/libm/math/s_sin/sin]
      - [0x7DC4, asm, newlib/libm/math/sf_atan/atanf]
      - [0x8060, asm, newlib/libm/math/sf_fabs/fabsf]
      - [0x8074, asm, newlib/libm/common/sf_isnanf/isnanf]
      - [0x8088, asm, newlib/libm/math/wf_atan2/atan2f]
      - [0x81CC, asm, newlib/libc/stdlib/abort/abort]
      - [0x81E4, asm, newlib/libc/stdlib/abs/abs]
      - [0x81F0, asm, newlib/libc/stdlib/atexit/atexit]
      - [0x82C4, asm, newlib/libc/stdlib/mallocr/_calloc_r]
      - [0x8380, asm, newlib/libc/reent/closer/_close_r]
      - [0x83DC, asm, newlib/libc/stdlib/dtoa/quorem]
      - [0x8624, asm, newlib/libc/stdlib/dtoa/_dtoa_r]
      - [0x9A70, asm, newlib/libc/reent/errno/__errno]
      - [0x9AB4, asm, newlib/libc/stdlib/exit/exit]
      - [0x9BB4, asm, newlib/libc/stdio/fflush/_fflush_r]
      - [0x9CB0, asm, newlib/libc/stdio/findfp/std]
      - [0x9D08, asm, newlib/libc/stdio/findfp/__sfmoreglue]
      - [0x9D7C, asm, newlib/libc/stdio/findfp/__sfp]
      - [0x9E60, asm, newlib/libc/stdio/findfp/_cleanup_r]
      - [0x9E80, asm, newlib/libc/stdio/findfp/_cleanup]
      - [0x9EA4, asm, newlib/libc/stdio/findfp/__sinit]
      - [0x9F28, asm, func_psp_08908834]
      - [0x9F5C, asm, newlib/libc/stdlib/mallocr/_free_r]
      - [0xA1D8, asm, newlib/libc/stdlib/mallocr/_malloc_trim_r]
      - [0xA314, asm, newlib/libc/reent/fstatr/_fstat_r]
      - [0xA378, asm, newlib/libc/stdio/fvwrite/__sfvwrite_r]
      - [0xA758, asm, newlib/libc/stdio/fwalk/_fwalk]
      - [0xA860, asm, newlib/libc/reent/getreent/__getreent]
      - [0xA888, asm, newlib/libc/stdlib/labs/labs]
      - [0xA894, asm, newlib/libc/locale/locale/_setlocale_r]
      - [0xA928, asm, newlib/libc/locale/locale/__locale_charset]
      - [0xA934, asm, newlib/libc/locale/locale/_localeconv_r]
      - [0xA940, asm, newlib/libc/locale/locale/setlocale]
      - [0xA980, asm, newlib/libc/locale/locale/localeconv]
      - [0xA9A4, asm, newlib/libc/reent/lseekr/_lseek_r]
      - [0xAA0C, asm, newlib/libc/stdio/makebuf/__smakebuf_r]
      - [0xAB74, asm, newlib/libc/stdlib/malign/memalign]
      - [0xABB4, asm, newlib/libc/stdlib/mallocr/_memalign_r]
      - [0xAD3C, asm, newlib/libc/stdlib/malloc/malloc]
      - [0xAD6C, asm, newlib/libc/stdlib/malloc/free]
      - [0xAD9C, asm, newlib/libc/stdlib/mallocr/malloc_extend_top]
      - [0xAFC4, asm, newlib/libc/stdlib/mallocr/_malloc_r]
      - [0xB50C, asm, newlib/libc/string/memchr/memchr]
      - [0xB5F4, asm, newlib/libc/string/memcmp/memcmp]
      - [0xB678, asm, newlib/libc/string/memcpy/memcpy]
      - [0xB7B4, asm, newlib/libc/string/memmove/memmove]
      - [0xBAB4, asm, newlib/libc/string/memset/memset]
      - [0xBB6C, asm, newlib/libc/stdlib/mlock/__malloc_lock]
      - [0xBBA8, asm, newlib/libc/stdlib/mlock/__malloc_unlock]
      - [0xBBF4, asm, _getmodreent]
      - [0xBD04, asm, _setmodreent]
      - [0xBE10, asm, _clrmodreent]
      - [0xBE94, asm, _reent_init_ptr]
      - [0xC074, asm, newlib/libc/stdlib/mprec/_Balloc]
      - [0xC12C, asm, newlib/libc/stdlib/mprec/_Bfree]
      - [0xC158, asm, newlib/libc/stdlib/mprec/__multadd]
      - [0xC268, asm, newlib/libc/stdlib/mprec/__s2b]
      - [0xC388, asm, newlib/libc/stdlib/mprec/__hi0bits]
      - [0xC410, asm, newlib/libc/stdlib/mprec/__lo0bits]
      - [0xC4C8, asm, newlib/libc/stdlib/mprec/__i2b]
      - [0xC4FC, asm, newlib/libc/stdlib/mprec/__multiply]
      - [0xC714, asm, newlib/libc/stdlib/mprec/__pow5mult]
      - [0xC82C, asm, newlib/libc/stdlib/mprec/__lshift]
      - [0xC964, asm, newlib/libc/stdlib/mprec/__mcmp]
      - [0xC9CC, asm, newlib/libc/stdlib/mprec/__mdiff]
      - [0xCB48, asm, newlib/libc/stdlib/mprec/__ulp]
      - [0xCBB8, asm, newlib/libc/stdlib/mprec/__b2d]
      - [0xCCDC, asm, newlib/libc/stdlib/mprec/__d2b]
      - [0xCE40, asm, newlib/libc/stdlib/mprec/__ratio]
      - [0xCEE0, asm, newlib/libc/stdlib/mprec/_mprec_log10]
      - [0xCF80, asm, newlib/libc/stdio/printf/_printf_r]
      - [0xCFC0, asm, newlib/libc/stdio/printf/printf]
      - [0xD010, asm, newlib/libc/stdlib/rand/srand]
      - [0xD048, asm, newlib/libc/stdlib/rand/rand]
      - [0xD0D4, asm, newlib/libc/reent/readr/_read_r]
      - [0xD13C, asm, newlib/libc/stdlib/mallocr/_realloc_r]
      - [0xD694, asm, newlib/libc/reent/reent/cleanup_glue]
      - [0xD6E8, asm, func_psp_0890BFF4]
      - [0xD77C, asm, newlib/libc/reent/reent/_reclaim_reent]
      - [0xD8F0, asm, func_psp_0890C1FC]
      - [0xD9A0, asm, newlib/libc/reent/sbrkr/_sbrk_r]
      - [0xD9FC, asm, newlib/libc/signal/signal/_init_signal_r]
      - [0xDA5C, asm, newlib/libc/signal/signal/_signal_r]
      - [0xDAE4, asm, newlib/libc/signal/signal/_raise_r]
      - [0xDBA8, asm, newlib/libc/signal/signal/__sigtramp_r]
      - [0xDC44, asm, newlib/libc/signal/signal/raise]
      - [0xDC74, asm, newlib/libc/signal/signal/signal]
      - [0xDCB4, asm, newlib/libc/signal/signal/_init_signal]
      - [0xDCD8, asm, newlib/libc/signal/signal/__sigtramp]
      - [0xDD08, asm, newlib/libc/reent/signalr/_kill_r]
      - [0xDD6C, asm, newlib/libc/reent/signalr/_getpid_r]
      - [0xDD88, asm, newlib/libc/stdio/sprintf/_sprintf_r]
      - [0xDDF0, asm, newlib/libc/stdio/sprintf/sprintf]
      - [0xDE70, asm, newlib/libc/stdio/stdio/__sread]
      - [0xDEE8, asm, newlib/libc/stdio/stdio/__swrite]
      - [0xDF74, asm, newlib/libc/stdio/stdio/__sseek]
      - [0xDFEC, asm, newlib/libc/stdio/stdio/__sclose]
      - [0xE01C, asm, newlib/libc/string/strcat/strcat]
      - [0xE0C8, asm, newlib/libc/string/strcmp/strcmp]
      - [0xE13C, asm, newlib/libc/string/strcpy/strcpy]
      - [0xE1D4, asm, newlib/libc/string/strlen/strlen]
      - [0xE1EC, asm, func_psp_0890CAF8]
      - [0xE23C, asm, newlib/libc/stdio/vfprintf/__sprint_r]
      - [0xE288, asm, newlib/libc/stdio/vfprintf/__sbprintf]
      - [0xE330, asm, func_psp_0890CC3C]
      - [0xE3AC, asm, newlib/libc/stdio/vfprintf/_svfprintf_r]
      - [0xFDC4, asm, newlib/libc/stdio/vfprintf/cvt]
      - [0xFF8C, asm, newlib/libc/stdio/vfprintf/exponent]
      - [0x10064, asm, func_psp_0890E970]
      - [0x100D8, asm, func_psp_0890E9E4]
      - [0x10128, asm, newlib/libc/stdlib/wcrtomb/_wcrtomb_r]
      - [0x10194, asm, newlib/libc/stdlib/wcrtomb/wcrtomb]
      - [0x101E4, asm, newlib/libc/stdlib/wcsrtombs/_wcsrtombs_r]
      - [0x1033C, asm, newlib/libc/stdlib/wcsrtombs/wcsrtombs]
      - [0x1039C, asm, newlib/libc/stdlib/wctomb/__wctomb]
      - [0x107BC, asm, newlib/libc/reent/writer/_write_r]
      - [0x10824, asm, newlib/libc/stdio/wsetup/__swsetup_r]
      - [0x10944, c, main_psp/10944]
      - [0x11320, c, main_psp/11320]
      - [0x138B0, c, main_psp/138B0]
      - [0x1528C, c, main_psp/mpeg/avsync]
      - [0x15650, c, main_psp/mpeg/display]
      - [0x1660C, c, main_psp/mpeg/fileread]
      - [0x17364, c, main_psp/mpeg/sound]
      - [0x17D24, c, main_psp/mpeg/strfile]
      - [0x18020, asm, func_psp_0891692C]
      - [0x18078, asm, func_psp_08916984]
      - [0x180DC, asm, func_psp_089169E8]
      - [0x181DC, asm, func_psp_08916AE8]
      - [0x18218, asm, func_psp_08916B24]
      - [0x18254, asm, func_psp_08916B60]
      - [0x182AC, asm, func_psp_08916BB8]
      - [0x182F8, asm, func_psp_08916C04]
      - [0x18334, c, main_psp/18334]
      - [0x18608, asm, func_psp_08916F14]
      - [0x18644, asm, func_psp_08916F50]
      - [0x18680, asm, func_psp_08916F8C]
      - [0x186C8, asm, func_psp_08916FD4]
      - [0x1870C, asm, func_psp_08917018]
      - [0x18754, asm, func_psp_08917060]
      - [0x18798, asm, func_psp_089170A4]
      - [0x1882C, asm, func_psp_08917138]
      - [0x188C0, asm, func_psp_089171CC]
      - [0x18944, asm, func_psp_08917250]
      - [0x189D8, asm, func_psp_089172E4]
      - [0x189F4, asm, func_psp_08917300]
      - [0x18A1C, asm, func_psp_08917328]
      - [0x18B8C, asm, func_psp_08917498]
      - [0x18CE4, asm, func_psp_089175F0]
      - [0x18D84, asm, func_psp_08917690]
      - [0x18E74, asm, func_psp_08917780]
      - [0x18ED0, asm, func_psp_089177DC]
      - [0x18F30, asm, func_psp_0891783C]
      - [0x18F9C, asm, func_psp_089178A8]
      - [0x18FD0, asm, func_psp_089178DC]
      - [0x1913C, asm, func_psp_08917A44]
      - [0x19234, asm, func_psp_08917B40]
      - [0x192C0, c, main_psp/192C0]
      - [0x1982C, asm, func_psp_08918138]
      - [0x19944, asm, func_psp_08918250]
      - [0x19B2C, asm, func_psp_08918438]
      - [0x19C64, asm, func_psp_08918570]
      - [0x19F10, asm, func_psp_0891881C]
      - [0x1A480, asm, func_psp_08918D8C]
      - [0x1A794, c, main_psp/1A794]
      - [0x1B0F0, c, main_psp/1B0F0]
      - [0x1B61C, c, main_psp/1B61C]
      - [0x1BCFC, c, main_psp/1BCFC]
      - [0x2758C, c, main_psp/2758C]
      - [0x280FC, c, main_psp/280FC]
      - [0x28A90, c, main_psp/28A90]
      - [0x2B69C, c, main_psp/2B69C]
      - [0x2D1D4, c, main_psp/dvdumd_io]
      - [0x2D608, c, main_psp/2D608]
      - [0x30F3C, asm, func_psp_0892F848]
      - [0x3104C, asm, func_psp_0892F958]
      - [0x31178, c, main_psp/31178]
      - [0x35670, c, main_psp/35670]
      - [0x359F8, c, main_psp/vector4]
      - [0x36174, c, main_psp/36174]
      - [0x38EF0, asm, func_psp_089377FC]
      - [0x39464, asm, func_psp_08937D70]
      - [0x39A10, asm, func_psp_0893831C]
      - [0x39B40, asm, func_psp_0893844C]
      - [0x39C04, asm, func_psp_08938510]
      - [0x39C34, asm, __extendsfdf2]
      - [0x39C80, asm, func_psp_0893858C]
      - [0x39EE8, asm, func_psp_089387F4]
      - [0x39FFC, asm, func_psp_08938908]
      - [0x3A344, asm, __adddf3]
      - [0x3A3AC, asm, __subdf3]
      - [0x3A420, asm, __muldf3]
      - [0x3A798, asm, __divdf3]
      - [0x3A9BC, asm, func_psp_089392C8]
      - [0x3AB20, asm, __eqdf2]
      - [0x3ABA8, asm, __nedf2]
      - [0x3AC30, asm, __gtdf2]
      - [0x3ACB8, asm, __gedf2]
      - [0x3AD40, asm, func_psp_0893964C]
      - [0x3ADC8, asm, __floatsidf]
      - [0x3AEA4, asm, __fixdfsi]
      - [0x3AF78, asm, __negdf2]
      - [0x3AFBC, asm, func_psp_089398C8]
      - [0x3AFF0, asm, __truncdfsf2]
      - [0x3B068, asm, _start] # crt0.c
      - [0x3B13C, asm, _main] # crt0.c
      - [0x3B3CC, asm, _stop] # crt0.c
      - [0x3B3FC, asm, sce_stub]
      - [0x3B9F4, textbin, sce_stub]
      - [0x3C524, rodata]
      - [0x3D528, .rodata, main_psp/192C0]
      - [0x3D534, .rodata, main_psp/1BCFC]
      - [0x3D564, .rodata, main_psp/280FC]
      - [0x3D580, rodata]
      - [0x3D6B4, .rodata, main_psp/31178]
      - [0x3D760, rodata]
      - [0x3D788, .rodata, main_psp/36174]
      - [0x3D8B8, rodata]
      - [0x3DA1C, rodata] # literal floats
      - [0x3DA9C, rodata] # literal doubles
      - [0x3DC24, data]
      - [0x3E3D0, .data, main_psp/10944]
      - [0x3E3F0, .data, main_psp/11320]
      - [0x3E414, .data, main_psp/138B0]
      - [0x3E4D4, .data, main_psp/mpeg/display]
      - [0x3E540, .data, main_psp/mpeg/fileread]
      - [0x3E554, .data, main_psp/mpeg/sound]
      - [0x3E57C, .data, main_psp/mpeg/strfile]
      - [0x3E5A8, data]
      - [0x3E5C4, .data, main_psp/1B0F0]
      - [0x3E680, .data, main_psp/portrait_data]
      - [0x47B00, data]
      - [0x47B04, .data, main_psp/1B61C]
      - [0x47BC4, .data, main_psp/1BCFC]
      - [0x47D7C, .data, main_psp/2758C]
      - [0x47DA0, .data, main_psp/280FC]
      - [0x6348C, data]
      - [0x647C0, .data, main_psp/2B69C]
      - [0x649A4, .data, main_psp/dvdumd_io]
      - [0x649BC, data]
      - [0x65808, .data, main_psp/31178]
      - [0xAEBAC, data]
      - {start: 0xAEF24, type: bss, vram: 0x089AD830, name: bss0}
      - {start: 0xAEF24, type: .bss, vram: 0x089B6540, name: main_psp/11320}
      - {start: 0xAEF24, type: .bss, vram: 0x08B1FB50, name: main_psp/138B0}
      - {start: 0xAEF24, type: .bss, vram: 0x08B1FB90, name: main_psp/mpeg/avsync}
      - {start: 0xAEF24, type: .bss, vram: 0x08B1FB94, name: main_psp/mpeg/display}
      - {start: 0xAEF24, type: .bss, vram: 0x08B1FBBC, name: main_psp/mpeg/fileread}
      - {start: 0xAEF24, type: .bss, vram: 0x08B1FBDC, name: main_psp/mpeg/sound}
      - {start: 0xAEF24, type: bss, vram: 0x08B1FBFC, name: bss1}
      - {start: 0xAEF24, type: .bss, vram: 0x08B21DE8, name: main_psp/1A794}
      - {start: 0xAEF24, type: bss, vram: 0x08B41F30, name: bss2}
      - {start: 0xAEF24, type: .bss, vram: 0x08B41F40, name: main_psp/1B0F0}
      - {start: 0xAEF24, type: .bss, vram: 0x08B41FB4, name: main_psp/1B61C}
      - {start: 0xAEF24, type: bss, vram: 0x08B41FC0, name: bss3}
      - {start: 0xAEF24, type: .bss, vram: 0x08B42068, name: main_psp/1BCFC}
      - {start: 0xAEF24, type: bss, vram: 0x08C63124, name: bss4}
      - {start: 0xAEF24, type: .bss, vram: 0x08C63C28, name: main_psp/28A90}
      - {start: 0xAEF24, type: bss, vram: 0x08C6BC30, name: bss5}
      - {start: 0xAEF24, type: .bss, vram: 0x08DAF2C8, name: main_psp/31178}
      - {start: 0xAEF24, type: bss, vram: 0x08E2E5F8, name: bss6}
  - [0xAEF24, bin, elf_footer]
  - [0xB3E1C]