options:
  platform:     psx
  basename:     stno3
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/ST/NO3/NO3.BIN
  asm_path:     asm/us/st/no3
  asset_path:   assets/st/no3
  src_path:     src/st/no3
  ld_script_path: build/us/stno3.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/symbols.us.txt
    - config/symbols.us.stno3.txt
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.stno3.txt
  undefined_syms_auto_path:  config/undefined_syms_auto.us.stno3.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  migrate_rodata_to_functions: no
  asm_jtbl_label_macro: jlabel
  extensions_path: tools/splat_ext
  section_order:
    - ".data"
    - ".rodata"
    - ".text"
    - ".bss"
    - ".sbss"
segments:
  - name: stno3
    type: code
    start: 0x00000000
    vram:  0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, data]
      #- [0x1C4, layers, rooms]
      - [0x5A4, data]
      - [0x920, data]
      - [0xAAC, data]
      - [0xDC0, data]
      - [0xDD0, data]
      - [0xE50, data]
      - [0xE70, data]
      - [0xE80, data]
      - [0xE90, data]
      - [0xEA0, data]
      - [0x11F0, data]
      - [0x1B40, data]
      - [0x1CEC, .data, collision]
      - [0x20AC, .data, e_red_door]
      - [0x20C4, data]
      - [0x25B4, .data, entity_relic_orb]
      - [0x2618, data]
      - [0x3180, data]
      - [0x39A0, data]
      - [0x3AC0, data]
      - [0x3AF0, data]
      - [0x3B30, data]
      - [0x3CC4, roomdef, g_Rooms]
      - [0x3DC8, data]
      - [0x4CE0, data]
      - [0x18838, tilelayout, D_80198838]
      - [0x19438, tilelayout, D_80199438]
      - [0x19638, tilelayout, D_80199638]
      - [0x19A38, tilelayout, D_80199A38]
      - [0x19E38, tilelayout, D_80199E38]
      - [0x1AC38, tilelayout, D_8019AC38]
      - [0x1AE38, tilelayout, D_8019AE38]
      - [0x1B038, tilelayout, D_8019B038]
      - [0x1B238, tilelayout, D_8019B238]
      - [0x1B638, tilelayout, D_8019B638]
      - [0x1BA38, tilelayout, D_8019BA38]
      - [0x1C238, tilelayout, D_8019C238]
      - [0x1CA38, tilelayout, D_8019CA38]
      - [0x1CC38, tilelayout, D_8019CC38]
      - [0x1CE38, tilelayout, D_8019CE38]
      - [0x1DA38, tilelayout, D_8019DA38]
      - [0x1E638, tilelayout, D_8019E638]
      - [0x1E838, tilelayout, D_8019E838]
      - [0x1EA38, tilelayout, D_8019EA38]
      - [0x1F638, tilelayout, D_8019F638]
      - [0x1F838, tilelayout, D_8019F838]
      - [0x1FA38, tilelayout, D_8019FA38]
      - [0x1FC38, tilelayout, D_8019FC38]
      - [0x20038, tilelayout, D_801A0038]
      - [0x20238, tilelayout, D_801A0238]
      - [0x20838, tilelayout, D_801A0838]
      - [0x20E38, tilelayout, D_801A0E38]
      - [0x21038, tilelayout, D_801A1038]
      - [0x21238, tilelayout, D_801A1238]
      - [0x21438, tilelayout, D_801A1438]
      - [0x21638, tilelayout, D_801A1638]
      - [0x22238, tilelayout, D_801A2238]
      - [0x22E38, tilelayout, D_801A2E38]
      - [0x23038, tilelayout, D_801A3038]
      - [0x23238, tilelayout, D_801A3238]
      - [0x23438, tilelayout, D_801A3438]
      - [0x23638, tilelayout, D_801A3638]
      - [0x25A38, tilelayout, D_801A5A38]
      - [0x25C38, tilelayout, D_801A5C38]
      - [0x25E38, tilelayout, D_801A5E38]
      - [0x26038, tilelayout, D_801A6038]
      - [0x26238, tilelayout, D_801A6238]
      - [0x26438, tilelayout, D_801A6438]
      - [0x26638, tiledef, t_801A6A38, D_801A6A38]
      - [0x26A48, tiledef, t_801AAA48, D_801AAA48]
      - [0x2AA58, tiledef, t_801AEA58, D_801AEA58]
      - [0x2EA68, data]
      - [0x373E0, data]
      - [0x373E8, .rodata, 377D4] # EntityCastleDoor
      - [0x37400, .rodata, 377D4] # EntityStairwayPiece
      - [0x37414, .rodata, 3C4EC]
      - [0x3742C, .rodata, 3E134] #EntityFlyingOwlAndLeaves
      - [0x37440, rodata]
      - [0x37458, .rodata, deathcutscene] # EntityDeathCutscene
      - [0x374DC, .rodata, 3FF00] # EntityRoomTransition2
      - [0x374F4, .rodata, 3FF00] # EntityDeathStolenItems
      - [0x37514, .rodata, 3FF00] # EntityDeath
      - [0x37564, .rodata, 3FF00] # EntityWargExplosionPuffOpaque
      - [0x37578, .rodata, e_red_door] # EntityRedDoor
      - [0x37590, rodata]
      - [0x375E0, .rodata, 46684] # EntityPrizeDrop
      - [0x37600, .rodata, 46684] # EntityEquipItemDrop
      - [0x37618, .rodata, entity_relic_orb]
      - [0x37650, .rodata, entity_message_box]
      - [0x37664, .rodata, 48A84] # EntityStageNamePopup
      - [0x37698, rodata]
      - [0x376E8, rodata]
      - [0x377A4, .rodata, 56264] # EntityBat
      - [0x377B8, .rodata, 564B0] # EntityZombie
      - [0x377CC, .rodata, prim_helpers]
      - [0x377D4, c]
      - [0x3C4EC, c]
      - [0x3E134, c]
      - [0x3E544, c, deathcutscene]
      - [0x3FF00, c]
      - [0x4184C, c, random]
      - [0x4187C, c, update]
      - [0x41B78, c, update_stage_entities]
      - [0x41C80, c, collision]
      - [0x4343C, c, create_entity]
      - [0x43FB4, c, e_red_door]
      - [0x44C64, c]
      - [0x46684, c]
      - [0x47930, c, entity_relic_orb]
      - [0x48400, c, entity_heart_drop]
      - [0x48528, c, entity_message_box]
      - [0x48A84, c]
      - [0x56264, c]
      - [0x564B0, c]
      - [0x56880, c, prim_helpers]
      - [0x570B0, sbss]
  - [0x57E18]
