name: Build Maria (PSP) for PSX

on:
  push:
    branches:
      - master
    paths:
      - 'include/**'
      - 'src/maria/**'
      - 'mods/mariapsp-forpsx/**'
  pull_request:
    paths:
      - 'include/**'
      - 'src/maria/**'
      - 'mods/mariapsp-forpsx/**'
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'Xeeynamo/sotn-decomp'
    strategy:
        matrix:
          version: ["us"]
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ matrix.version }}
    steps:
      - name: Install requirements
        run: sudo apt-get install gcc-mipsel-linux-gnu
      - name: Clone repo
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
          submodules: false
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.4'
      - name: Get dependencies
        uses: ./.github/actions/get-dependencies
        with:
          token: ${{ secrets.SOTN_DECOMP_DEPENDENCIES_TOKEN }}
      - name: Extract dependencies
        run: |
          mkdir -p ~/go/bin
          ln -s $(which go) ~/go/bin/
          VERSION=pspeu make extract_disk
      - name: build
        working-directory: mods/mariapsp-forpsx
        run: VERSION=${{ matrix.version }} make
  push-docker-image:
    if: github.repository == 'Xeeynamo/sotn-decomp' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Clone main repository
        uses: actions/checkout@v6
        with:
          submodules: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./mods/mariapsp-forpsx
          file: ./mods/mariapsp-forpsx/Dockerfile
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/sotn-mariapsp-forpsx:latest
