name: Build Saturn version

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '**/*.md'
  pull_request_target:
    paths-ignore:
      - '*.md'
      - '**/*.md'
  workflow_dispatch:

jobs:
  build-and-test-saturn:
    # Building and testing cannot work if the repository owner is not Xeeynamo
    # due to the missing secrets to clone the game's data repository
    if: github.repository == 'Xeeynamo/sotn-decomp'
    runs-on: ubuntu-latest
    steps:
      - name: Clone main repo
        uses: actions/checkout@v3
        with:
          submodules: false
      - name: Clone dependencies
        uses: actions/checkout@v3
        with:
          repository: xeeynamo/sotn-decomp-dependencies
          ref: saturn
          token: ${{ secrets.SOTN_DECOMP_DEPENDENCIES_TOKEN }}
          path: 'disks/dependencies'
      - name: Setting up dependencies
        working-directory: disks
        run: |
          cat dependencies/* > dependencies.tar.gz
          tar -xf dependencies.tar.gz
          mv *.cue sotn.saturn.cue
          mv *.bin sotn.saturn.bin
      - name: Install bchunk 7zip
        run: |
          sudo apt-get install p7zip-full bchunk
      - name: Install dosemu
        run: |
          sudo apt-get install -y -o APT::Immediate-Configure=false \
          dos2unix software-properties-common && \
          sudo add-apt-repository -y ppa:dosemu2/ppa && \
          sudo apt-get update && \
          sudo apt-get install -y dosemu2;
      - name: Prep
        run: make -j saturn_ci_tasks
      - name: Extract asm
        run: make extract_saturn
      - name: Build saturn binaries
        run: make build_saturn_ci
      - name: Check saturn
        run: make check_saturn
